/*
 * Doctor Career: GCSE cases (AQA 8461). Every illness, test idea and treatment below comes from the specification (the spec reference is on each case).
 * A case has a file, ten or so questions (you have time for six), several tests (you can order three), a list of possible diagnoses, the
 * facts that really separate them, and four things you could do. `twist` says how first impressions mislead.
 */
(function (root) {
  var D = root.DOCTOR = root.DOCTOR || {}; D.cases = D.cases || [];
  var P = '/assets/doctor/';

  D.add({
    id: 'g01', track: 'gcse', rank: 0, minutes: 10,
    title: 'A rash and a temperature', tagline: 'Strawberries, a new washing powder and a very hot little boy',
    complaint: 'Fever for three days, and a red rash this morning',
    patient: { name: 'Oliver Hughes', age: 4, job: 'Nursery pupil', setting: 'GP surgery, same-day appointment', image: P + 'g01.jpg',
      look: 'a four-year-old white boy with short fair hair, flushed cheeks, red watery eyes, wearing a dinosaur T-shirt, sitting on his father\'s lap in a doctor\'s surgery' },
    opening: 'Oliver is hot, tired and grumpy. His dad does the talking.',
    referral: 'Dad phoned at 08:10. Oliver has had a **high temperature for three days** and a **red rash appeared on his face this morning**. Dad thinks it is an allergy: Oliver ate strawberries yesterday and the family changed washing powder last week.',
    obs: [['Temperature', '39.4 °C'], ['Pulse', '126 per minute'], ['Breathing', '28 per minute'], ['Alertness', 'Tired, but responds']],
    notes: ['Lives with his parents and his baby sister, aged 5 months.', 'Goes to nursery three days a week.', 'No allergies, asthma or eczema recorded.', 'The rash is red, blotchy and flat, and is spreading down his neck.'],
    startFacts: ['temp', 'rash'],
    facts: {
      temp: 'Temperature of 39.4 °C', rash: 'A red, blotchy rash that started on his face this morning',
      order: 'The fever began three days before the rash appeared', noitch: 'The rash is not itchy',
      cold: 'He also has a runny nose, a hacking cough and sore red eyes', unvacc: 'He has never had the MMR vaccination',
      contact: 'Two children at his nursery were sent home last week with a fever and spots', straw: 'He ate strawberries yesterday but has eaten them before without trouble',
      nogut: 'No vomiting, diarrhoea or stomach cramps', nowheeze: 'No wheeze or difficulty breathing', drink: 'He is only taking sips of fluid',
      record: 'His vaccination record shows no MMR doses', swab: 'The throat swab found the measles virus', blood: 'His blood contains antibodies to the measles virus',
      prick: 'A skin prick test is negative for strawberry',
    },
    questions: [
      { id: 'q1', q: 'Which came first, the fever or the rash?', a: 'The **fever came first**, three days ago. The rash only appeared this morning, behind his ears and on his face. It has been creeping down his neck since.', fact: 'order' },
      { id: 'q2', q: 'Is the rash itchy?', a: 'No, he is not scratching at all. It just looks angry.', fact: 'noitch' },
      { id: 'q3', q: 'Does he have a cough, a runny nose or red eyes?', a: 'All three. His eyes are red and sore and he keeps rubbing them. He has had a hacking cough since the weekend.', fact: 'cold' },
      { id: 'q4', q: 'Has he had his MMR vaccination?', a: 'No. We moved in the spring and the appointment letter went to our old address. We never booked another.', fact: 'unvacc' },
      { id: 'q5', q: 'Has anyone around him been ill?', a: 'Two children at nursery were sent home last week with a fever and spots. The nursery sent a letter but I have not read it properly.', fact: 'contact' },
      { id: 'q6', q: 'What did he eat and touch recently?', a: 'Strawberries for pudding yesterday. He has had them at his nan\'s before and been fine. And a new washing powder last week.', fact: 'straw' },
      { id: 'q7', q: 'Has he been sick or had diarrhoea?', a: 'No, not at all. He just does not want to eat.', fact: 'nogut' },
      { id: 'q8', q: 'Is he wheezy or struggling to breathe?', a: 'No, just the cough.', fact: 'nowheeze' },
      { id: 'q9', q: 'How much is he drinking?', a: 'Only sips.', fact: 'drink' },
      { id: 'q10', q: 'What did you have for dinner last night?', a: 'Er, pasta? I am not sure what that has to do with it.', value: 'waste' },
      { id: 'q11', q: 'What is his favourite cartoon?', a: 'Dinosaur Train. Why do you ask?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Check his vaccination record', note: 'The red book the parents carry', result: 'No MMR doses are recorded.', fact: 'record', value: 'key' },
      { id: 't2', name: 'Throat swab sent for virus testing', result: 'The laboratory finds the **measles virus**.', fact: 'swab', value: 'key' },
      { id: 't3', name: 'Blood test for antibodies', note: 'Looks for the body\'s own response', result: 'His blood contains **antibodies to the measles virus**: his white blood cells are fighting it now.', fact: 'blood', value: 'useful' },
      { id: 't4', name: 'Skin prick allergy test', result: 'Negative for strawberry. This does not explain the fever.', fact: 'prick', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. He was exposed to radiation for no good reason.', value: 'risky' },
      { id: 't6', name: 'Stool sample', result: 'Normal. There was no stomach problem to find.', value: 'waste' },
    ],
    options: [
      { id: 'measles', name: 'Measles', sub: 'A viral disease' },
      { id: 'allergy', name: 'An allergic reaction', sub: 'A skin rash caused by an immune overreaction' },
      { id: 'salmonella', name: 'Salmonella food poisoning', sub: 'A bacterial infection from food' },
    ],
    truth: 'measles', decisive: ['order', 'cold', 'unvacc', 'contact', 'swab', 'blood', 'record'],
    treatments: [
      { id: 'x1', label: 'Keep him away from other children, give paracetamol and fluids, and tell the nursery and public health', verdict: 'best', why: 'Measles is spread by droplets from coughs and sneezes, so isolating him protects others, especially babies like his sister who are too young to be vaccinated. Paracetamol treats the **symptoms** of the fever; it does not kill the virus. Telling the nursery lets other families check their children\'s vaccinations.' },
      { id: 'x2', label: 'Prescribe penicillin', verdict: 'wrong', why: '**Antibiotics cannot kill viruses.** Measles is viral, so penicillin would do nothing, and using antibiotics inappropriately helps resistant bacteria spread.' },
      { id: 'x3', label: 'Prescribe an antihistamine and send him back to nursery tomorrow', verdict: 'harm', why: 'This treats an allergy he does not have, and sends a child with a highly infectious virus back to a room with unvaccinated babies and toddlers.' },
      { id: 'x4', label: 'Paracetamol and fluids at home, and nothing more', verdict: 'ok', why: 'Right for the symptoms, but it misses the need to stop the spread and to alert the nursery.' },
    ],
    outcome: {
      right: 'Oliver recovered over the following week with rest and fluids. The nursery told every family, two unvaccinated toddlers were offered protection, and his baby sister, too young to be vaccinated, was watched closely and stayed well. His parents booked his MMR that same afternoon.',
      wrong: 'Oliver\'s rash spread and his fever went on. By the weekend he was back at the surgery, and by then the infection had been passed to children at his nursery. Looking back, the order of events (fever and a cold first, rash later) and the missed vaccination were the signs.',
    },
    twist: 'Strawberries and a new washing powder made this sound like an allergy. But an allergic rash itches and usually comes without a fever, whereas measles begins with a fever and a cold-like illness, and the rash arrives last. The lessons on **measles** and **allergies** cover both.',
    lessons: ['measles', 'allergy', 'vaccination', 'antibiotics'],
    spec: { board: 'AQA', code: '8461', refs: ['4.3.1.2 viral diseases', '4.3.1.7 vaccination', '4.2.2.5 health issues (allergies)', '4.3.1.8 antibiotics'] },
  });

  D.add({
    id: 'g02', track: 'gcse', rank: 0, minutes: 10,
    title: 'The holiday that would not leave', tagline: 'A fever that goes away and keeps coming back',
    complaint: 'Shaking fevers every few days since coming home',
    patient: { name: 'Tunde Bello', age: 34, job: 'Accountant', setting: 'Walk-in clinic', image: P + 'g02.jpg',
      look: 'a thirty-four-year-old Black British man in a creased office shirt, looking exhausted and sweaty, sitting in a clinic chair with a blanket over his shoulders' },
    opening: 'Tunde looks wrung out. He says he feels fine one day and dreadful the next.',
    referral: 'Reception note: **returned from a three-week family trip to rural Nigeria 3 weeks ago**. Since then, three bouts of high fever with shaking chills and drenching sweats, a few days apart. He thinks it is flu.',
    obs: [['Temperature', '39.8 °C (today)'], ['Pulse', '110 per minute'], ['Breathing', '22 per minute'], ['Skin', 'Pale and sweaty']],
    notes: ['Works long hours, no previous illnesses.', 'Took paracetamol, which brought the fever down for a few hours each time.', 'No rash, no cough, no sore throat.', 'Had a new partner two months ago.'],
    startFacts: ['temp', 'travel'],
    facts: {
      temp: 'Temperature of 39.8 °C with sweating', travel: 'He travelled to a country where malaria occurs, three weeks ago',
      waves: 'The fevers come in waves with feeling better in between', bitten: 'He was bitten by mosquitoes many times and did not use a net',
      notab: 'He took no anti-malaria medicine before or during the trip', norash: 'No rash, no sore throat and no cough',
      partner: 'He had a new partner two months ago but they used condoms', nogut: 'No vomiting, diarrhoea or stomach cramps', contacts: 'Nobody else in his household is ill',
      film: 'A blood sample shows protist cells, the malaria pathogen', hivneg: 'The HIV test is negative', swabneg: 'The throat swab finds no virus',
    },
    questions: [
      { id: 'q1', q: 'Where exactly did you travel, and when?', a: 'Three weeks in a village in **southern Nigeria**. We got back three weeks ago.', fact: 'travel' },
      { id: 'q2', q: 'What are the fevers like? Do they come and go?', a: 'They come in **waves**. Two or three days of nothing, then suddenly I am freezing, shaking, then burning, then drenched. Then I feel almost normal again.', fact: 'waves' },
      { id: 'q3', q: 'Were you bitten by mosquitoes?', a: 'Constantly. The nights were awful. We slept without nets because my cousin said they were hot and stuffy.', fact: 'bitten' },
      { id: 'q4', q: 'Did you take any tablets to prevent malaria?', a: 'No, I had not planned ahead. I have been there before and I was fine.', fact: 'notab' },
      { id: 'q5', q: 'Do you have a rash, cough or sore throat?', a: 'No. Just fever, aching, a headache and feeling wiped out.', fact: 'norash' },
      { id: 'q6', q: 'Have you had any recent sexual partners, and was it protected?', a: 'I met someone two months ago. We have always used condoms. I got an all-clear screen at the time, though I have not repeated it since.', fact: 'partner' },
      { id: 'q7', q: 'Any vomiting or diarrhoea?', a: 'A little nausea when the fever peaks, but nothing else.', fact: 'nogut' },
      { id: 'q8', q: 'Is anyone at home or work ill with the same thing?', a: 'No. My wife and my team are fine. Nobody else travelled.', fact: 'contacts' },
      { id: 'q9', q: 'What is your job and how many hours do you work?', a: 'I am an accountant, about 55 hours a week.', value: 'waste' },
      { id: 'q10', q: 'Do you support a football team?', a: 'Er, Arsenal? Are we nearly done?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Blood film under the microscope', note: 'Looks for pathogens in the blood', result: 'Protist cells are seen inside the blood cells: the pathogen that causes **malaria**.', fact: 'film', value: 'key' },
      { id: 't2', name: 'HIV test', note: 'Because of the flu-like illness', result: 'Negative.', fact: 'hivneg', value: 'useful' },
      { id: 't3', name: 'Throat swab for virus testing', result: 'No virus found.', fact: 'swabneg', value: 'useful' },
      { id: 't4', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. No reason to have done it: he has no cough or breathing problem.', value: 'risky' },
      { id: 't5', name: 'Stool sample', result: 'Normal.', value: 'waste' },
      { id: 't6', name: 'Skin prick allergy test', result: 'Not helpful: nothing here suggests an allergy.', value: 'waste' },
    ],
    options: [
      { id: 'malaria', name: 'Malaria', sub: 'A protist disease carried by mosquitoes' },
      { id: 'hiv', name: 'The flu-like illness of early HIV infection', sub: 'A viral disease' },
      { id: 'measles', name: 'Measles', sub: 'A viral disease with a fever and a rash' },
      { id: 'salmonella', name: 'Salmonella food poisoning', sub: 'A bacterial infection' },
    ],
    truth: 'malaria', decisive: ['travel', 'waves', 'bitten', 'notab', 'film'],
    treatments: [
      { id: 'x1', label: 'Admit him for anti-malarial medicine, and advise nets and protection for any future trip', verdict: 'best', why: 'Malaria is a **protist** disease, so it needs specific anti-malarial medicine. It is not spread directly between people; it is spread by the **mosquito vector**, so the long-term control is **nets and stopping mosquitoes from breeding**.' },
      { id: 'x2', label: 'Prescribe penicillin', verdict: 'wrong', why: '**Antibiotics kill bacteria.** Malaria is caused by a protist, so penicillin does nothing, and misusing antibiotics helps resistant bacteria to spread.' },
      { id: 'x3', label: 'Tell him it is flu, advise paracetamol and send him home', verdict: 'harm', why: 'Paracetamol treats the **symptom**. Left untreated, malaria can be fatal, so sending him away is dangerous.' },
      { id: 'x4', label: 'Isolate him from his family as he is very infectious', verdict: 'wrong', why: 'Malaria is not passed from person to person like measles. It is carried by mosquitoes, so isolation does not stop its spread.' },
    ],
    outcome: {
      right: 'Tunde was treated with anti-malarial medicine and was back at work in two weeks. He now sleeps under a net whenever he travels and takes tablets before he goes.',
      wrong: 'Tunde got worse overnight and was admitted by ambulance with a dangerously high fever. He recovered, but only after a delay that did not need to happen. Asking where he had been, and whether the fevers kept coming back, would have pointed to malaria on the first visit.',
    },
    twist: 'Fever, aching and chills sound like flu, and a flu-like illness is also how HIV begins. What separates malaria is **where he has been** and **how the fever keeps returning in waves**. The lessons on **malaria** and **HIV** cover both, along with **antibiotics**, which cannot help either.',
    lessons: ['malaria', 'hiv', 'pathogens', 'antibiotics'],
    spec: { board: 'AQA', code: '8461', refs: ['4.3.1.5 protist diseases', '4.3.1.2 viral diseases (HIV)', '4.3.1.8 antibiotics'] },
  });

  D.add({
    id: 'g03', track: 'gcse', rank: 1, minutes: 10,
    title: 'The thirsty teenager', tagline: 'Overweight, a grandad with diabetes, and a sudden change',
    complaint: 'Constant thirst, passing urine all the time, losing weight',
    patient: { name: 'Kai Morgan', age: 15, job: 'Year 11 pupil', setting: 'GP surgery', image: P + 'g03.jpg',
      look: 'a fifteen-year-old mixed-heritage boy with a slightly round build, pale and tired, holding a large water bottle, in school uniform, in a doctor\'s office' },
    opening: 'Kai drains his bottle of water and asks if he can fill it up again.',
    referral: 'Mum reports Kai is **drinking litres every day**, **getting up several times a night to pass urine**, and has **lost weight over the last six weeks** without trying. His grandfather has Type 2 diabetes, so she is worried.',
    obs: [['Temperature', '36.8 °C'], ['Pulse', '104 per minute'], ['Weight', '78 kg (was 86 kg two months ago)'], ['Urine dipstick', 'Glucose present']],
    notes: ['Overweight for his age. Eats a lot of snacks and fizzy drinks.', 'Plays football for the school team.', 'Very tired in lessons. Mum thinks it is exam stress.', 'Grandfather was diagnosed with Type 2 diabetes at 63.'],
    startFacts: ['weight', 'urine'],
    facts: {
      weight: 'He has lost 8 kg in two months without trying', urine: 'There is glucose in his urine', fast: 'The symptoms came on quickly, over about six weeks',
      thirst: 'He drinks several litres a day and wakes at night to pass urine', fam: 'His grandfather has Type 2 diabetes', eats: 'He is eating more than usual but still losing weight',
      bg: 'His blood glucose is 24 mmol per litre (normal is 4 to 8)', curve: 'After a glucose drink his blood insulin stays low while his blood glucose stays high',
      insulin: 'Kai is overweight and has gained weight in the past, but not recently', sport: 'He had no unusual sports training or sweating',
    },
    questions: [
      { id: 'q1', q: 'How long has this been going on?', a: 'About **six weeks**. It was gradual at first, then it got really bad in the last fortnight.', fact: 'fast' },
      { id: 'q2', q: 'How much is he drinking and passing urine?', a: 'Three or four litres a day, easily. He is up two or three times every night.', fact: 'thirst' },
      { id: 'q3', q: 'Has his weight changed?', a: 'He has gone **down**, and he was always a bigger lad. His trousers are falling off. I thought it was the football.', fact: 'weight' },
      { id: 'q4', q: 'Is his appetite normal?', a: 'He is ravenous. He eats everything in the house and still looks thinner.', fact: 'eats' },
      { id: 'q5', q: 'Does diabetes run in the family?', a: 'His granddad has the Type 2. He was told it was because of his weight.', fact: 'fam' },
      { id: 'q6', q: 'Has he been doing extra sport or sweating a lot?', a: 'No more than usual: a training session on Thursdays and a match at the weekend.', fact: 'sport' },
      { id: 'q7', q: 'Has his weight been going up recently?', a: 'He gained a lot at 12 and 13, but not recently. If anything, he has been losing it.', fact: 'insulin' },
      { id: 'q8', q: 'Is he stressed about exams?', a: 'A bit, but he is not worried. He just says he feels tired all the time.', value: 'waste' },
      { id: 'q9', q: 'What is his favourite subject?', a: 'PE, obviously, though he has been missing it lately.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Blood glucose test (finger prick)', result: 'Blood glucose is **24 mmol per litre**. Normal is about 4 to 8.', fact: 'bg', value: 'key' },
      { id: 't2', name: 'Glucose drink test with blood insulin measured', note: 'He drinks a measured glucose drink; blood is sampled over two hours', fact: 'curve', value: 'key',
        result: 'The graph of his results is below. In a person without diabetes, insulin would rise soon after the drink and glucose would fall back.',
        table: [['Time (minutes)', '0', '30', '60', '120'], ['Blood glucose (mmol per litre)', '19', '27', '30', '28'], ['Blood insulin (units)', '3', '4', '4', '4']] },
      { id: 't3', name: 'Check his weight chart', result: 'Weight 86 kg two months ago, 78 kg today: he is **losing weight**.', value: 'useful' },
      { id: 't4', name: 'Cholesterol blood test', result: 'Slightly raised. Not useful for deciding what is wrong today.', value: 'waste' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. Radiation without any reason.', value: 'risky' },
      { id: 't6', name: 'Throat swab', result: 'Nothing found.', value: 'waste' },
    ],
    options: [
      { id: 'type1', name: 'Type 1 diabetes', sub: 'The pancreas fails to produce enough insulin' },
      { id: 'type2', name: 'Type 2 diabetes', sub: 'The body cells no longer respond to insulin' },
      { id: 'dehydration', name: 'Dehydration from sport', sub: 'Too much water lost in sweat' },
    ],
    truth: 'type1', decisive: ['weight', 'fast', 'curve', 'insulin', 'bg', 'eats'],
    treatments: [
      { id: 'x1', label: 'Start insulin injections, and teach him about carbohydrate in his diet and exercise', verdict: 'best', why: 'In **Type 1** the pancreas does not make enough insulin, so insulin must be replaced by injections. Diet and exercise help him keep his glucose steady.' },
      { id: 'x2', label: 'A carbohydrate-controlled diet and an exercise plan, and review in six months', verdict: 'harm', why: 'That is the treatment for **Type 2**. With no insulin, his blood glucose will stay dangerously high for six months.' },
      { id: 'x3', label: 'Tell him to drink more water and rest', verdict: 'wrong', why: 'The thirst is a symptom of his high blood glucose. More water does not fix the cause.' },
      { id: 'x4', label: 'Insulin injections, but no diet advice', verdict: 'ok', why: 'The insulin is right, but diet and exercise are still an important part of keeping glucose steady.' },
    ],
    outcome: {
      right: 'Kai learned to inject insulin and count his carbohydrate. Within a month he was back to playing football, steadier, with his weight levelling out. His mum says his tiredness lifted in a week.',
      wrong: 'Kai got worse over the next fortnight and was admitted to hospital with very high blood glucose. He is now on insulin, and the delay was avoidable: he was losing weight and his insulin stayed low in the test.',
    },
    twist: 'Overweight, a grandad with Type 2, a diet full of snacks: all of it points to **Type 2**. But he is **losing weight fast**, the illness came on quickly, and after a sugary drink his **insulin stays low**. That means his pancreas is not making it, which is **Type 1**. Read both **diabetes** lessons.',
    lessons: ['diabetes', 'lifestyle', 'waterbalance'],
    spec: { board: 'AQA', code: '8461', refs: ['4.5.3.2 control of blood glucose concentration (Type 1 and Type 2)', '4.2.2.6 lifestyle and non-communicable disease'] },
  });

  D.add({
    id: 'g04', track: 'gcse', rank: 1, minutes: 10,
    title: 'Chest pain on the stairs', tagline: 'Stress at work, a heavy smoker, and a pounding heart',
    complaint: 'Tight chest when climbing stairs, eased by rest',
    patient: { name: 'Dennis Clarke', age: 57, job: 'Bus driver', setting: 'GP surgery', image: P + 'g04.jpg',
      look: 'a fifty-seven-year-old white man with grey hair and a heavy build, in a high-visibility jacket, rubbing his chest with a worried expression, sitting in a doctor\'s office' },
    opening: 'Dennis is embarrassed to be here. He says it is probably just stress.',
    referral: 'Dennis, 57, reports **tightness in his chest when walking uphill or climbing stairs**. It goes after a few minutes of rest. He puts it down to stress at work and rushing his meals.',
    obs: [['Pulse', '84 per minute at rest'], ['Blood pressure', '152 / 94'], ['Weight', 'BMI 31 (obese)'], ['Breathing', '18 per minute']],
    notes: ['Smokes about 20 cigarettes a day for 35 years.', 'Eats a lot of fried food and takes little exercise.', 'His father died of a heart attack aged 60.', 'Says work has been very stressful since a reorganisation.'],
    startFacts: ['bp', 'smoker'],
    facts: {
      bp: 'Blood pressure is raised at 152 / 94', smoker: 'He has smoked 20 a day for 35 years',
      effort: 'The pain comes on with effort (stairs, hills) and eases within minutes of resting', notstress: 'It does not come on when he is stressed but sitting still',
      father: 'His father died of a heart attack at 60', diet: 'He eats a lot of fatty food and does little exercise', pounding: 'He sometimes feels his heart pounding, but only after arguments at work',
      murmur: 'The heart sounds normal: no sign of a faulty valve', angio: 'The scan of the coronary arteries shows narrowing by layers of fatty material',
      chol: 'His blood cholesterol is high', exercise: 'On a treadmill the chest tightness returns when his heart is working hard',
    },
    questions: [
      { id: 'q1', q: 'When exactly do you get the tightness?', a: 'Going **up stairs**, walking up the hill to the depot, carrying shopping. It stops if I **stand still for a couple of minutes**.', fact: 'effort' },
      { id: 'q2', q: 'Does it happen when you are stressed but sitting down?', a: 'No. When I am wound up at work, my heart thumps, but my chest does not tighten like this.', fact: 'notstress' },
      { id: 'q3', q: 'Do you ever feel your heart pounding?', a: 'Yes, after a row with my manager. It settles within a few minutes.', fact: 'pounding' },
      { id: 'q4', q: 'Do you smoke?', a: 'Twenty a day. Thirty-five years. I know, I know.', fact: 'smoker' },
      { id: 'q5', q: 'Is there any heart disease in your family?', a: 'My dad had a heart attack and died at 60.', fact: 'father' },
      { id: 'q6', q: 'What is your diet and exercise like?', a: 'Chips, mostly. Fry-ups at the depot. I sit all day driving and the most exercise I get is the stairs at home.', fact: 'diet' },
      { id: 'q7', q: 'Does the pain come after meals, or when you lie down?', a: 'No, I have had indigestion before and this is different. It is a pressing tightness, not burning.', value: 'useful' },
      { id: 'q8', q: 'Do you feel breathless or dizzy at rest?', a: 'No. Only when I am pushing up the stairs.', value: 'useful' },
      { id: 'q9', q: 'What route do you drive?', a: 'The 42, from the depot to the station and back.', value: 'waste' },
      { id: 'q10', q: 'Which team do you support?', a: 'Villa. Why?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Listen to the heart with a stethoscope', note: 'Checks the valves', result: 'The heart sounds are **normal**. No sign of a faulty valve.', fact: 'murmur', value: 'useful' },
      { id: 't2', name: 'Heart monitor during exercise (treadmill)', result: 'The chest tightness returns when his heart is working hard, and eases as he slows down.', fact: 'exercise', value: 'key' },
      { id: 't3', name: 'Scan of the coronary arteries with dye', note: 'Specialist test', result: 'Two coronary arteries are **narrowed by layers of fatty material**, reducing blood flow to the heart muscle.', fact: 'angio', value: 'key' },
      { id: 't4', name: 'Blood cholesterol test', result: 'His cholesterol is **high**.', fact: 'chol', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. It does not help explain pain on effort.', value: 'waste' },
      { id: 't6', name: 'Sleep study', result: 'Unnecessary for this complaint.', value: 'waste' },
    ],
    options: [
      { id: 'chd', name: 'Coronary heart disease', sub: 'Fatty material is narrowing the coronary arteries' },
      { id: 'adrenaline', name: 'An adrenaline response to stress', sub: 'The heart races after a scare or row' },
      { id: 'valve', name: 'A faulty heart valve', sub: 'A valve that does not open fully or leaks' },
    ],
    truth: 'chd', decisive: ['effort', 'notstress', 'angio', 'exercise', 'chol', 'murmur'],
    treatments: [
      { id: 'x1', label: 'Refer for a stent to open the narrowed artery, start a statin, and advise stopping smoking, diet and exercise', verdict: 'best', why: 'A **stent** keeps a coronary artery open. **Statins** lower blood cholesterol, slowing the build-up of fatty material. Smoking, diet and lack of exercise are risk factors, so changing them matters.' },
      { id: 'x2', label: 'A statin and lifestyle changes only, with no further tests', verdict: 'ok', why: 'These are sensible, but with two narrowed arteries on the scan, a stent may be needed to protect his heart.' },
      { id: 'x3', label: 'Tell him it is stress, to relax and take paracetamol', verdict: 'harm', why: 'Missing coronary heart disease risks a heart attack. Adrenaline from stress does not explain pain that follows effort and eases at rest.' },
      { id: 'x4', label: 'Replace his heart valve', verdict: 'wrong', why: 'His valves are working normally. Valve replacement is for a valve that fails to open fully or leaks.' },
    ],
    outcome: {
      right: 'Dennis had a stent fitted and a statin started. He gave up smoking over the following months and was back at work within six weeks, climbing the depot hill without stopping.',
      wrong: 'Dennis was sent away with reassurance. Three weeks later he had a heart attack on the stairs at the depot. He survived, and had the stent that should have been arranged earlier.',
    },
    twist: 'A pounding heart and a stressful job sound like **adrenaline**. And chest pain can also come from a **faulty valve**. But Dennis\'s tightness only comes **on effort** and **eases with rest**, and the scan shows the real cause. The lessons on **coronary heart disease** and **adrenaline** cover both, and the one on **lifestyle** explains why he is at risk.',
    lessons: ['chd', 'hormones', 'lifestyle'],
    spec: { board: 'AQA', code: '8461', refs: ['4.2.2.4 coronary heart disease', '4.5.3.1 human endocrine system (adrenaline)', '4.2.2.6 lifestyle and non-communicable disease'] },
  });

  D.add({
    id: 'g05', track: 'gcse', rank: 2, minutes: 10,
    title: 'The lump', tagline: 'Slow, painless and smooth: worry versus the facts',
    complaint: 'A lump on his thigh that has been growing for over a year',
    patient: { name: 'Marcus Webb', age: 31, job: 'Painter and decorator', setting: 'GP surgery', image: P + 'g05.jpg',
      look: 'a thirty-one-year-old mixed-race man with short dark hair and a painter\'s paint-splattered work trousers, looking anxious, sitting on a surgery examination couch' },
    opening: 'Marcus says he has been putting this off for months because he is frightened of what he might hear.',
    referral: 'Marcus has noticed a **lump on his right thigh**. It has been there for **about 14 months** and has grown slowly. It does not hurt. He has read online that lumps mean cancer and he is terrified.',
    obs: [['Temperature', '36.6 °C'], ['Pulse', '72 per minute'], ['Weight', 'Stable'], ['The lump', '3 cm, smooth, firm, moves under the skin']],
    notes: ['Non-smoker. Drinks very little alcohol.', 'No family history of cancer.', 'No weight loss, night sweats or other symptoms.', 'The lump is not red, hot or tender.'],
    startFacts: ['smooth', 'stable'],
    facts: {
      smooth: 'The lump is smooth, firm and moves freely under the skin', stable: 'He has not lost weight and feels well',
      slow: 'It has grown very slowly over 14 months', nopain: 'It is painless and has not changed colour', nofam: 'No family history of cancer',
      nodes: 'No swollen lumps in the groin or elsewhere', contained: 'The scan shows the lump is contained within a membrane', biopsy: 'The cells are abnormal but contained, with none invading nearby tissue',
      nospread: 'There is no sign of any spread to other parts of the body', blood: 'Routine blood tests are normal',
    },
    questions: [
      { id: 'q1', q: 'How quickly has the lump grown?', a: 'Very slowly. It was the size of a marble a year ago. Now it is about the size of a golf ball.', fact: 'slow' },
      { id: 'q2', q: 'Is it painful or has it changed colour?', a: 'No, never. It is just there. The skin looks normal.', fact: 'nopain' },
      { id: 'q3', q: 'Does it move when you push it?', a: 'Yes, it slides about under the skin. It is not stuck down.', fact: 'smooth' },
      { id: 'q4', q: 'Have you lost weight or felt unwell?', a: 'No, I feel absolutely fine. I have not lost any weight.', fact: 'stable' },
      { id: 'q5', q: 'Does cancer run in your family?', a: 'Not that I know of. My grandparents lived to their eighties.', fact: 'nofam' },
      { id: 'q6', q: 'Have you noticed any other lumps, in your groin or elsewhere?', a: 'No, I have checked everywhere. Only this one.', fact: 'nodes' },
      { id: 'q7', q: 'Do you smoke or use sunbeds?', a: 'Never. I do not smoke and I hate the sun.', value: 'useful' },
      { id: 'q8', q: 'Did you have an injury to that leg?', a: 'I fell off a ladder two years ago and bruised it. That was a long time ago.', value: 'useful' },
      { id: 'q9', q: 'What colour paint do you use most?', a: 'Magnolia. Always magnolia.', value: 'waste' },
      { id: 'q10', q: 'Do you listen to music while you work?', a: 'Radio 2. Why?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Ultrasound scan of the lump', result: 'The lump is **contained within a membrane**, with clear edges. It does not extend into the surrounding tissue.', fact: 'contained', value: 'key' },
      { id: 't2', name: 'Biopsy (a small sample of the lump)', result: 'The cells are **abnormal but contained within the lump**. None are invading the neighbouring tissue.', fact: 'biopsy', value: 'key' },
      { id: 't3', name: 'Examine the groin and other lymph glands', result: 'No swollen lumps anywhere else.', fact: 'nodes', value: 'useful' },
      { id: 't4', name: 'Whole-body scan to look for spread', note: 'Uses radiation', result: 'No sign of any spread, but he was exposed to a lot of radiation for no real reason given the biopsy.', fact: 'nospread', value: 'risky' },
      { id: 't5', name: 'Routine blood tests', result: 'Normal.', fact: 'blood', value: 'waste' },
      { id: 't6', name: 'Skin allergy test', result: 'Not relevant to a lump under the skin.', value: 'waste' },
    ],
    options: [
      { id: 'benign', name: 'A benign tumour', sub: 'Abnormal cells contained in one area' },
      { id: 'malignant', name: 'A malignant tumour (cancer)', sub: 'Cells invade nearby tissue and spread' },
      { id: 'secondary', name: 'A secondary tumour', sub: 'Spread from cancer elsewhere in the body' },
    ],
    truth: 'benign', decisive: ['contained', 'biopsy', 'slow', 'smooth', 'nodes'],
    treatments: [
      { id: 'x1', label: 'Reassure him, and arrange to have the lump removed and checked', verdict: 'best', why: 'A **benign tumour** stays in one place and does not spread, so the outlook is very good. Removing it solves the problem and the removed lump can be checked to confirm the result.' },
      { id: 'x2', label: 'Start urgent chemotherapy', verdict: 'harm', why: 'Chemotherapy is for cancer. This tumour is benign, so powerful drugs would harm him for no benefit.' },
      { id: 'x3', label: 'Tell him it is nothing and not to come back', verdict: 'ok', why: 'He is right to be reassured, but any lump that is growing should be removed or monitored, not ignored.' },
      { id: 'x4', label: 'Prescribe an antibiotic course', verdict: 'wrong', why: 'There is no infection here: no redness, heat or fever. Antibiotics do nothing for a tumour.' },
    ],
    outcome: {
      right: 'Marcus had the lump removed under local anaesthetic. It was confirmed to be a benign tumour. He felt the weight lift from his shoulders and was back on ladders within a fortnight.',
      wrong: 'Marcus went through weeks of needless fear and treatment that did not suit him. The lump, which was benign all along, was eventually removed. The scan and biopsy had shown the answer.',
    },
    twist: 'The word "lump" frightens everyone, and the internet says cancer. But not every tumour is cancer: a **benign** one stays **contained**, while a **malignant** one **invades**. The scan and biopsy decided it. Read both parts of the **cancer** lesson.',
    lessons: ['cancer', 'lifestyle'],
    spec: { board: 'AQA', code: '8461', refs: ['4.2.2.7 cancer (benign and malignant tumours)', '4.2.2.6 lifestyle risk factors'] },
  });

  D.add({
    id: 'g06', track: 'gcse', rank: 2, minutes: 10,
    title: 'It will not respond', tagline: 'A hot, red wound and a fifth day of antibiotics',
    complaint: 'Knee wound red, hot and leaking pus after surgery',
    patient: { name: 'Priya Nair', age: 52, job: 'Teaching assistant', setting: 'Ward round, hospital', image: P + 'g06.jpg',
      look: 'a fifty-two-year-old British Indian woman in a hospital gown, looking tired and flushed, sitting up in a hospital bed with one leg raised on a pillow' },
    opening: 'Priya is tired and sore and a little tearful. She says she has done everything the nurses asked.',
    referral: 'Priya had a **knee replacement 10 days ago**. Her wound is now **red, hot and leaking pus** and she has a temperature. She has been on **penicillin for five days** and is **not improving**.',
    obs: [['Temperature', '38.7 °C'], ['Pulse', '102 per minute'], ['Wound', 'Red, hot, swollen, leaking pus'], ['Antibiotic so far', 'Penicillin (5 days)']],
    notes: ['She has completed every dose on time.', 'She is otherwise healthy.', 'Before the operation she had a swab test for MRSA: result not yet checked.', 'The ward has had other cases of wound infection this month.'],
    startFacts: ['pus', 'nopeni'],
    facts: {
      pus: 'The wound is red, hot and leaking pus with a fever', nopeni: 'Five days of penicillin have made no difference',
      dose: 'She took every dose on time', bacterial: 'The pus contains bacteria', mrsa: 'The bacteria grow even in the presence of penicillin: they are resistant (MRSA)',
      ward: 'There have been other wound infections on the ward this month', viral: 'The throat swab finds no virus and nothing else is wrong',
      blood: 'Her white blood cell count is high, as the body responds to an infection', normal: 'She had no signs of an infection before the operation',
    },
    questions: [
      { id: 'q1', q: 'Have you taken every dose of the antibiotic?', a: 'Every single one, at the right time. The nurses write it all down.', fact: 'dose' },
      { id: 'q2', q: 'When did the wound start to look worse?', a: 'About five days ago it started to get red. It has got worse each day.', fact: 'pus' },
      { id: 'q3', q: 'Has the penicillin made any difference?', a: 'None at all. If anything it is worse.', fact: 'nopeni' },
      { id: 'q4', q: 'Do you have a cough, sore throat or runny nose?', a: 'No, nothing like that. It is just the leg.', value: 'useful' },
      { id: 'q5', q: 'Have you noticed other patients with similar wounds?', a: 'The lady in the next bed had something similar last week. They moved her to a side room.', fact: 'ward' },
      { id: 'q6', q: 'Were you unwell before the operation?', a: 'No, I was perfectly well. That is why it is so frustrating.', fact: 'normal' },
      { id: 'q7', q: 'Do you have any allergies to antibiotics?', a: 'No, none known.', value: 'useful' },
      { id: 'q8', q: 'Are you worried about anything?', a: 'That the new knee will have to come out.', value: 'useful' },
      { id: 'q9', q: 'What do you teach at school?', a: 'I am a teaching assistant, mostly in Year 3.', value: 'waste' },
      { id: 'q10', q: 'What do you think of the hospital food?', a: 'Don\'t get me started...', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Swab the wound and test which antibiotics kill the bacteria', note: 'Grows the bacteria with different antibiotics', result: 'Bacteria **grow despite penicillin**, and are only killed by a different antibiotic. This is a **resistant strain (MRSA)**.', fact: 'mrsa', value: 'key' },
      { id: 't2', name: 'Look at the pus under the microscope', result: 'The pus is full of **bacteria**.', fact: 'bacterial', value: 'key' },
      { id: 't3', name: 'Blood test for white blood cells', result: 'White blood cell count is high: the body is fighting an infection.', fact: 'blood', value: 'useful' },
      { id: 't4', name: 'Throat swab for virus testing', result: 'No virus found.', fact: 'viral', value: 'waste' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. She has no chest symptoms.', value: 'risky' },
      { id: 't6', name: 'Skin prick allergy test', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'mrsa', name: 'An infection with antibiotic-resistant bacteria (MRSA)', sub: 'Bacteria that penicillin cannot kill' },
      { id: 'viral', name: 'A viral infection', sub: 'Antibiotics have no effect on a virus' },
      { id: 'normal', name: 'Normal healing after surgery', sub: 'Redness and soreness that will pass' },
    ],
    truth: 'mrsa', decisive: ['mrsa', 'bacterial', 'nopeni', 'dose', 'ward'],
    treatments: [
      { id: 'x1', label: 'Move her to a side room, strict hygiene, and change to the antibiotic the swab shows will work', verdict: 'best', why: 'The test shows which antibiotic kills this strain, and **specific bacteria need specific antibiotics**. Isolation and hygiene stop the resistant strain spreading to other patients.' },
      { id: 'x2', label: 'Double the dose of penicillin', verdict: 'wrong', why: 'The bacteria are **resistant** to penicillin. A bigger dose does not kill resistant bacteria and helps more resistance develop.' },
      { id: 'x3', label: 'Stop all antibiotics and wait to see if the wound heals', verdict: 'harm', why: 'She has a bacterial infection in a new joint. Stopping treatment would let it spread.' },
      { id: 'x4', label: 'Change the antibiotic as the swab shows, but leave her on the open ward', verdict: 'ok', why: 'Right drug, but without isolation the resistant strain could spread to other patients on the ward.' },
    ],
    outcome: {
      right: 'Priya was moved to a side room and given the antibiotic that the swab showed would work. The infection cleared over a fortnight and her new knee was saved. The ward tightened its hand-washing rules.',
      wrong: 'The infection spread and Priya needed another operation. The resistant bacteria also reached another patient on the ward. The swab result, which showed resistance, had been the key.',
    },
    twist: 'A red, sore wound could be normal healing, and a hospital patient with a fever could have a virus. But five full days of the right-seeming antibiotic did nothing, because the bacteria were **resistant**. The lessons on **antibiotics** and **resistant bacteria** explain how a drug can stop working.',
    lessons: ['resistance', 'antibiotics', 'pathogens'],
    spec: { board: 'AQA', code: '8461', refs: ['4.6.3.7 resistant bacteria', '4.3.1.8 antibiotics and painkillers', '4.3.1.1 communicable diseases'] },
  });

  D.add({
    id: 'g07', track: 'gcse', rank: 2, minutes: 10,
    title: 'Collapse at the finish line', tagline: 'Everyone says drink more. Is that right this time?',
    complaint: 'Confused and sick after finishing a marathon',
    patient: { name: 'Hannah Brooks', age: 38, job: 'Primary school teacher', setting: 'Marathon first-aid tent', image: P + 'g07.jpg',
      look: 'a thirty-eight-year-old white woman in running kit with a race number pinned to her top, pale and confused, wrapped in a foil blanket, sitting on a folding chair in a first-aid tent' },
    opening: 'Hannah looks vaguely around the tent. Her husband is holding a large empty water bottle.',
    referral: 'Hannah finished her first marathon in 5 hours 40 minutes, then **vomited, developed a headache and became confused**. Her husband says she **drank water at every drinks station**, about four litres, because she was told to stay hydrated.',
    obs: [['Temperature', '36.9 °C'], ['Pulse', '98 per minute'], ['Weight', '3 kg heavier than before the race'], ['Alertness', 'Confused and drowsy']],
    notes: ['She sweated heavily but drank water very frequently.', 'She did not eat salty snacks or use sports drinks.', 'She noticed her rings felt tight.', 'The race was cool and cloudy.'],
    startFacts: ['conf', 'weight'],
    facts: {
      conf: 'She is confused and has a headache and nausea', weight: 'She is 3 kg heavier than before the race', water: 'She drank about four litres of plain water during the race',
      nosalt: 'She ate and drank nothing containing salt', cool: 'The weather was cool and she was not overheating', rings: 'Her fingers are swollen and her rings feel tight',
      dilute: 'Her blood sample is too dilute: the salt concentration is low', urine: 'Her urine is pale and plentiful', hot: 'Her temperature is normal at 36.9 °C',
      conc: 'Her blood is not concentrated (a dehydrated person would show concentrated blood)',
    },
    questions: [
      { id: 'q1', q: 'How much did you drink during the race?', a: 'At every station, a full cup. I was told to drink before I felt thirsty. I think about **four litres**, maybe more.', fact: 'water' },
      { id: 'q2', q: 'Did you have anything salty to eat or drink?', a: 'No, just plain water. I did not want to feel sick.', fact: 'nosalt' },
      { id: 'q3', q: 'Was it hot? Did you feel overheated?', a: 'No, it was cool and cloudy. I was sweaty but not boiling.', fact: 'cool' },
      { id: 'q4', q: 'Have you gained weight?', a: 'I weighed myself at the hotel: 3 kg more than this morning. I assumed it was a mistake.', fact: 'weight' },
      { id: 'q5', q: 'Do your hands feel swollen?', a: 'Yes, my rings feel tight, which is odd after a run.', fact: 'rings' },
      { id: 'q6', q: 'Are you passing urine?', a: 'Yes, lots, and it is clear.', fact: 'urine' },
      { id: 'q7', q: 'When did the headache and confusion start?', a: 'About 20 minutes after I stopped. It came on quickly.', value: 'useful' },
      { id: 'q8', q: 'Have you trained for this?', a: 'Four months of training. I did a 20-mile run a month ago.', value: 'useful' },
      { id: 'q9', q: 'What do you do on Fridays at school?', a: 'Assembly, then art.', value: 'waste' },
      { id: 'q10', q: 'What is your running playlist?', a: 'Mostly Taylor Swift.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Blood test for how concentrated the blood is (salt level)', result: 'The blood is **too dilute**: the salt concentration is very low.', fact: 'dilute', value: 'key' },
      { id: 't2', name: 'Check her temperature', result: 'Normal at 36.9 °C.', fact: 'hot', value: 'useful' },
      { id: 't3', name: 'Examine her urine', result: 'Pale and plentiful: her kidneys are removing a lot of water.', value: 'useful' },
      { id: 't4', name: 'Weigh her again', result: 'She is 3 kg heavier than at registration.', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. She has no chest symptoms.', value: 'risky' },
      { id: 't6', name: 'Throat swab', result: 'Not relevant.', value: 'waste' },
    ],
    options: [
      { id: 'dilute', name: 'Too much water: her blood is too dilute', sub: 'Cells are taking in water by osmosis' },
      { id: 'dehydration', name: 'Dehydration: she has lost too much water', sub: 'Blood is too concentrated' },
      { id: 'heat', name: 'Overheating', sub: 'Body temperature too high' },
    ],
    truth: 'dilute', decisive: ['dilute', 'weight', 'water', 'nosalt', 'rings', 'cool'],
    treatments: [
      { id: 'x1', label: 'Stop her drinking, and arrange urgent hospital care to correct the salt level carefully', verdict: 'best', why: 'Her blood is **too dilute**, so water is moving into her cells by **osmosis**, and brain cells swelling cause the confusion. She needs salt balance restored under medical care, not more water.' },
      { id: 'x2', label: 'Give her as much water as she can drink', verdict: 'harm', why: 'That would make the blood even more dilute and her brain cells swell further. This is the opposite of what she needs.' },
      { id: 'x3', label: 'Cool her with ice packs and fans', verdict: 'wrong', why: 'Her temperature is normal, so she is not overheating. Cooling does nothing for a water-balance problem.' },
      { id: 'x4', label: 'Let her rest in the tent and see how she feels in an hour', verdict: 'ok', why: 'Resting is harmless, but her confusion means she needs urgent medical attention.' },
    ],
    outcome: {
      right: 'Hannah was taken to hospital and her salt balance corrected slowly over the night. By morning she was clear-headed. She now uses a sports drink and drinks to thirst rather than by the clock.',
      wrong: 'Hannah was given more water and grew worse, with a seizure on the way to hospital. She recovered, but her confusion had been the sign of dangerously dilute blood, not dehydration.',
    },
    twist: 'A collapsed runner who is confused and sick sounds **dehydrated**, and everyone will tell you to give her water. But her weight is **up**, her blood is **too dilute** and her urine is plentiful: she has had **too much water**. The lesson on **water balance** covers both.',
    lessons: ['waterbalance', 'hormones'],
    spec: { board: 'AQA', code: '8461', refs: ['4.5.3.3 maintaining water and nitrogen balance (biology only)', '4.1.3.2 osmosis', '4.5.1 homeostasis'] },
  });
})(typeof window !== 'undefined' ? window : globalThis);
