/*
 * Doctor Career: A-level cases (AQA 7402). The reasoning each case asks for is the specification's. Where the specification does not name a
 * condition, the case file gives the information and the lessons teach the mechanism (A-level questions work this way).
 */
(function (root) {
  var D = root.DOCTOR = root.DOCTOR || {}; D.cases = D.cases || [];
  var P = '/assets/doctor/';

  D.add({
    id: 'a01', track: 'alevel', rank: 0, minutes: 10,
    title: 'Thirsty at forty-four', tagline: 'Overweight, a family history, and a blood glucose of 26',
    complaint: 'Constant thirst, tiredness and weight loss over two months',
    patient: { name: 'Callum Reid', age: 44, job: 'Delivery driver', setting: 'Medical admissions unit', image: P + 'a01.jpg',
      look: 'a forty-four-year-old white man of heavy build with a stubbled face, tired and pale, in a hospital gown, sitting up on a hospital trolley and holding a plastic cup of water' },
    opening: 'Callum has drunk two cups of water since he arrived and asks for a third.',
    referral: 'Sent in by his GP. Callum has had **two months of intense thirst, passing urine very often, tiredness and weight loss of 9 kg** without dieting. A finger-prick glucose in the surgery read **26 mmol per litre**. His GP suspects Type II diabetes: he is overweight and his father had it.',
    obs: [['Temperature', '36.9 °C'], ['Pulse', '98 per minute'], ['BMI', '30'], ['Urine dipstick', 'Glucose present']],
    notes: ['Overweight for many years, and weight has been **falling** over the last two months.', 'Father had Type II diabetes, diagnosed at 58.', 'Eats a lot of takeaway food; drives for a living and takes little exercise.', 'No medicines. No previous medical problems.'],
    startFacts: ['bg', 'urine'],
    facts: {
      bg: 'Blood glucose is 26 mmol per litre', urine: 'There is glucose in his urine', loss: 'He has lost 9 kg in two months without trying', quick: 'The symptoms began quickly, within about two months',
      fam: 'His father has Type II diabetes', obese: 'He is overweight and has been for years', eats: 'He is eating more than ever but still losing weight',
      curve: 'After a glucose drink his insulin barely rises while his glucose stays very high', ab: 'His blood contains antibodies against his own insulin-producing beta cells',
      thirst: 'He drinks several litres a day and passes urine very often', age: 'He is 44, but the illness started suddenly rather than slowly',
    },
    questions: [
      { id: 'q1', q: 'How quickly did the symptoms come on?', a: 'Over about **two months**. I was fine at Christmas. By March I could not stop drinking.', fact: 'quick' },
      { id: 'q2', q: 'Has your weight changed?', a: 'I have **lost nine kilos** without trying. I thought it was good news until the thirst started.', fact: 'loss' },
      { id: 'q3', q: 'How much are you drinking and passing?', a: 'Four or five litres a day. I am up four times a night.', fact: 'thirst' },
      { id: 'q4', q: 'Is your appetite normal?', a: 'I am starving all the time. I eat everything and still lose weight.', fact: 'eats' },
      { id: 'q5', q: 'Is there diabetes in your family?', a: 'My dad had the Type II. He was big, like me. It runs in the men on that side.', fact: 'fam' },
      { id: 'q6', q: 'Has your weight been a lifelong issue?', a: 'Yes, since my twenties. I have been fourteen stone plus for twenty years.', fact: 'obese' },
      { id: 'q7', q: 'Have you had any recent infections or other autoimmune illnesses?', a: 'A bad cold in January, then nothing. My mother has an underactive thyroid.', value: 'useful' },
      { id: 'q8', q: 'How is your diet?', a: 'Takeaways three or four times a week, sugary drinks on the van, no real exercise.', value: 'useful' },
      { id: 'q9', q: 'What do you deliver?', a: 'Parcels. Mostly for online shops.', value: 'waste' },
      { id: 'q10', q: 'What is your favourite motorway services?', a: 'Tebay. Best pies in the country.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Glucose drink test with blood insulin measured', note: 'He drinks a measured glucose drink; blood is sampled over two hours', fact: 'curve', value: 'key',
        result: 'In a person without diabetes, glucose would peak at about 7 to 8 and fall back, and insulin would rise sharply soon after the drink.',
        table: [['Time (minutes)', '0', '30', '60', '120'], ['Blood glucose (mmol per litre)', '24', '29', '31', '30'], ['Blood insulin (units)', '2', '3', '3', '3']] },
      { id: 't2', name: 'Blood test for antibodies against the beta cells of the pancreas', result: 'Antibodies against his own **insulin-producing beta cells** are present: the immune system is attacking them.', fact: 'ab', value: 'key' },
      { id: 't3', name: 'Weigh him and review his weight chart', result: 'Weight is **down 9 kg** over two months.', fact: 'loss', value: 'useful' },
      { id: 't4', name: 'Fasting cholesterol', result: 'Mildly raised. It does not help decide the type of diabetes.', value: 'waste' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. No reason for it.', value: 'risky' },
      { id: 't6', name: 'Throat swab', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'type1', name: 'Type I diabetes', sub: 'Beta cells fail to make enough insulin' },
      { id: 'type2', name: 'Type II diabetes', sub: 'Target cells are less responsive to insulin' },
      { id: 'osmo', name: 'A fault in the control of blood water potential', sub: 'Too little ADH' },
    ],
    truth: 'type1', decisive: ['curve', 'ab', 'quick', 'loss', 'eats'],
    treatments: [
      { id: 'x1', label: 'Start insulin injections, with advice on diet and exercise', verdict: 'best', why: 'In **Type I** there is no insulin to attach to receptors, increase glucose uptake or activate the enzymes that make glycogen, so insulin must be given. Diet and exercise still help keep glucose steady.' },
      { id: 'x2', label: 'Manipulate his diet and increase exercise only; review in three months', verdict: 'harm', why: 'That is the Type II plan. With little insulin, his glucose will stay dangerously high for months.' },
      { id: 'x3', label: 'Start a drug to make his cells more sensitive to insulin', verdict: 'wrong', why: 'His cells are not the problem: there is almost no insulin for them to respond to.' },
      { id: 'x4', label: 'Insulin only, with no further advice', verdict: 'ok', why: 'The insulin is essential, but diet and exercise are still part of controlling blood glucose.' },
    ],
    outcome: {
      right: 'Callum started insulin that day and learned to adjust his doses to his meals. Within weeks his thirst had gone, his weight had steadied and he was back on the road. His GP recorded Type I and offered the same screening to his children.',
      wrong: 'Callum was sent home on a diet plan and returned within two weeks, very unwell, with blood glucose above 40. He recovered in hospital, but the delay was avoidable: his insulin response and antibody result had shown it was Type I.',
    },
    twist: 'Age 44, overweight, a father with Type II: every first impression says **Type II**. But the illness came on **fast**, he is **losing weight**, his **insulin barely rises** and the **antibody test** shows an attack on the beta cells. That is **Type I**. Read the glucose lesson with this in mind.',
    lessons: ['a-glucose', 'a-kidney', 'a-immune'],
    spec: { board: 'AQA', code: '7402', refs: ['3.6.4.2 control of blood glucose concentration', '3.6.4.3 control of blood water potential', '3.2.4 cell recognition and the immune system'] },
  });

  D.add({
    id: 'a02', track: 'alevel', rank: 0, minutes: 10,
    title: 'A sore throat that is not', tagline: 'Fever, swollen glands and a negative test',
    complaint: 'Sore throat, fever and a rash for ten days',
    patient: { name: 'Sam Okafor', age: 27, job: 'Bar manager', setting: 'Sexual health clinic', image: P + 'a02.jpg',
      look: 'a twenty-seven-year-old Black British man in a casual hooded top, looking tired and unwell, sitting nervously in a clinic consulting room' },
    opening: 'Sam looks uncomfortable. He says his GP gave him antibiotics and nothing changed.',
    referral: 'Sam has had a **sore throat, fever, swollen neck glands and a faint rash for ten days**. His GP treated it as **bacterial tonsillitis** with a course of **antibiotics** but it has not improved. A **rapid HIV test done yesterday was negative**, so the GP has referred him to find out why he is still ill.',
    obs: [['Temperature', '38.4 °C'], ['Pulse', '96 per minute'], ['Throat', 'Red, no pus'], ['Skin', 'Faint rash on his chest']],
    notes: ['Completed a full course of an antibiotic for tonsillitis: no improvement.', 'Night sweats and tiredness over the last week.', 'Neck glands swollen on both sides.', 'No cough, no runny nose.'],
    startFacts: ['abx', 'neg'],
    facts: {
      abx: 'A full course of antibiotics made no difference', neg: 'A rapid HIV antibody test yesterday was negative', sweats: 'He has had night sweats and tiredness',
      exposure: 'He had unprotected sex with a new partner about three weeks ago', swab: 'A throat swab grows no bacteria', antigen: 'A test that detects an HIV antigen as well as antibodies is positive',
      repeat: 'A repeat antibody test in three months is expected to turn positive', rash: 'There is a faint rash on his chest with a fever and swollen glands',
      nopus: 'The throat is red but has no pus, and nobody else at home is ill', tcells: 'His helper T cell count has started to fall',
    },
    questions: [
      { id: 'q1', q: 'Did the antibiotics help at all?', a: 'Not at all. Ten days of tablets and I am worse, not better.', fact: 'abx' },
      { id: 'q2', q: 'Have you had night sweats or tiredness?', a: 'Yes, drenching sweats for a week and I am shattered.', fact: 'sweats' },
      { id: 'q3', q: 'Have you had any recent unprotected sex?', a: 'About **three weeks ago**, with someone new. We did not use a condom. It was one time.', fact: 'exposure' },
      { id: 'q4', q: 'Have you noticed a rash?', a: 'A faint pink rash on my chest in the last few days.', fact: 'rash' },
      { id: 'q5', q: 'Is anyone at home or work ill with the same thing?', a: 'No, nobody. I live with my brother and he is fine.', fact: 'nopus' },
      { id: 'q6', q: 'Do you have a cough or a runny nose?', a: 'No, just the throat and the fever.', value: 'useful' },
      { id: 'q7', q: 'Have you injected drugs or had a blood transfusion?', a: 'No, never.', value: 'useful' },
      { id: 'q8', q: 'Did you travel abroad recently?', a: 'No, not for two years.', value: 'useful' },
      { id: 'q9', q: 'How many shifts a week do you work?', a: 'Six. It is a busy bar.', value: 'waste' },
      { id: 'q10', q: 'What is your favourite cocktail?', a: 'An old fashioned, if you must know.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Throat swab, cultured for bacteria', result: 'No bacteria grow: a bacterial throat infection is **unlikely**.', fact: 'swab', value: 'key' },
      { id: 't2', name: 'A test that detects HIV antigen as well as antibodies (a type of ELISA)', note: 'Can detect infection earlier than an antibody test', result: 'Positive: an **HIV antigen** is present in his blood.', fact: 'antigen', value: 'key' },
      { id: 't3', name: 'Repeat the HIV antibody test straight away', note: 'He was tested yesterday', result: 'Negative again. His body has probably not yet made enough antibodies to detect.', value: 'useful' },
      { id: 't4', name: 'Count his helper T cells', result: 'His **helper T cell count** has begun to fall.', fact: 'tcells', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. No reason for it.', value: 'risky' },
      { id: 't6', name: 'Allergy skin test', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'hiv', name: 'Early HIV infection', sub: 'A viral infection of helper T cells' },
      { id: 'bacterial', name: 'Bacterial tonsillitis', sub: 'An infection that antibiotics should clear' },
      { id: 'viral', name: 'A common viral infection such as flu', sub: 'Will pass without treatment' },
    ],
    truth: 'hiv', decisive: ['antigen', 'swab', 'abx', 'exposure', 'sweats', 'tcells'],
    treatments: [
      { id: 'x1', label: 'Stop the antibiotics, refer urgently to an HIV specialist for treatment, and give counselling and advice on preventing spread', verdict: 'best', why: 'Antibiotics are **ineffective against viruses**. HIV replicates in helper T cells and early treatment protects them. Counselling and protection reduce the risk of passing it on.' },
      { id: 'x2', label: 'Prescribe a stronger antibiotic', verdict: 'wrong', why: 'There is no bacterial infection (the swab was negative), and **antibiotics have no effect on a virus**.' },
      { id: 'x3', label: 'Tell him the negative HIV test means he is clear and send him home', verdict: 'harm', why: 'An **antibody** test can be negative in early infection, because antibodies have not yet been made. The antigen test is positive, so this reassurance would be wrong and dangerous.' },
      { id: 'x4', label: 'Treat the symptoms and repeat the antibody test in three months', verdict: 'ok', why: 'Waiting would eventually confirm the result, but delaying treatment and advice leaves his helper T cells exposed and risks spreading the virus.' },
    ],
    outcome: {
      right: 'Sam was seen by an HIV specialist that week and started treatment early. His helper T cell count recovered, and his partner was contacted and tested. He now lives with HIV as a long-term, well-controlled condition.',
      wrong: 'Sam took another course of antibiotics, reassured by the negative test. Months later his helper T cell count had fallen sharply and he developed repeated infections. Testing for the antigen as well as antibodies would have shown it at the start.',
    },
    twist: 'Sore throat, fever and swollen glands sound like **tonsillitis**, and the HIV test came back **negative**. But the antibiotics did nothing (it is not bacterial), and an **antibody** test can be **negative early on** because the immune system has not had time to make antibodies. A test for the **antigen** shows the truth. Read the **HIV** and **immune response** lessons.',
    lessons: ['a-hiv', 'a-immune'],
    spec: { board: 'AQA', code: '7402', refs: ['3.2.4 HIV and AIDS, ELISA, antibiotics and viruses', '3.2.4 primary and secondary immune response'] },
  });

  D.add({
    id: 'a03', track: 'alevel', rank: 1, minutes: 10,
    title: 'The lump that hurt', tagline: 'Sore and red: infection, or something worse?',
    complaint: 'A painful, red lump in the breast for three weeks',
    patient: { name: 'Maggie Doyle', age: 53, job: 'Retired librarian', setting: 'Breast clinic', image: P + 'a03.jpg',
      look: 'a fifty-three-year-old white woman with short grey hair and glasses, wearing a cardigan, sitting upright and anxious in a clinic consulting room' },
    opening: 'Maggie says her GP thought it was a breast infection, but the antibiotics did not shift it.',
    referral: 'Maggie has a **firm lump in her left breast**, with the skin over it **red and sore**. Her GP prescribed an **antibiotic for a suspected infection** but after **two weeks** the lump has **not shrunk** and has got **harder**. Referred urgently.',
    obs: [['Temperature', '36.8 °C'], ['Pulse', '76 per minute'], ['The lump', '3.5 cm, hard, irregular, fixed to the skin'], ['Glands', 'One hard node in the armpit']],
    notes: ['Completed a course of antibiotics: no improvement.', 'Post-menopausal. Took hormone replacement therapy (oestrogen) for 12 years.', 'Her mother was treated for breast cancer at 58.', 'Not feverish. Not breastfeeding.'],
    startFacts: ['abx', 'hard'],
    facts: {
      abx: 'Two weeks of antibiotics made no difference', hard: 'The lump is hard, irregular and fixed to the skin', nofever: 'She has no fever and the lump is not warm like an abscess',
      hrt: 'She took oestrogen as hormone replacement for 12 years', mum: 'Her mother had breast cancer', node: 'There is a hard lump in her armpit', grow: 'The lump has grown and hardened over three weeks',
      fast: 'The biopsy shows cells dividing very rapidly with many dividing nuclei', invade: 'The biopsy cells invade the surrounding tissue with no clear boundary', receptor: 'The tumour cells have receptors for oestrogen and are stimulated by it',
      cystic: 'Fluid drawn off with a needle is not infected and the lump remains',
    },
    questions: [
      { id: 'q1', q: 'How has the lump changed over time?', a: 'It was small and sore at first. Over three weeks it has grown and gone **harder**.', fact: 'grow' },
      { id: 'q2', q: 'Did the antibiotics help?', a: 'Not even slightly. Two weeks of them.', fact: 'abx' },
      { id: 'q3', q: 'Have you had fevers or felt unwell?', a: 'No fever. I feel perfectly well in myself.', fact: 'nofever' },
      { id: 'q4', q: 'Have you ever taken hormone replacement?', a: 'Yes, for twelve years. Oestrogen tablets, after the menopause.', fact: 'hrt' },
      { id: 'q5', q: 'Does breast cancer run in your family?', a: 'My mother had it at 58.', fact: 'mum' },
      { id: 'q6', q: 'Have you noticed lumps anywhere else?', a: 'One under my left arm. I thought it was just swollen from the infection.', fact: 'node' },
      { id: 'q7', q: 'Are you breastfeeding or have you recently?', a: 'No. My youngest is thirty.', value: 'useful' },
      { id: 'q8', q: 'Have you lost weight?', a: 'A little, but I put it down to worry.', value: 'useful' },
      { id: 'q9', q: 'What was your favourite book to recommend?', a: 'Persuasion. Always Persuasion.', value: 'waste' },
      { id: 'q10', q: 'How long were you a librarian?', a: 'Thirty-four years.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Biopsy: look at the dividing cells', result: 'The sample shows cells **dividing very rapidly**, many in mitosis, with large dark nuclei, and **invading the surrounding tissue** with no clear boundary.', fact: 'fast', value: 'key' },
      { id: 't2', name: 'Test the tumour cells for oestrogen receptors', note: 'On the biopsy sample', result: 'The cells **have receptors for oestrogen** and are stimulated to divide by it.', fact: 'receptor', value: 'key' },
      { id: 't3', name: 'Examine the armpit node', result: 'A **hard lump in the armpit**: cells may have spread.', fact: 'node', value: 'useful' },
      { id: 't4', name: 'Needle draw-off of fluid', result: 'No fluid or infection: **not an abscess**, and the lump remains.', fact: 'cystic', value: 'useful' },
      { id: 't5', name: 'Throat swab', result: 'Irrelevant.', value: 'waste' },
      { id: 't6', name: 'Skin allergy test', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'malignant', name: 'A malignant tumour', sub: 'Uncontrolled division, invading tissue' },
      { id: 'benign', name: 'A benign tumour', sub: 'Slow-growing with a clear boundary' },
      { id: 'infection', name: 'A bacterial infection', sub: 'Antibiotics should clear it' },
    ],
    truth: 'malignant', decisive: ['fast', 'receptor', 'abx', 'nofever', 'node', 'grow'],
    treatments: [
      { id: 'x1', label: 'Remove the tumour surgically, and follow with treatment that targets cell division and blocks oestrogen\'s action', verdict: 'best', why: 'Surgery removes the tumour. Many cancer treatments target the **rate of cell division**, and because the cells respond to **oestrogen**, blocking oestrogen can slow their growth.' },
      { id: 'x2', label: 'Wait six months and re-examine the lump', verdict: 'harm', why: 'A malignant tumour invades and spreads. Waiting risks secondary tumours.' },
      { id: 'x3', label: 'Try a different antibiotic', verdict: 'wrong', why: 'There is no infection. The antibiotic failed because the problem is **not bacterial**.' },
      { id: 'x4', label: 'Remove the lump but give no follow-up treatment', verdict: 'ok', why: 'Removing it is essential, but cells may already have spread, so treatment to control division is important.' },
    ],
    outcome: {
      right: 'Maggie had surgery within two weeks, then treatment that blocked oestrogen. Scans a year later showed no sign of the cancer returning. She asked for her daughters to be told about their family risk.',
      wrong: 'The lump kept growing and by the time it was investigated a second time, cancer cells had reached more lymph nodes. Maggie still had surgery, but needed far more treatment than she would have done.',
    },
    twist: 'A red, sore lump sounds like an **infection**, and the antibiotic seems the obvious answer. But the antibiotics **did nothing**, there is **no fever**, and the biopsy shows **rapid division and invasion**. That is a **malignant tumour**, and the **oestrogen** history explains why. Read the lesson on **tumours**.',
    lessons: ['a-tumours', 'a-mutation'],
    spec: { board: 'AQA', code: '7402', refs: ['3.2.2 uncontrolled cell division and cancer treatments', '3.8.2.3 benign and malignant tumours, oncogenes, oestrogen and breast cancer', '3.2.4 why antibiotics are ineffective against non-bacterial disease'] },
  });

  D.add({
    id: 'a04', track: 'alevel', rank: 1, minutes: 10,
    title: 'Short of breath', tagline: 'A smoker, a stonemason, and small breaths',
    complaint: 'Increasing breathlessness over two years',
    patient: { name: 'Frank Dobson', age: 64, job: 'Retired stonemason', setting: 'Respiratory clinic', image: P + 'a04.jpg',
      look: 'a sixty-four-year-old white man with a weathered face and white hair, wearing a flat cap and an old cardigan, breathing with visible effort, sitting in a respiratory clinic' },
    opening: 'Frank takes a breath between sentences. He says the stairs have become a mountain.',
    referral: 'Frank is **increasingly breathless over two years**, now even on gentle walks, with a **dry cough**. He worked as a **stonemason for 35 years**, mostly without a mask, and **smoked 15 a day for 12 years** before giving up 25 years ago. His GP suspects **smoking-related damage**.',
    obs: [['Breathing rate', '26 per minute at rest'], ['Pulse', '90 per minute'], ['Oxygen in blood', '88% (low)'], ['Tidal volume', '320 cm³ (normal about 500)']],
    notes: ['Ex-smoker: 12 years at 15 a day, stopped 25 years ago.', '35 years cutting and shaping stone, working in dust.', 'Dry cough, no phlegm. No wheeze.', 'Breathes quickly and shallowly.'],
    infoCard: { title: 'How lung disease can change breathing', body: [
      '**Alveolar walls damaged and broken down**: fewer, larger air spaces, so **less surface area** for gas exchange. The lungs are floppy. Breathing rate may rise, but each breath is **not small**.',
      '**Alveolar walls thickened and scarred**: oxygen has a **longer way to diffuse**, and the lung becomes **stiff**, so each breath is **small** and the person **breathes faster**.',
      '**Airways narrowed**: **less air gets in and out** (reduced ventilation), often with a **wheeze**, and breathing out is slow.',
    ] },
    startFacts: ['tv', 'dust'],
    facts: {
      tv: 'His tidal volume is small (320 cm³) and his breathing rate is fast (26 per minute)', dust: 'He worked in stone dust for 35 years',
      smoker: 'He smoked 12 years but stopped 25 years ago', nowheeze: 'He has no wheeze and breathes out at a normal speed', lowo2: 'His blood oxygen is low (88%), worse on exercise',
      scar: 'The scan shows scarring that has thickened the walls of the alveoli', pvr: 'His pulmonary ventilation rate is about 8300 cm³ per minute, higher than normal because he breathes so fast',
      emph: 'The scan does not show fewer, larger air spaces', stiff: 'The lungs are stiff and do not inflate easily', heart: 'His heart is normal',
    },
    questions: [
      { id: 'q1', q: 'Describe how your breathing feels.', a: 'I cannot take a **deep breath**. It is as if my chest is held in a corset. I breathe quickly and shallowly.', fact: 'stiff' },
      { id: 'q2', q: 'Do you wheeze, or find it hard to breathe out?', a: 'No wheeze. Breathing out is easy enough. It is the breathing **in** that stops short.', fact: 'nowheeze' },
      { id: 'q3', q: 'Tell me about your work.', a: 'Thirty-five years a stonemason. Cutting sandstone, no mask for the first twenty years. The dust hung in the air like fog.', fact: 'dust' },
      { id: 'q4', q: 'Do you smoke now, or did you?', a: 'Fifteen a day for twelve years, then I stopped. That was twenty-five years ago.', fact: 'smoker' },
      { id: 'q5', q: 'Does it get worse when you exercise?', a: 'Yes, I go blue about the lips on the stairs.', fact: 'lowo2' },
      { id: 'q6', q: 'Any chest pain, ankle swelling, palpitations?', a: 'No. My heart is fine, they say.', fact: 'heart' },
      { id: 'q7', q: 'Do you cough up phlegm?', a: 'No, it is a dry irritating cough.', value: 'useful' },
      { id: 'q8', q: 'Does anyone in your family have lung disease?', a: 'No, only my uncle, who was a miner.', value: 'useful' },
      { id: 'q9', q: 'What was the hardest stone to carve?', a: 'Granite, without a doubt.', value: 'waste' },
      { id: 'q10', q: 'Which cathedral did you work on?', a: 'Wells, for a year.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Measure tidal volume, breathing rate and ventilation rate', note: 'Pulmonary ventilation rate = tidal volume x breathing rate', fact: 'pvr', value: 'key',
        result: 'His tidal volume is small and his breathing rate is high. The numbers are below.',
        table: [['Measure', 'Frank', 'Typical healthy adult'], ['Tidal volume (cm³)', '320', '500'], ['Breathing rate (per minute)', '26', '12'], ['Pulmonary ventilation rate (cm³ per minute)', '8320', '6000']] },
      { id: 't2', name: 'CT scan of the lungs', note: 'Uses radiation but is justified here', result: 'Scarring has **thickened the walls of the alveoli** throughout both lungs. There is **no sign of the large air spaces** that would show broken-down alveoli.', fact: 'scar', value: 'key' },
      { id: 't3', name: 'Blood oxygen on exercise', result: 'His blood oxygen **drops sharply on exercise**, from 88% to 79%.', fact: 'lowo2', value: 'useful' },
      { id: 't4', name: 'Test the speed of breathing out', result: 'He breathes out at a **normal speed**: no sign that the airways are narrowed.', fact: 'nowheeze', value: 'useful' },
      { id: 't5', name: 'Heart examination', result: 'Normal. His heart is not the cause.', fact: 'heart', value: 'useful' },
      { id: 't6', name: 'Throat swab', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'thick', name: 'Thickened, scarred alveolar walls', sub: 'Longer diffusion distance, stiff lungs, small breaths' },
      { id: 'broken', name: 'Broken-down alveolar walls', sub: 'Reduced surface area for gas exchange' },
      { id: 'airway', name: 'Narrowed airways', sub: 'Reduced ventilation, difficulty breathing out' },
    ],
    truth: 'thick', decisive: ['tv', 'scar', 'stiff', 'nowheeze', 'pvr', 'lowo2'],
    treatments: [
      { id: 'x1', label: 'Avoid further dust exposure, give oxygen when needed, and review his lung function regularly', verdict: 'best', why: 'The damage is thickened alveolar walls from dust, so further exposure must stop. Extra oxygen raises the concentration gradient and helps with the longer diffusion distance.' },
      { id: 'x2', label: 'A reliever inhaler to widen his airways', verdict: 'wrong', why: 'His airways are not narrowed: he breathes out at normal speed. Widening them will not fix thickened alveolar walls.' },
      { id: 'x3', label: 'A course of antibiotics', verdict: 'wrong', why: 'There is no bacterial infection. His breathlessness has built up over two years.' },
      { id: 'x4', label: 'Tell him he is just out of shape and to get back to work', verdict: 'harm', why: 'Continuing dust exposure would worsen the scarring. This is a lung disease, not poor fitness.' },
    ],
    outcome: {
      right: 'Frank gave up his part-time stone carving, was given oxygen for use when he exerted himself, and has been stable for two years with regular monitoring. His breathing is still limited but no longer getting worse.',
      wrong: 'Frank carried on with his weekend stone carving and treatment for the wrong problem. His breathing worsened, and when the scan was finally done the scarring was more extensive than it needed to be.',
    },
    twist: 'Smoking history and breathlessness suggest **smoking-related damage with broken-down alveoli**. But the data show **small, fast breaths**, **normal breathing out** and **scarred, thickened walls**, which point to **stone dust**. Lung disease is solved by asking: **surface area, diffusion distance or ventilation?** Read the **gas exchange** lesson.',
    lessons: ['a-gas'],
    spec: { board: 'AQA', code: '7402', refs: ['3.3.2 gas exchange: alveolar epithelium, ventilation, pulmonary ventilation rate', '3.3.2 interpret information on the effects of lung disease; risk factors and incidence'] },
  });

  D.add({
    id: 'a05', track: 'alevel', rank: 2, minutes: 10,
    title: 'Drinking all day, passing it all night', tagline: 'Is it sugar, is it sweat, or is it something else?',
    complaint: 'Extreme thirst and huge volumes of urine since a head injury',
    patient: { name: 'Gareth Pugh', age: 40, job: 'Long-distance lorry driver', setting: 'Endocrine clinic', image: P + 'a05.jpg',
      look: 'a forty-year-old white man with a thick neck and a beard, in a checked shirt, clutching a large water bottle with a worried expression, sitting in a clinic chair' },
    opening: 'Gareth keeps a litre bottle between his knees and refills it from the tap in the corridor.',
    referral: 'Gareth is **extremely thirsty** and is passing **very large volumes of urine day and night**, around **9 litres a day**. It began about **a month after a road accident in which he hit his head**. His GP suspects **diabetes** because of the thirst and the frequent urine.',
    obs: [['Pulse', '88 per minute'], ['Blood pressure', '118 / 74'], ['Urine volume', 'About 9 litres a day'], ['Urine', 'Pale and very dilute']],
    notes: ['Head injury in a lorry crash five weeks ago, with a fracture at the base of the skull.', 'Drinking 8 to 10 litres of water a day.', 'No family history of diabetes.', 'Weight steady. No hunger. Not overweight.'],
    startFacts: ['dilute', 'head'],
    facts: {
      dilute: 'His urine is pale and very dilute, up to about 9 litres a day', head: 'He had a head injury five weeks ago, before the thirst began',
      noglu: 'There is no glucose in his urine and his blood glucose is normal', thirst: 'He is intensely thirsty and drinks 8 to 10 litres a day',
      conc: 'His blood is slightly too concentrated (low water potential)', stays: 'After a period without water his urine stays dilute', adh: 'After an injection of ADH his urine becomes concentrated and its volume falls',
      noeat: 'He has not been eating or drinking unusually sweet foods', weight: 'His weight has not changed and he is not hungry',
    },
    questions: [
      { id: 'q1', q: 'When did the thirst and urine begin?', a: 'About a **month after the crash**. At first I thought it was the painkillers.', fact: 'head' },
      { id: 'q2', q: 'How much do you drink and pass?', a: 'Eight to ten litres of water a day and about the same in urine, day and night. It is clear, like water.', fact: 'thirst' },
      { id: 'q3', q: 'Has your weight or appetite changed?', a: 'No. I eat the same as ever and my weight is the same.', fact: 'weight' },
      { id: 'q4', q: 'Do you eat or drink a lot of sugary things?', a: 'No, I drink water. I do not like fizzy drinks.', fact: 'noeat' },
      { id: 'q5', q: 'Does diabetes run in your family?', a: 'No, nobody that I know of.', value: 'useful' },
      { id: 'q6', q: 'Does the urine smell or look different?', a: 'It looks like water. No colour at all.', value: 'useful' },
      { id: 'q7', q: 'Do you sweat a lot, or work in the heat?', a: 'The cab is air-conditioned. I sweat no more than anyone.', value: 'useful' },
      { id: 'q8', q: 'Are you on any medicines?', a: 'Just painkillers after the accident.', value: 'useful' },
      { id: 'q9', q: 'How many miles do you drive a week?', a: 'About 2000.', value: 'waste' },
      { id: 'q10', q: 'What do you listen to on the road?', a: 'Radio 4. Mostly the cricket.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Test the urine for glucose and the blood glucose', result: '**No glucose** in his urine and his **blood glucose is normal**: this is not caused by too much glucose.', fact: 'noglu', value: 'key' },
      { id: 't2', name: 'Withhold water under supervision and test the urine', result: 'Even after hours without water his urine **stays dilute and plentiful**, and his blood becomes **too concentrated**.', fact: 'stays', value: 'key' },
      { id: 't3', name: 'Give an injection of ADH and test the urine again', result: 'His urine **becomes concentrated and its volume falls**: the kidneys can respond, but **ADH is not being released**.', fact: 'adh', value: 'key' },
      { id: 't4', name: 'Measure the concentration of the blood', result: 'The blood is **slightly too concentrated**: low water potential.', fact: 'conc', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal.', value: 'risky' },
      { id: 't6', name: 'Throat swab', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'adh', name: 'Too little ADH is released', sub: 'The collecting ducts reabsorb too little water' },
      { id: 'sugar', name: 'High blood glucose carrying water out in the urine', sub: 'Glucose passes into the urine' },
      { id: 'sweat', name: 'Dehydration from sweating', sub: 'Concentrated blood and urine, as the body conserves water' },
    ],
    truth: 'adh', decisive: ['noglu', 'stays', 'adh', 'head', 'dilute', 'conc'],
    treatments: [
      { id: 'x1', label: 'Replace the missing ADH with a drug that acts like it, and let him drink to thirst', verdict: 'best', why: 'ADH makes the **distal convoluted tubule and collecting ducts more permeable to water**, so **more water is reabsorbed**. The injury damaged the **posterior pituitary**, which normally releases ADH, so a replacement restores water reabsorption.' },
      { id: 'x2', label: 'Start insulin injections', verdict: 'wrong', why: 'His blood glucose is normal and there is no glucose in the urine. This is not diabetes.' },
      { id: 'x3', label: 'Restrict his fluids to ease the urine volume', verdict: 'harm', why: 'He is losing water through the kidneys. Restricting fluids would make his blood dangerously concentrated.' },
      { id: 'x4', label: 'Advise him to drink more water and see how he gets on', verdict: 'ok', why: 'It replaces what he loses, but without replacing ADH he will keep losing litres of water every day.' },
    ],
    outcome: {
      right: 'Gareth started the ADH replacement and within a day his urine volume fell to normal. He slept through the night for the first time in weeks.',
      wrong: 'Gareth was started on diabetes treatment and became very unwell. Only when the urine and blood glucose were rechecked did the team see that ADH was the problem. He recovered fully after the right treatment.',
    },
    twist: 'Thirst plus large volumes of urine sound like **diabetes** (where glucose carries water out) or like **dehydration**. But his urine has **no glucose** and is **dilute**: his kidneys cannot conserve water because **ADH is not being released** after the head injury. Read both the **blood glucose** and **nephron** lessons.',
    lessons: ['a-kidney', 'a-glucose'],
    spec: { board: 'AQA', code: '7402', refs: ['3.6.4.3 osmoregulation, hypothalamus, posterior pituitary, ADH, nephron', '3.6.4.2 control of blood glucose concentration'] },
  });

  D.add({
    id: 'a06', track: 'alevel', rank: 2, minutes: 10,
    title: 'Nobody in the family has it', tagline: 'A brother, a sister, and a baby on the way',
    complaint: 'Worried about passing on a condition that affected two siblings',
    patient: { name: 'Amira Haddad', age: 29, job: 'Pharmacist', setting: 'Genetic counselling clinic', image: P + 'a06.jpg',
      look: 'a twenty-nine-year-old Middle Eastern woman in a smart cardigan, twelve weeks pregnant, with long dark hair, looking anxious and holding a folder of notes in a consultation room' },
    opening: 'Amira has brought her family\'s medical notes and a list of questions.',
    referral: 'Amira is **12 weeks pregnant**. Her **brother Yusuf died of a serious inherited condition at 9**, and her **older sister Salma, 12**, is affected too. Her parents are **healthy**. Amira and her husband Karim have **no symptoms** and no other family history. They ask: **will the baby be affected?**',
    obs: [['Gestation', '12 weeks'], ['Amira', 'Unaffected'], ['Karim', 'Unaffected, no family history'], ['Parents', 'Both healthy']],
    notes: ['Two of her three siblings are affected: Yusuf (male, died at 9) and Salma (female, 12).', 'The third sibling, a brother, is healthy at 20.', 'Her parents are first cousins.', 'The affected children have the same condition, caused by a faulty gene.'],
    infoCard: { title: 'The family tree', body: [
      'Amira\'s parents: both healthy. Their children: **Yusuf** (male, affected, died), **Salma** (female, affected), **a third son** (unaffected) and **Amira** (unaffected).',
      'Amira married Karim, who is **unrelated** to her, and **has no family history** of the condition. Their baby is due in six months.',
    ] },
    startFacts: ['parents', 'both'],
    facts: {
      parents: 'Both parents are healthy but two of their children are affected', both: 'Both a boy and a girl in the family are affected',
      cousins: 'Her parents are first cousins', carrier: 'Amira\'s DNA test shows she carries one faulty allele', karimneg: 'Karim\'s test shows he does not carry the faulty allele',
      notx: 'An affected girl cannot come from an unaffected father if the allele is X-linked', unaff: 'Amira herself is unaffected', baby: 'The baby can only be affected if Karim also passes on a faulty allele',
      carriers: 'The baby has a 1 in 2 chance of being a carrier, like its mother',
    },
    questions: [
      { id: 'q1', q: 'Who in the family is affected?', a: '**Yusuf** and **Salma**: one brother, one sister. Both of them. My other brother and I are well.', fact: 'both' },
      { id: 'q2', q: 'Are your parents affected?', a: 'No. Both completely healthy and have been all their lives.', fact: 'parents' },
      { id: 'q3', q: 'Are your parents related?', a: 'Yes, they are first cousins. It is common in our family.', fact: 'cousins' },
      { id: 'q4', q: 'Is your husband\'s family affected?', a: 'Not as far as he knows. His family have no history of it.', value: 'useful' },
      { id: 'q5', q: 'Do you have any symptoms yourself?', a: 'None. I am well.', fact: 'unaff' },
      { id: 'q6', q: 'How are you and Karim related?', a: 'We are not. We met at university.', value: 'useful' },
      { id: 'q7', q: 'Has any other relative died young?', a: 'A cousin on my mother\'s side, I think, but I do not know the details.', value: 'useful' },
      { id: 'q8', q: 'What are you most worried about?', a: 'That our baby will go through what Yusuf did.', value: 'useful' },
      { id: 'q9', q: 'What does Karim do?', a: 'He is an engineer.', value: 'waste' },
      { id: 'q10', q: 'Where are you going on holiday this year?', a: 'We have not decided yet.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'DNA screening test for Amira', result: 'Amira **carries one faulty allele** (heterozygous): she is a **carrier**.', fact: 'carrier', value: 'key' },
      { id: 't2', name: 'DNA screening test for Karim', result: 'Karim **does not carry** the faulty allele.', fact: 'karimneg', value: 'key' },
      { id: 't3', name: 'Check the family tree for mode of inheritance', result: 'Unaffected parents, an affected boy **and an affected girl**: the pattern fits an **autosomal recessive** condition, not an X-linked one.', fact: 'notx', value: 'useful' },
      { id: 't4', name: 'Chorionic villus test on the baby now', note: 'A procedure with a small risk of miscarriage', result: 'Not needed: both parents\' results already answer the question, and the test carries a risk to the pregnancy.', value: 'risky' },
      { id: 't5', name: 'Cholesterol test for Amira', result: 'Irrelevant.', value: 'waste' },
      { id: 't6', name: 'Test the third brother', result: 'Not needed for this decision, and he has not asked to be tested.', value: 'waste' },
    ],
    options: [
      { id: 'ar', name: 'Autosomal recessive', sub: 'Unaffected carriers can have affected children' },
      { id: 'ad', name: 'Autosomal dominant', sub: 'Affected people have an affected parent' },
      { id: 'xr', name: 'X-linked recessive', sub: 'Mostly affects boys' },
    ],
    truth: 'ar', decisive: ['parents', 'both', 'carrier', 'karimneg', 'cousins'],
    treatments: [
      { id: 'x1', label: 'Explain that the condition is recessive, that Karim is not a carrier so the baby cannot be affected, and that the baby has a 1 in 2 chance of being a carrier', verdict: 'best', why: 'For a recessive condition the baby needs a faulty allele from **both** parents. Karim has none to give, so the baby cannot be affected. It has a **1 in 2** chance of inheriting Amira\'s allele and being a **carrier**.' },
      { id: 'x2', label: 'Advise an immediate invasive test on the baby', verdict: 'harm', why: 'The parents\' results already answer the question. A procedure on the baby carries a **risk** to the pregnancy and offers no new information.' },
      { id: 'x3', label: 'Tell them there is a 1 in 4 chance the baby is affected', verdict: 'wrong', why: 'The 1 in 4 figure applies only when **both** parents are carriers. Karim is not, so the chance is none.' },
      { id: 'x4', label: 'Tell them there is nothing to worry about and discharge them without explaining', verdict: 'ok', why: 'The conclusion is right for this baby, but without explaining carrier status and genetic counselling for later pregnancies and for Amira\'s siblings, much of the value is lost.' },
    ],
    outcome: {
      right: 'Amira and Karim left with a clear explanation. Their baby, born healthy, is a carrier like her mother, and when she grows up she will be offered counselling. Amira\'s healthy brother and his partner were offered screening too.',
      wrong: 'Amira and Karim spent months in distress, believing the baby had a 1 in 4 chance of being affected, and nearly had a risky invasive test. The screening results had answered the question.',
    },
    twist: 'Two affected children and healthy parents make it sound as though the whole family is at risk, and Amira\'s "no one has it" makes it sound as if nothing could be wrong. In truth it is **recessive**: **both parents were carriers**, Amira is one, but **Karim is not**. The risk to her baby comes down to **both parents** passing on a faulty allele. Read the **inheritance** lesson.',
    lessons: ['a-genetics', 'a-mutation'],
    spec: { board: 'AQA', code: '7402', refs: ['3.7.1 inheritance: autosomal and sex-linked, recessive, probability', '3.8.4.2 screening for genetically determined conditions; genetic counselling', '3.4.3 mutation'] },
  });
})(typeof window !== 'undefined' ? window : globalThis);
