/*
 * Psychology Career: A-level cases (AQA 7182), part one. Each patient is written against the specification (Psychopathology, Schizophrenia,
 * Eating behaviour, Stress). Where the specification does not name a condition (post-traumatic stress), the case file gives the definition.
 * Several cases have a twist: the patient sounds like one disorder and has another, and the lessons cover both.
 */
(function (root) {
  var D = root.DOCTOR = root.DOCTOR || {}; D.cases = D.cases || [];
  var P = '/assets/psych/';

  D.add({
    id: 'p01', track: 'psych', rank: 0, minutes: 10,
    title: 'Eleven floors', tagline: 'She climbs the stairs rather than ride a lift',
    complaint: 'Panic around lifts, and a daily climb of eleven flights',
    patient: { name: 'Hannah Doyle', age: 29, job: 'Accounts assistant', setting: 'Community mental health clinic', image: P + 'p01.jpg',
      look: 'a twenty-nine-year-old white woman with shoulder-length brown hair, in a smart work blouse and cardigan, looking tense and a little embarrassed, sitting upright in a bright clinic waiting room with her hands clasped in her lap, wearing only a blouse and a plain knitted cardigan, nothing else on her shoulders or chest' },
    opening: 'Hannah laughs nervously and says she is sure this is a waste of your time.',
    referral: 'Referred by her GP. Hannah has **avoided lifts for two years**. Her new office is on the **eleventh floor** and she now **climbs the stairs every morning** and arrives exhausted and late. When a colleague pulled her into a lift last month she **panicked, shook and cried** and had to be helped out. She wants it to stop.',
    obs: [['Appearance', 'Tidy, tense, fidgeting'], ['Speech', 'Normal pace and clear'], ['Mood (her words)', '"Fine, apart from this"'], ['Sleep and appetite', 'Normal']],
    notes: ['Avoids all lifts and now takes the stairs to the eleventh floor.', 'Panic with shaking, sweating and a pounding heart when forced into a lift.', 'Otherwise works well, sees friends and enjoys her hobbies.', 'No previous mental health history.'],
    startFacts: ['avoid', 'panic'],
    facts: {
      avoid: 'She avoids lifts and climbs eleven floors instead', panic: 'She panics (shakes, sweats, cries) when she has to use a lift',
      event: 'Two years ago she was stuck in a lift for 40 minutes, frightened, with no phone signal', after: 'The fear began straight after that event, and has stayed',
      thought: 'She believes the lift will fall or trap her again, and knows the fear is out of proportion', mood: 'Her mood is good and she enjoys her life otherwise',
      ritual: 'She has no rituals, no intrusive thoughts and nothing else she needs to do to feel safe', relief: 'She feels better as soon as she takes the stairs',
      work: 'She functions well at work, apart from the lift', family: 'No family history of mental illness', sleep: 'Her sleep and appetite are normal',
    },
    questions: [
      { id: 'q1', q: 'When did the fear start?', a: 'Two years ago. I was stuck in a lift for **forty minutes**. There was no signal. I thought I would be there all night. It has been the same ever since.', fact: 'event' },
      { id: 'q2', q: 'What goes through your mind when you think of a lift?', a: 'That it will **drop** or **jam**. I know it is silly. They are checked every year. My body does not believe me.', fact: 'thought' },
      { id: 'q3', q: 'What happens in your body when you have to use one?', a: 'My heart **pounds**, my hands shake, I sweat and I cannot breathe. I just want to get out.', fact: 'panic' },
      { id: 'q4', q: 'How do you feel when you take the stairs instead?', a: 'Better, **straight away**. I get a bit pleased with myself, to be honest.', fact: 'relief' },
      { id: 'q5', q: 'How is your mood in general?', a: 'Good, actually. I am at the gym three times a week and I see my friends. It is only this.', fact: 'mood' },
      { id: 'q6', q: 'Are there any other thoughts or habits you cannot stop?', a: 'No. I am quite relaxed about most things. I just will not go in lifts.', fact: 'ritual' },
      { id: 'q7', q: 'How is your sleep and your appetite?', a: 'Normal. I sleep well, eat well.', fact: 'sleep' },
      { id: 'q8', q: 'How is it affecting your work?', a: 'My work is fine. It is the eleven floors that wear me out. I am late twice a week.', fact: 'work' },
      { id: 'q9', q: 'Does anyone in your family have a mental illness?', a: 'No. My family are all very calm.', fact: 'family' },
      { id: 'q10', q: 'Have you tried anything yourself?', a: 'I tried to ride one with a friend and could not. I did not try again.', value: 'useful' },
      { id: 'q11', q: 'What is your favourite kind of music?', a: 'Soul, mostly. Why?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Clinical interview about the fear and the avoidance', note: 'Ask about the trigger, her thoughts and what she does about them', value: 'key', fact: 'after',
        result: 'The fear began **straight after being stuck in a lift**, is limited to **lifts**, and is kept going by **avoiding them**. She recognises it is **excessive**.' },
      { id: 't2', name: 'Make a fear hierarchy with her', note: 'List situations from least to most frightening', value: 'key', fact: 'thought',
        result: 'From least to most frightening: a **photo of a lift**, **standing in a lobby**, **pressing the call button**, **entering a lift with the doors open**, **one floor**, **three floors**. Nothing else on her list is feared.' },
      { id: 't3', name: 'Ask about rituals, checking and intrusive thoughts', value: 'useful', fact: 'ritual', result: 'No obsessions, no compulsions, no counting or checking.' },
      { id: 't4', name: 'Screening questionnaire for low mood', value: 'useful', fact: 'mood', result: 'A low score. **Mood is not low.**' },
      { id: 't5', name: 'Blood tests for thyroid and blood count', result: 'Normal. No reason for them.', value: 'waste' },
      { id: 't6', name: 'Brain MRI scan', note: 'Expensive and takes time', result: 'Normal. This will not help decide.', value: 'waste' },
    ],
    options: [
      { id: 'phobia', name: 'A specific phobia', sub: 'An intense, irrational fear of lifts' },
      { id: 'ocd', name: 'OCD', sub: 'Obsessions and compulsions to reduce anxiety' },
      { id: 'dep', name: 'Depression', sub: 'Low mood and withdrawal' },
    ],
    truth: 'phobia', decisive: ['event', 'avoid', 'ritual', 'mood', 'relief'],
    treatments: [
      { id: 'x1', label: 'Systematic desensitisation: build the fear hierarchy, teach relaxation, and move up the steps slowly', verdict: 'best', why: 'This treats a **learned fear**. She **cannot be relaxed and afraid at once** (**reciprocal inhibition**), so gradual exposure while relaxed **extinguishes** the response, one step at a time.' },
      { id: 'x2', label: 'Flooding: with her consent, a long session riding lifts with no way to escape', verdict: 'ok', why: 'Flooding **can** work quickly, because the fear fades when she cannot avoid the lift. But it is **very distressing**, and a high drop-out is likely, so it is a second choice.' },
      { id: 'x3', label: 'Prescribe an antidepressant and review in four months', verdict: 'wrong', why: 'Her mood is good. This is a **phobia**, not depression, and the **learned avoidance** will go on.' },
      { id: 'x4', label: 'Tell her to push through it alone and avoid the stairs', verdict: 'harm', why: 'Forcing her into a lift without preparation, with no consent, risks a **panic attack** that **strengthens** the fear and **breaks her trust**.' },
    ],
    outcome: {
      right: 'Hannah practised relaxing, then went up her hierarchy over eight weeks. By the end she was riding to the eleventh floor. She told her GP she had forgotten how much time the stairs had been taking.',
      wrong: 'Hannah was treated for something else and the fear stayed exactly where it was. She was still climbing eleven floors a year later, and had begun to avoid lifts in shops as well.',
    },
    twist: 'Strong **avoidance** and a **racing heart** can look like **OCD** (avoiding triggers) or a **mood disorder** (withdrawing). But Hannah has **no obsessions or rituals**, her **mood is good**, and the fear began with **one frightening event** and is **kept alive by avoiding lifts**. That is a **phobia**, learned in **two steps**.',
    lessons: ['p-phobias', 'p-ocd', 'p-abnormal'],
    teach: [{ tab: 'A specific phobia', lessons: ['p-phobias'] }, { tab: 'OCD', lessons: ['p-ocd'] }, { tab: 'Depression', lessons: ['p-depression'] }, { tab: 'Background: what counts as abnormal', lessons: ['p-abnormal'] }],
    spec: { board: 'AQA', code: '7182', refs: ['Psychopathology: characteristics of phobias', 'Psychopathology: behavioural approach (two-process model)', 'Psychopathology: systematic desensitisation and flooding'] },
  });

  D.add({
    id: 'p02', track: 'psych', rank: 0, minutes: 10,
    title: 'Forty washes a day', tagline: 'A teacher who cannot stop cleaning his hands',
    complaint: 'Hours of hand-washing, and thoughts about contamination he cannot shake',
    patient: { name: 'Daniel Mahmood', age: 34, job: 'Secondary school teacher', setting: 'Community mental health clinic', image: P + 'p02.jpg',
      look: 'a thirty-four-year-old British Pakistani man with short dark hair and a trimmed beard, wearing a shirt and tie and a lanyard, with very dry, red, cracked hands folded in his lap, looking anxious and exhausted in a clinic consulting room' },
    opening: 'Daniel keeps his hands pressed together and says he is embarrassed to be here.',
    referral: 'Referred by his GP. Daniel washes his hands **forty or more times a day** and spends **three hours** on his morning routine. The skin on his hands is **cracked and bleeding**. He says he is **tormented by thoughts that he will contaminate his pupils** and make them ill. He knows this is **unreasonable**, but cannot stop.',
    obs: [['Appearance', 'Cracked, red hands'], ['Speech', 'Normal pace, apologetic'], ['Mood (his words)', '"Worn out and ashamed"'], ['Time on routines', 'About five hours a day']],
    notes: ['Hand-washing, then checking the door and the taps, in a fixed order.', 'Distressing, repeated thoughts of making others ill.', 'Feels better for a few minutes after washing, then the thought returns.', 'Has started to be late for school.'],
    startFacts: ['wash', 'cracked'],
    facts: {
      wash: 'He washes his hands forty or more times a day', cracked: 'His skin is cracked and bleeding from washing',
      thoughts: 'He has repeated, intrusive thoughts that he will contaminate other people', insight: 'He knows his thoughts and washing are excessive but cannot stop',
      relief: 'Washing relieves his anxiety only for a few minutes before it returns', order: 'He must do his rituals in a fixed order, and has to start again if he is interrupted',
      spread: 'The rituals have spread: he also checks doors and taps many times', mother: 'His mother had similar problems with checking',
      avoid: 'He avoids touching door handles and shared equipment at school', anxious: 'He becomes very anxious if he is stopped from washing',
      mood: 'His mood is low, but only because of the exhaustion and shame', germs: 'He is not afraid of germs in general, but of harming others',
    },
    questions: [
      { id: 'q1', q: 'What goes through your mind before you wash?', a: 'That I have **touched something** and will pass it to a child. It comes back again and again. I try to push it away and it gets worse.', fact: 'thoughts' },
      { id: 'q2', q: 'Do you think the washing is reasonable?', a: 'No. I **know** it is too much. I teach science. I know what a clean hand is. I still cannot stop.', fact: 'insight' },
      { id: 'q3', q: 'How do you feel just after washing?', a: 'Better for **a few minutes**. Then the thought is back and I have to start again.', fact: 'relief' },
      { id: 'q4', q: 'What happens if someone interrupts you?', a: 'I have to **start again from the beginning**. It has to be in order. If I am stopped I feel panic.', fact: 'order' },
      { id: 'q5', q: 'Are there other things you have to do repeatedly?', a: 'I check the **door and the taps** again and again. Ten, twenty times.', fact: 'spread' },
      { id: 'q6', q: 'Does anything like this run in your family?', a: 'My mother was the same with checking. She never went out without checking the cooker six times.', fact: 'mother' },
      { id: 'q7', q: 'Do you avoid anything?', a: 'Door handles, the shared keyboard. I wait for others to open doors for me.', fact: 'avoid' },
      { id: 'q8', q: 'Are you frightened of germs in general?', a: 'It is not me I worry about. It is **hurting the children**. That is the thought.', fact: 'germs' },
      { id: 'q9', q: 'How is your mood?', a: 'Low, at the moment, because I am exhausted and ashamed. Before this I was fine.', fact: 'mood' },
      { id: 'q10', q: 'How is it affecting school?', a: 'I am late most days. I have been told it will be noticed.', value: 'useful' },
      { id: 'q11', q: 'What do you teach?', a: 'Chemistry and physics.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Structured interview about obsessions and compulsions', note: 'What the thoughts are, and what he does about them', value: 'key', fact: 'thoughts',
        result: 'Daniel has **recurring intrusive thoughts (obsessions)** about harming others, and **repetitive behaviours (compulsions)** that he carries out to **reduce his anxiety**.' },
      { id: 't2', name: 'OCD severity questionnaire', value: 'key', fact: 'insight', result: 'A **severe** score. He rates his thoughts as **excessive** and the rituals as **time-consuming** (about **five hours a day**).' },
      { id: 't3', name: 'Ask about his family history', value: 'useful', fact: 'mother', result: 'His **mother** had severe checking compulsions, which she never had treated.' },
      { id: 't4', name: 'Screen for low mood', value: 'useful', fact: 'mood', result: 'Mild to moderate low mood, which he says is **new** and linked to being worn out by the rituals.' },
      { id: 't5', name: 'Skin swabs from his hands', result: 'The skin is damaged by washing, not infected. It does not decide the diagnosis.', value: 'waste' },
      { id: 't6', name: 'Hair analysis for toxins', result: 'Nothing to find. Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'ocd', name: 'OCD', sub: 'Obsessions and compulsions to reduce anxiety' },
      { id: 'phobia', name: 'A specific phobia of germs', sub: 'An intense, irrational fear of an object' },
      { id: 'dep', name: 'Depression', sub: 'Low mood, hopeless thinking' },
    ],
    truth: 'ocd', decisive: ['thoughts', 'relief', 'order', 'spread', 'insight'],
    treatments: [
      { id: 'x1', label: 'Start an SSRI (such as fluoxetine), explain it takes three to four months to work, and add CBT', verdict: 'best', why: 'OCD is linked to **low serotonin** and over-activity in the **orbitofrontal cortex**. An **SSRI blocks reuptake** so more serotonin stays at the synapse. It is usually combined with **CBT**.' },
      { id: 'x2', label: 'CBT only, with no medication', verdict: 'ok', why: 'CBT helps with the thoughts. For severe OCD an **SSRI** is normally added, because of the **biological** factors.' },
      { id: 'x3', label: 'A long course of benzodiazepines to calm him', verdict: 'wrong', why: 'Benzodiazepines calm anxiety in the short term but carry **dependence** risks and do not treat the obsession and compulsion cycle.' },
      { id: 'x4', label: 'Flooding: make him touch dirty objects and prevent any washing', verdict: 'harm', why: 'Without his consent and a gradual plan this is **cruel**. It can **increase** distress and cause him to leave treatment.' },
    ],
    outcome: {
      right: 'Daniel started fluoxetine and weekly CBT. After four months he was washing a handful of times a day and his hands had healed. He told the clinic the thoughts were still there, but they no longer gave the orders.',
      wrong: 'Daniel was told it was a fear of germs and given advice to avoid them. The rituals grew. Within the term he was off sick, and his hands were bleeding.',
    },
    twist: 'Hand-washing and fear of contamination sound like a **phobia of germs**. But a phobia is a **fear of an object**, relieved by avoiding it. Daniel has **intrusive thoughts (obsessions)** and **repetitive rituals (compulsions)** that give only **brief relief**, and the rituals **spread** to other areas. He also has **insight**. That is **OCD**.',
    lessons: ['p-ocd', 'p-phobias', 'p-depression'],
    teach: [{ tab: 'OCD', lessons: ['p-ocd'] }, { tab: 'A specific phobia', lessons: ['p-phobias'] }, { tab: 'Depression', lessons: ['p-depression'] }],
    spec: { board: 'AQA', code: '7182', refs: ['Psychopathology: characteristics of OCD', 'Psychopathology: biological explanations for OCD (genetic and neural)', 'Psychopathology: drug therapy (SSRIs)'] },
  });

  D.add({
    id: 'p03', track: 'psych', rank: 1, minutes: 10,
    title: 'Switched off', tagline: 'A quiet man, a worried mother, and a diagnosis that could go two ways',
    complaint: 'Withdrawal, poor sleep and almost no speech at home since losing his job',
    patient: { name: 'Marcus Bailey', age: 41, job: 'Warehouse supervisor (made redundant)', setting: 'Community mental health clinic', image: P + 'p03.jpg',
      look: 'a forty-one-year-old dark-skinned Black British man of African-Caribbean heritage with a medium build with short greying hair and a trimmed beard, in a dark jumper, looking weary and downcast, sitting slumped in a chair in a clinic consulting room with his hands loosely clasped' },
    opening: 'Marcus answers in a quiet voice and does not look up.',
    referral: 'Referred by his GP at the request of his sister. Marcus was **made redundant four months ago**. Since then he has **barely spoken at home**, stopped seeing friends, **sleeps badly** and has **lost weight**. His sister fears he might have **schizophrenia**, as her husband\'s cousin does, because he is so silent and flat.',
    obs: [['Appearance', 'Unshaven, slow movements'], ['Speech', 'Quiet, slow, but clear sentences'], ['Mood (his words)', '"Empty. A failure."'], ['Sleep', 'Wakes at 4 am, cannot return to sleep']],
    notes: ['Low mood most of the day, for four months.', 'Weight down 6 kg. Little appetite.', 'Has stopped going to football, which he loved.', 'No voices or unusual beliefs reported to his sister.'],
    startFacts: ['mood', 'sleep'],
    facts: {
      mood: 'He feels empty, worthless and low for most of the day', sleep: 'He wakes at 4 am every night and cannot return to sleep',
      appetite: 'His appetite has fallen and he has lost 6 kg', triad: 'He thinks he is a failure, that everything is pointless and that nothing will improve',
      absolute: 'He thinks in absolutes: "I have lost everything", "I will never work again"', conc: 'He cannot concentrate to read or watch television',
      nohall: 'He hears no voices and has no unusual beliefs', speech: 'He speaks in full, sensible sentences when asked about how he feels',
      onset: 'It began after he lost his job, four months ago', joy: 'He has lost interest in football and seeing friends', family: 'His sister has noticed his withdrawal but not any odd behaviour',
      kids: 'He feels he has let down his two children',
    },
    questions: [
      { id: 'q1', q: 'How would you describe your mood?', a: 'Empty. **Worthless.** Most days I do not see the point.', fact: 'mood' },
      { id: 'q2', q: 'What do you think about the future?', a: 'It is **finished**. I will never work again. I have **lost everything**. I let my kids down.', fact: 'triad' },
      { id: 'q3', q: 'How are you sleeping?', a: 'I am awake at **four** every morning. I lie there and go through everything I have done wrong.', fact: 'sleep' },
      { id: 'q4', q: 'Has your appetite changed?', a: 'I am not hungry. I have lost about six kilos.', fact: 'appetite' },
      { id: 'q5', q: 'Can you concentrate on things?', a: 'No. I read the same page ten times. I gave up on the television.', fact: 'conc' },
      { id: 'q6', q: 'Do you ever hear voices, or have beliefs other people find strange?', a: 'No. Nothing like that. I just feel like a failure.', fact: 'nohall' },
      { id: 'q7', q: 'Your sister says you barely speak at home. Is that so?', a: 'I do not have much to say. But I can talk to you. I am just **tired** and **sad**.', fact: 'speech' },
      { id: 'q8', q: 'When did this start?', a: 'After they let me go in the spring. I was fine before that.', fact: 'onset' },
      { id: 'q9', q: 'Are there things you used to enjoy?', a: 'Football every Sunday. I have not been in months. I do not see the point.', fact: 'joy' },
      { id: 'q10', q: 'How is your relationship with the children?', a: 'I feel I have let them down. I see them but I hide when I can.', fact: 'kids' },
      { id: 'q11', q: 'Which team do you support?', a: 'Leicester. Do not ask.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Clinical interview about mood, sleep and thinking', value: 'key', fact: 'triad',
        result: 'He describes **low mood**, **worthlessness**, **poor sleep and appetite**, and **negative thoughts about himself, his world and his future** (the negative triad). He expresses himself clearly.' },
      { id: 't2', name: 'Ask directly about hallucinations and unusual beliefs', value: 'key', fact: 'nohall', result: 'He **denies** voices, visions and unusual beliefs, and shows **no signs** of them during the interview.' },
      { id: 't3', name: 'Depression questionnaire', value: 'useful', fact: 'mood', result: 'A **moderately severe** score, with the highest scores on **low mood**, **loss of interest** and **sleep**.' },
      { id: 't4', name: 'Collateral history from his sister', value: 'useful', fact: 'family', result: 'She describes **withdrawal and sadness** after the redundancy, but **no odd or frightening behaviour**.' },
      { id: 't5', name: 'Brain scan', note: 'Expensive and not needed', result: 'Normal. It would not distinguish the two diagnoses.', value: 'waste' },
      { id: 't6', name: 'Genetic test for schizophrenia', result: 'There is no such test. Useless.', value: 'waste' },
    ],
    options: [
      { id: 'dep', name: 'Depression', sub: 'Low mood, negative thinking, disturbed sleep' },
      { id: 'sch', name: 'Schizophrenia', sub: 'Negative symptoms: speech poverty and avolition' },
      { id: 'ocd', name: 'OCD', sub: 'Obsessions and compulsions' },
    ],
    truth: 'dep', decisive: ['mood', 'triad', 'nohall', 'speech'],
    treatments: [
      { id: 'x1', label: 'CBT to identify and challenge his negative, irrational thoughts, with behavioural activation', verdict: 'best', why: 'Depression is kept going by **negative thoughts** (Beck\'s **negative triad**) and **irrational beliefs** (Ellis\'s **ABC**). **CBT** teaches him to **identify and dispute** them, and **activity** lets him test whether his predictions are true.' },
      { id: 'x2', label: 'Start an antidepressant drug and review in a month', verdict: 'ok', why: 'Medication can help in moderate to severe depression, but on its own it does not teach him to **change the thinking** that maintains it.' },
      { id: 'x3', label: 'Start an antipsychotic drug', verdict: 'harm', why: 'He has **no psychotic symptoms**. An antipsychotic would give side effects and no benefit, and would **mislabel** him.' },
      { id: 'x4', label: 'Tell him to pull himself together and find a new job', verdict: 'wrong', why: 'He **cannot** just stop: depression changes **thinking and motivation**. Advice like this can deepen the **worthlessness**.' },
    ],
    outcome: {
      right: 'Marcus began weekly CBT. In the sessions he learned to spot "I have lost everything" and test it. By the third month he was sleeping better, and he was back at football on Sundays.',
      wrong: 'Marcus was labelled with a psychotic illness and given medicine he did not need. He felt more ashamed than ever and stopped coming. His sister brought him back eight months later, much more unwell.',
    },
    twist: 'Silence, withdrawal and a flat face look like the **negative symptoms of schizophrenia** (speech poverty and avolition). But Marcus **speaks fully when asked**, has **no hallucinations or delusions**, and describes **lowered mood, worthlessness** and the **negative triad**. The silence is **sadness**, not a loss of speech.',
    lessons: ['p-depression', 'p-schiz-class', 'p-abnormal'],
    teach: [{ tab: 'Depression', lessons: ['p-depression'] }, { tab: 'Schizophrenia', lessons: ['p-schiz-class'] }, { tab: 'OCD', lessons: ['p-ocd'] }, { tab: 'Background: what counts as abnormal', lessons: ['p-abnormal'] }],
    spec: { board: 'AQA', code: '7182', refs: ['Psychopathology: characteristics of depression', 'Psychopathology: Beck\'s cognitive theory and Ellis\'s ABC model', 'Psychopathology: CBT', 'Schizophrenia: classification (positive and negative symptoms)'] },
  });

  D.add({
    id: 'p04', track: 'psych', rank: 1, minutes: 10,
    title: 'Two voices', tagline: 'Thoughts he cannot stop, and voices that are not his own',
    complaint: 'Hearing two voices, convinced the neighbours are controlling him, and withdrawing from friends',
    patient: { name: 'Jordan Ellis', age: 22, job: 'University student', setting: 'Early intervention service', image: P + 'p04.jpg',
      look: 'a twenty-two-year-old mixed-heritage young man with short curly hair, wearing a grey hooded top, unshaven and tired, looking wary and glancing to one side, sitting in a bare clinic room' },
    opening: 'Jordan glances at the window before he answers, as though checking that nobody is listening.',
    referral: 'Referred by his tutor. Over **six weeks** Jordan has become withdrawn and stopped attending lectures. His flatmates say he **talks to himself**. He tells the clinic he hears **two voices** that **comment on what he is doing**, and that **the neighbours are using the television to control him**. He thinks the voices come from **outside his head**.',
    obs: [['Appearance', 'Unwashed, tired'], ['Speech', 'Sparse, stops mid-sentence'], ['Mood (his words)', '"Watched"'], ['Duration', 'Six weeks']],
    notes: ['Hears two voices commenting on his actions, for six weeks.', 'Believes neighbours control him through the television.', 'Has stopped washing and going to lectures.', 'A cousin was treated for schizophrenia.'],
    startFacts: ['voices', 'weeks'],
    facts: {
      voices: 'He hears two voices commenting on his actions, which he believes come from outside', weeks: 'The symptoms have lasted six weeks',
      delusion: 'He is convinced the neighbours are controlling him through the television', noinsight: 'He does not accept that anything is wrong with him',
      avol: 'He has lost the motivation to wash, eat or attend lectures', speechpov: 'He says very little and often stops mid-sentence', cousin: 'A cousin has been treated for schizophrenia',
      intrusive: 'He does not describe intrusive thoughts of his own, only voices he thinks are other people', nomood: 'His mood is not low: he is more frightened than sad',
      nodrug: 'He has taken no drugs and drinks little', sudden: 'It began over a few weeks after a stressful exam term',
    },
    questions: [
      { id: 'q1', q: 'Tell me about the voices.', a: 'There are **two** of them. They say what I am doing: "He is getting up. He is putting the kettle on." They are **outside**. They are not me.', fact: 'voices' },
      { id: 'q2', q: 'Why do you think this is happening?', a: 'The neighbours. They have set up something in the **television**. They are **controlling** what I think.', fact: 'delusion' },
      { id: 'q3', q: 'Do you think anything is wrong with you?', a: 'No. **There is nothing wrong with me.** It is them.', fact: 'noinsight' },
      { id: 'q4', q: 'How long has this been going on?', a: 'About **six weeks**. It started in the exam term.', fact: 'weeks' },
      { id: 'q5', q: 'How are you managing day to day?', a: 'I cannot be bothered to wash or go in. It does not seem to matter.', fact: 'avol' },
      { id: 'q6', q: 'Do you have thoughts of your own that you cannot stop?', a: 'No. It is not **my** thoughts. It is **their** voices.', fact: 'intrusive' },
      { id: 'q7', q: 'Is anyone in your family unwell?', a: 'My cousin Ravi was in hospital with schizophrenia. We do not talk about it.', fact: 'cousin' },
      { id: 'q8', q: 'How is your mood?', a: 'Scared, mostly. I am not sad. I am **watched**.', fact: 'nomood' },
      { id: 'q9', q: 'Have you used any drugs?', a: 'No, I do not even drink much. I have not had anything.', fact: 'nodrug' },
      { id: 'q10', q: 'How are you sleeping?', a: 'Badly. The voices keep going at night.', value: 'useful' },
      { id: 'q11', q: 'Which course are you doing?', a: 'Geography. Second year.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Clinical interview about his experiences', note: 'Where the voices come from, and what he believes', value: 'key', fact: 'voices',
        result: 'He hears **voices** and holds **fixed, irrational beliefs** of persecution (**delusions**), with **no insight**. There are **negative symptoms** too: **avolition** and sparse speech.' },
      { id: 't2', name: 'Check how long the symptoms have lasted', value: 'key', fact: 'weeks', result: 'The symptoms have lasted **six weeks**, longer than the **one month** usually needed for a diagnosis.' },
      { id: 't3', name: 'Ask about obsessions, compulsions and rituals', value: 'useful', fact: 'intrusive', result: 'He has **no compulsions**, and he does **not** experience the voices as his own thoughts.' },
      { id: 't4', name: 'Collateral history from his flatmates and family', value: 'useful', fact: 'cousin', result: 'His **cousin** has schizophrenia. His flatmates describe a **gradual change** over the term.' },
      { id: 't5', name: 'Whole-body CT scan', note: 'Uses radiation', result: 'Normal. It does not help, and exposes him to radiation.', value: 'risky' },
      { id: 't6', name: 'Test his hearing', result: 'Normal. Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'sch', name: 'Schizophrenia', sub: 'Hallucinations, delusions and negative symptoms' },
      { id: 'ocd', name: 'OCD', sub: 'Intrusive thoughts he recognises as his own' },
      { id: 'dep', name: 'Depression', sub: 'Low mood and withdrawal' },
    ],
    truth: 'sch', decisive: ['voices', 'delusion', 'noinsight', 'weeks', 'avol'],
    treatments: [
      { id: 'x1', label: 'Start an antipsychotic drug that blocks dopamine receptors, with regular review and support', verdict: 'best', why: 'Antipsychotics such as **chlorpromazine** (a **dopamine antagonist**) **block D2 receptors**, which reduces the **hallucinations and delusions** linked to **excess dopamine**. Review is needed for **side effects**.' },
      { id: 'x2', label: 'CBT to help him make sense of the voices, without medication at first', verdict: 'ok', why: 'CBT helps people **cope with** and **reinterpret** their experiences, but it is normally given **alongside** drugs, not instead.' },
      { id: 'x3', label: 'Start an SSRI for anxiety', verdict: 'wrong', why: 'SSRIs act on **serotonin**, for OCD and depression. They do not treat **hallucinations and delusions**.' },
      { id: 'x4', label: 'Reassure him and send him home with no follow-up', verdict: 'harm', why: 'Untreated psychosis tends to get **worse**, and early treatment gives the best outcome.' },
    ],
    outcome: {
      right: 'Jordan began an antipsychotic and weekly meetings with his care team. Within a month the voices had faded to a murmur. He returned to his course part-time the following term, with a support plan.',
      wrong: 'Jordan was sent away with reassurance. The voices got louder, and he was brought to hospital by the police three months later in a much worse state.',
    },
    twist: 'Thoughts he cannot stop might sound like **OCD**. But in OCD the person recognises the thoughts as **their own** and knows they are **excessive**. Jordan hears **voices he believes come from outside**, holds **fixed false beliefs** and has **no insight**: those are **hallucinations and delusions**, so **schizophrenia**.',
    lessons: ['p-schiz-class', 'p-ocd', 'p-schiz-bio'],
    teach: [{ tab: 'Schizophrenia', lessons: ['p-schiz-class', 'p-schiz-bio', 'p-schiz-treat'] }, { tab: 'OCD', lessons: ['p-ocd'] }, { tab: 'Depression', lessons: ['p-depression'] }],
    spec: { board: 'AQA', code: '7182', refs: ['Schizophrenia: classification (hallucinations, delusions, negative symptoms)', 'Schizophrenia: the dopamine hypothesis', 'Schizophrenia: antipsychotic drugs'] },
  });

  D.add({
    id: 'p05', track: 'psych', rank: 2, minutes: 10,
    title: 'Gunfire at night', tagline: 'He hears it and sees it, but only some of the time',
    complaint: 'Nightmares, hearing explosions and not being able to settle since an incident at work',
    patient: { name: 'Tom Hargreaves', age: 33, job: 'Paramedic (off sick)', setting: 'Trauma service outpatient clinic', image: P + 'p05.jpg',
      look: 'a thirty-three-year-old white man with a close-cropped haircut and tired eyes, wearing a green paramedic fleece with the badge removed, sitting tensely upright and scanning the room in a clinic consulting room' },
    opening: 'Tom sits facing the door, and flinches when a car goes past outside.',
    referral: 'Referred by his GP. **Five months ago** Tom attended a **serious motorway collision** in which a child died. Since then he has had **nightmares**, **vivid memories** that make him feel he is **back at the scene**, and he **startles at sirens**. He has **stopped driving ambulances** and has had **no proper sleep**. His GP asks: **is this psychosis?**',
    obs: [['Appearance', 'Alert, tense, unshaven'], ['Speech', 'Clear and fast'], ['Mood (his words)', '"On edge, all the time"'], ['Sleep', 'About three hours, with nightmares']],
    notes: ['Serious motorway collision attended five months ago.', 'Nightmares and vivid images of the scene, set off by sirens.', 'Avoids ambulances, motorways and talking about it.', 'Startles easily and sleeps badly.'],
    startFacts: ['event', 'cue'],
    facts: {
      event: 'He attended a real, traumatic collision five months ago', cue: 'The images and noises are set off by sirens, brakes and the smell of fuel',
      memory: 'He knows what he sees and hears are memories of what really happened', avoid: 'He avoids ambulances, motorways and anything that reminds him', arousal: 'He is always on guard, startles easily and sleeps about three hours',
      night: 'He has repeated nightmares of the collision', blame: 'He believes it was his fault, that he should have saved the child', nodel: 'He has no false beliefs about the world and no voices when no cue is present',
      mood: 'His mood is low and flat, mostly because of the lack of sleep and guilt', after: 'None of this began until after the collision', fam: 'There is no family history of mental illness',
    },
    infoCard: { title: 'How post-traumatic stress is defined', body: [
      'Here is the definition of **post-traumatic stress disorder (PTSD)** that you need for this case.',
      'PTSD can follow **exposure to a real, threatening or traumatic event**. For **more than a month** afterwards the person has **intrusive re-experiencing** (flashbacks and nightmares), **avoidance** of reminders, **negative changes in mood and beliefs**, and **hyperarousal** (always on guard, easily startled, unable to sleep).',
    ] },
    questions: [
      { id: 'q1', q: 'Tell me what you see and hear.', a: 'The **crash**. The noise of the **brakes**, the smell of fuel, the little girl. It is like being **back there**. It happens when a **siren** goes past.', fact: 'cue' },
      { id: 'q2', q: 'When it happens, do you know it is a memory?', a: 'Yes. Afterwards. I **know** it is **the crash**. It is what really happened, but it feels as though it is happening **now**.', fact: 'memory' },
      { id: 'q3', q: 'Does this happen when nothing reminds you of it?', a: 'No. Not really. It is always **something** that sets it off. A siren, a smell.', fact: 'nodel' },
      { id: 'q4', q: 'How are you sleeping?', a: 'Three hours at best. I have the **same nightmare** nearly every night.', fact: 'arousal' },
      { id: 'q5', q: 'What do you avoid?', a: 'Ambulances. The motorway. Even talking about it. My wife says I changed the subject from the news.', fact: 'avoid' },
      { id: 'q6', q: 'Do you blame anyone for what happened?', a: 'Myself. I keep thinking I should have **got there faster**. I keep going over it.', fact: 'blame' },
      { id: 'q7', q: 'When did all this start?', a: 'The night after the crash. I was **fine** before. Nine years in the job and nothing like it.', fact: 'after' },
      { id: 'q8', q: 'How is your mood?', a: 'Flat. I am exhausted and **ashamed** of how I react.', fact: 'mood' },
      { id: 'q9', q: 'Does anyone in your family have mental health problems?', a: 'No. We are pretty steady.', fact: 'fam' },
      { id: 'q10', q: 'How are you getting on at home?', a: 'My wife is worried. I am short with her. I do not mean to be.', value: 'useful' },
      { id: 'q11', q: 'Which ambulance station do you work from?', a: 'Eastgate. Why?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Clinical interview about the event and his symptoms', value: 'key', fact: 'event',
        result: 'He was exposed to a **real traumatic event**, and has **re-experiencing** (flashbacks and nightmares), **avoidance** and **hyperarousal** for **five months**. The images are **memories**, **triggered by cues**.' },
      { id: 't2', name: 'Ask about hallucinations and fixed false beliefs', value: 'key', fact: 'nodel', result: 'There are **no voices or delusions** outside the flashbacks. He recognises the experiences as **memories**. He has no unusual beliefs about the world.' },
      { id: 't3', name: 'Map what sets the experiences off', value: 'useful', fact: 'cue', result: 'Every episode follows a **sound, smell or sight** linked to the collision: **sirens, brakes, fuel**.' },
      { id: 't4', name: 'Ask about avoidance and sleep', value: 'useful', fact: 'arousal', result: 'He avoids reminders, is **hypervigilant** and sleeps about **three hours**.' },
      { id: 't5', name: 'Brain MRI scan', note: 'Not useful', result: 'Normal. It would not change anything.', value: 'waste' },
      { id: 't6', name: 'Whole-body CT scan', note: 'Uses radiation', result: 'Normal. No reason for it.', value: 'risky' },
    ],
    options: [
      { id: 'ptsd', name: 'Post-traumatic stress', sub: 'Flashbacks, avoidance and hyperarousal after a real trauma' },
      { id: 'sch', name: 'Schizophrenia', sub: 'Hallucinations and delusions' },
      { id: 'phobia', name: 'A specific phobia', sub: 'Fear of a particular thing, avoided' },
    ],
    truth: 'ptsd', decisive: ['event', 'cue', 'memory', 'nodel', 'avoid'],
    treatments: [
      { id: 'x1', label: 'CBT to challenge his beliefs ("it was my fault") and to face reminders gradually, plus stress-management skills', verdict: 'best', why: 'His **negative beliefs** can be **challenged** with CBT, and **gradual exposure** weakens the **conditioned** link between **cues and fear**. **Relaxation and stress management** calm the **overactive stress response**.' },
      { id: 'x2', label: 'An SSRI for mood and sleep, reviewed in a month, alongside support', verdict: 'ok', why: 'Medication can ease **low mood and anxiety**, but does not remove the **memory**, so it works best **with** therapy.' },
      { id: 'x3', label: 'An antipsychotic drug', verdict: 'wrong', why: 'He does not have **psychosis**: his experiences are **memories** with **triggers**, and he has **insight**.' },
      { id: 'x4', label: 'Send him straight back onto the front line to face it', verdict: 'harm', why: 'Being **flooded** with the cues **before** treatment and support can **deepen** the trauma and put him at risk.' },
    ],
    outcome: {
      right: 'Tom began trauma-focused CBT, learned to slow his breathing in the moment, and visited the scene with his therapist after twelve weeks. The nightmares eased, and he returned to the service in a training role.',
      wrong: 'Tom was treated as psychotic and given medicine that dulled him without helping. He left the service, and the nightmares carried on for years.',
    },
    twist: 'Hearing explosions and seeing things that are not there sounds like **psychosis**. But a **flashback** is a **memory of a real event**, set off by a **cue**, and he **knows it is a memory**. There are **no delusions**, and it began **after a trauma**, with **avoidance** and **hyperarousal**. That is **post-traumatic stress**.',
    lessons: ['p-trauma', 'p-schiz-class', 'p-stress-body'],
    teach: [{ tab: 'Post-traumatic stress', lessons: ['p-trauma', 'p-stress-body'] }, { tab: 'Schizophrenia', lessons: ['p-schiz-class'] }, { tab: 'A specific phobia', lessons: ['p-phobias'] }],
    spec: { board: 'AQA', code: '7182', refs: ['Stress: the physiology of stress (SAM and HPA)', 'Psychopathology: behavioural approach (conditioning)', 'Schizophrenia: classification (hallucinations)', 'Post-traumatic stress is defined in the case file'] },
  });

})(typeof window !== 'undefined' ? window : globalThis);
