/* Doctor Career: GCSE cases for the Specialty registrar and Consultant ranks (AQA 8461). */
(function (root) {
  var D = root.DOCTOR = root.DOCTOR || {}; D.cases = D.cases || [];
  var P = '/assets/doctor/';

  D.add({
    id: 'g08', track: 'gcse', rank: 3, minutes: 10,
    title: 'The chesty toddler', tagline: 'A cough all winter, and a child who will not put on weight',
    complaint: 'Cough and wheeze all winter, and poor weight gain',
    patient: { name: 'Layla Ahmed', age: 3, job: 'Nursery pupil', setting: 'Children\'s outpatient clinic', image: P + 'g08.jpg',
      look: 'a three-year-old girl of South Asian heritage with dark curly hair, thin for her age, sitting on her mother\'s lap in a children\'s clinic, looking tired with a hand on her chest' },
    opening: 'Layla coughs a wet, rattly cough. Her mother has brought a thick folder of GP letters.',
    referral: 'Layla has had a **wet cough and wheeze for most of the winter**, with **four chest infections** treated with antibiotics, and she has **not been gaining weight** even though she eats well. Her GP wonders if it is **asthma or an allergy**.',
    obs: [['Weight', '10.2 kg (well below the expected range)'], ['Breathing', '34 per minute'], ['Temperature', '37.2 °C'], ['Chest', 'Wheeze and crackles on both sides']],
    notes: ['Both parents are healthy. Layla is their only child.', 'Her father\'s cousin died in childhood of a lung condition.', 'Greasy, bulky stools that are hard to flush away.', 'Skin tastes salty when kissed, her mother says.'],
    startFacts: ['weight', 'infect'],
    facts: {
      weight: 'She is gaining weight poorly despite a good appetite', infect: 'She has had four chest infections this winter',
      mucus: 'She coughs up thick, sticky mucus, not clear mucus', greasy: 'Her stools are greasy, bulky and pale', salty: 'Her skin tastes very salty',
      parents: 'Both parents are healthy, and a cousin on her father\'s side died of a lung condition', noallergy: 'No eczema, no hay fever, and no link to pets, pollen or foods',
      sweat: 'Her sweat contains far too much salt', dna: 'A DNA test shows two faulty alleles of the cystic fibrosis gene', prick: 'A skin prick test is negative to common allergens',
      wheezeinfect: 'Her wheeze does not follow a pattern of triggers', cousin: 'The family history fits a recessive condition',
    },
    questions: [
      { id: 'q1', q: 'What is the cough like?', a: 'It is **wet and rattly**. She coughs up **thick, sticky mucus** that is hard for her to shift, even when she is not ill.', fact: 'mucus' },
      { id: 'q2', q: 'How is her appetite and weight?', a: 'She eats like a horse. She is still **below the bottom line** on the chart, and has been dropping down it.', fact: 'weight' },
      { id: 'q3', q: 'What are her stools like?', a: '**Greasy, pale, bulky** and very smelly. They float and do not flush away.', fact: 'greasy' },
      { id: 'q4', q: 'Have you noticed anything about her skin?', a: 'When I kiss her, she tastes **really salty**. My mother-in-law said it was a sign of something.', fact: 'salty' },
      { id: 'q5', q: 'Does she wheeze after pets, pollen or food?', a: 'No pattern at all. She has no eczema, and no hay fever in the family.', fact: 'noallergy' },
      { id: 'q6', q: 'Is there a family history of lung or other conditions?', a: 'We are healthy. But my husband\'s cousin died young of a lung condition. It was never explained.', fact: 'parents' },
      { id: 'q7', q: 'How many chest infections has she had?', a: 'Four since October. The antibiotics help for a bit, then it comes back.', fact: 'infect' },
      { id: 'q8', q: 'Is she up to date with her vaccinations?', a: 'Yes, all of them.', value: 'useful' },
      { id: 'q9', q: 'Does she sleep well?', a: 'She wakes coughing most nights.', value: 'useful' },
      { id: 'q10', q: 'What is her favourite bedtime story?', a: 'The Gruffalo, every night.', value: 'waste' },
      { id: 'q11', q: 'What colour is her bedroom?', a: 'Yellow, why?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Sweat test', note: 'Measures the salt in her sweat', result: 'Her sweat contains **far more salt than normal**.', fact: 'sweat', value: 'key' },
      { id: 't2', name: 'DNA test for the cystic fibrosis gene', result: 'She has **two copies of the faulty recessive allele**: cystic fibrosis is confirmed. Both parents are carriers.', fact: 'dna', value: 'key' },
      { id: 't3', name: 'Skin prick allergy test', result: 'Negative to common allergens: **allergy is unlikely**.', fact: 'prick', value: 'useful' },
      { id: 't4', name: 'Weigh and plot her growth chart', result: 'She has been **falling away from the line** for 18 months.', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Shows changes in the lungs, but it does not explain the cause and exposes her to radiation.', value: 'risky' },
      { id: 't6', name: 'Throat swab for a virus', result: 'Nothing found: not helpful for a long-standing problem.', value: 'waste' },
    ],
    options: [
      { id: 'cf', name: 'Cystic fibrosis', sub: 'A disorder of cell membranes caused by a recessive allele' },
      { id: 'asthma', name: 'Asthma triggered by an allergy', sub: 'An immune reaction in the airways' },
      { id: 'infections', name: 'Ordinary repeated infections', sub: 'Common in toddlers who attend nursery' },
    ],
    truth: 'cf', decisive: ['mucus', 'greasy', 'salty', 'sweat', 'dna', 'weight', 'noallergy'],
    treatments: [
      { id: 'x1', label: 'Refer to a cystic fibrosis team for daily chest physiotherapy, medicines and antibiotics for infections, and explain the inheritance and options for future pregnancies', verdict: 'best', why: 'Cystic fibrosis is caused by a **recessive allele**, so both parents are healthy carriers and each pregnancy has a **1 in 4 chance** of an affected child. The family can be told about **embryo screening**, with its benefits and ethical issues, so that they can make informed choices.' },
      { id: 'x2', label: 'Prescribe an asthma inhaler and discharge her', verdict: 'harm', why: 'This is not asthma, so the inhaler will not address the sticky mucus or her poor weight gain. Her condition would worsen without specialist care.' },
      { id: 'x3', label: 'Give another course of antibiotics and review in the spring', verdict: 'wrong', why: 'Antibiotics treat each infection but not the underlying condition, and her weight is still falling.' },
      { id: 'x4', label: 'Refer to the specialist team, but tell the parents there is no inherited cause', verdict: 'ok', why: 'The referral is right, but cystic fibrosis is inherited, and the parents need accurate information about the chances for any future child.' },
    ],
    outcome: {
      right: 'Layla began daily physiotherapy and treatment at the cystic fibrosis centre and started to put on weight within weeks. Her parents had counselling about inheritance and were glad to know what they were facing.',
      wrong: 'Layla continued to fall behind on her growth chart and spent more time in hospital with chest infections. The diagnosis, when it came, could have been made months earlier from her weight, stools and salty skin.',
    },
    twist: 'Cough, wheeze and repeated infections sound like **asthma** or **ordinary toddler infections**. But the **thick mucus**, the **greasy stools**, the **salty skin** and the **poor weight gain** show a different cause altogether: a **recessive inherited disorder**. Read the **inherited disorders** lesson.',
    lessons: ['inherited', 'allergy', 'pathogens'],
    spec: { board: 'AQA', code: '8461', refs: ['4.6.1.7 inherited disorders (cystic fibrosis, embryo screening)', '4.6.1.6 genetic inheritance', '4.2.2.5 health issues (allergies and asthma)'] },
  });

  D.add({
    id: 'g09', track: 'gcse', rank: 3, minutes: 10,
    title: 'Run down and low', tagline: 'Infections that will not clear, and a man who has given up',
    complaint: 'Repeated infections, weight loss and feeling hopeless',
    patient: { name: 'Daniel Mensah', age: 41, job: 'Taxi driver', setting: 'Hospital outpatient clinic', image: P + 'g09.jpg',
      look: 'a forty-one-year-old Black British man who has lost weight, with hollow cheeks and tired eyes, wearing a loose jumper, sitting slumped in a clinic chair' },
    opening: 'Daniel speaks quietly. He says he is not sure why he came.',
    referral: 'Daniel has had **two chest infections and persistent mouth sores** this year, has **lost 12 kg**, and says he feels **low and hopeless**. His GP wondered about **depression** or **Type 2 diabetes**. His notes mention that he was **diagnosed with HIV eight years ago**.',
    obs: [['Weight', '12 kg lost in 8 months'], ['Temperature', '37.9 °C'], ['Pulse', '96 per minute'], ['Mouth', 'White sores on the tongue']],
    notes: ['Diagnosed with HIV eight years ago and took antiretroviral drugs until last year.', 'Stopped his drugs about 14 months ago after moving house and losing touch with the clinic.', 'Has been sleeping badly and has lost interest in things.', 'No family history of diabetes.'],
    startFacts: ['loss', 'hivhx'],
    facts: {
      loss: 'He has lost 12 kg over eight months without trying', hivhx: 'He has known HIV infection, diagnosed eight years ago',
      stopped: 'He stopped his antiretroviral drugs 14 months ago', infect: 'He has had two chest infections and persistent mouth sores this year', mood: 'He feels low and hopeless and has lost interest in things',
      thirst: 'He is not especially thirsty and passes urine normally', glu: 'His blood glucose is normal', cells: 'His count of immune cells is very low', ill: 'His low mood began after he became repeatedly ill',
      nodiabetes: 'No excess thirst, no sugar in the urine, and no family history of diabetes',
    },
    questions: [
      { id: 'q1', q: 'Tell me about your HIV treatment.', a: 'I had my tablets for seven years. Then I moved, lost my clinic and thought, I feel fine, I will stop. That was about **fourteen months ago**.', fact: 'stopped' },
      { id: 'q2', q: 'How have you been in yourself?', a: 'Terrible. I **cannot shake infections** and my mouth is sore. I have lost weight and I am exhausted.', fact: 'infect' },
      { id: 'q3', q: 'How is your mood?', a: 'Low. I do not see the point of anything. It started when I kept being ill and could not work.', fact: 'mood' },
      { id: 'q4', q: 'Has your weight changed?', a: '**Twelve kilos** gone. I have not been dieting.', fact: 'loss' },
      { id: 'q5', q: 'Are you very thirsty or passing a lot of urine?', a: 'No, nothing like that.', fact: 'thirst' },
      { id: 'q6', q: 'Does diabetes run in your family?', a: 'Not that I know of.', value: 'useful' },
      { id: 'q7', q: 'Which came first, the low mood or the illnesses?', a: 'The infections. The low mood crept in after I stopped being able to drive.', fact: 'ill' },
      { id: 'q8', q: 'Do you have support from family or friends?', a: 'My sister texts. I have been avoiding people.', value: 'useful' },
      { id: 'q9', q: 'Where do you park your cab?', a: 'Outside my flat.', value: 'waste' },
      { id: 'q10', q: 'What kind of music do you play in the cab?', a: 'Highlife, mostly.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Count his immune cells (helper T cells)', result: 'His count of immune cells is **very low**: the immune system is badly damaged.', fact: 'cells', value: 'key' },
      { id: 't2', name: 'Blood glucose test', result: 'Normal: **not diabetes**.', fact: 'glu', value: 'useful' },
      { id: 't3', name: 'Check the mouth sores', result: 'White sores on the tongue: signs of an infection his body cannot clear.', value: 'useful' },
      { id: 't4', name: 'Review his weight record', result: 'Weight down by 12 kg over 8 months.', fact: 'loss', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Mild changes from the old infections. It does not explain why he cannot clear them.', value: 'risky' },
      { id: 't6', name: 'Allergy skin test', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'aids', name: 'Late-stage HIV infection (AIDS)', sub: 'The immune system is too damaged to cope with other infections' },
      { id: 'depression', name: 'Depression on its own', sub: 'Low mood causing tiredness and weight loss' },
      { id: 'type2', name: 'Type 2 diabetes', sub: 'Body cells no longer respond to insulin' },
    ],
    truth: 'aids', decisive: ['cells', 'stopped', 'infect', 'hivhx', 'ill', 'glu'],
    treatments: [
      { id: 'x1', label: 'Restart his antiretroviral drugs, treat the infections with the specific medicines they need, and arrange support for his low mood', verdict: 'best', why: 'Late-stage HIV (AIDS) means the immune system can no longer deal with other infections. **Antiretroviral drugs** control the virus. Severe physical illness can lead to **depression**, so his mood needs support as well.' },
      { id: 'x2', label: 'Treat the depression and send him home', verdict: 'harm', why: 'His low mood is real, but treating it alone ignores the cause of his illness. His immune system will keep failing.' },
      { id: 'x3', label: 'Start a carbohydrate-controlled diet and exercise plan for Type 2 diabetes', verdict: 'wrong', why: 'His blood glucose is normal and he has no diabetes symptoms.' },
      { id: 'x4', label: 'Restart the antiretroviral drugs but offer no mental health support', verdict: 'ok', why: 'The drugs are essential, but severe ill health leads to depression and untreated it makes it harder to keep taking the drugs.' },
    ],
    outcome: {
      right: 'Daniel restarted his drugs and the infections were treated. Within three months his immune cell count was recovering and his weight rising. With support from a counsellor and his sister, his mood lifted.',
      wrong: 'Daniel was given antidepressants only. Over the next months the infections returned and he was admitted to hospital with pneumonia, by which time his immune system was even weaker.',
    },
    twist: 'Low mood, tiredness and weight loss sound like **depression**, or even **diabetes**. But his blood glucose is normal, his **immune cell count is very low** and he **stopped his HIV drugs**: the infections came first and **the depression followed from the illness**. Read the lessons on **HIV** and on **interacting illnesses**.',
    lessons: ['hiv', 'interactions', 'diabetes'],
    spec: { board: 'AQA', code: '8461', refs: ['4.3.1.2 viral diseases (HIV and AIDS, antiretroviral drugs)', '4.2.2.5 health issues: how illnesses interact', '4.5.3.2 blood glucose and diabetes'] },
  });

  D.add({
    id: 'g10', track: 'gcse', rank: 4, minutes: 10,
    title: 'Penicillin from a friend', tagline: 'It stings, it will not clear, and the leftover tablets did nothing',
    complaint: 'Pain passing urine and a thick discharge for four days',
    patient: { name: 'Ethan Whitlock', age: 23, job: 'University student', setting: 'Sexual health clinic', image: P + 'g10.jpg',
      look: 'a twenty-three-year-old white man in a university hoodie with a nervous, embarrassed expression, sitting in a sexual health clinic consulting room' },
    opening: 'Ethan looks at the floor. He says he was too embarrassed to come sooner.',
    referral: 'Ethan has had **pain on urinating and a thick yellow-green discharge for four days**. He took **three days of leftover penicillin from a friend** and it made **no difference**. He had **unprotected sex about a week ago**.',
    obs: [['Temperature', '37.4 °C'], ['Pulse', '78 per minute'], ['Discharge', 'Thick, yellow-green'], ['Pain', 'Burning on urinating']],
    notes: ['Took leftover penicillin for three days, not all of it.', 'One new partner in the last month.', 'No cough, no sore throat, no flu-like illness.', 'Has not had a sexual health screen before.'],
    startFacts: ['discharge', 'pen'],
    facts: {
      discharge: 'Thick yellow-green discharge with pain on urinating', pen: 'Three days of penicillin made no difference', sex: 'He had unprotected sex about a week ago with a new partner',
      noflu: 'He has no fever, cough or flu-like illness', bacteria: 'The swab shows bacteria that cause gonorrhoea', resist: 'The bacteria grow in penicillin but are killed by a different antibiotic',
      nohiv: 'His HIV test is negative', partner: 'His partner has had no symptoms and has not been tested', incomplete: 'He took only part of the course of leftover penicillin',
      urine: 'A urine test for glucose is normal',
    },
    questions: [
      { id: 'q1', q: 'What are the symptoms and how long have you had them?', a: '**Burning when I pee** and a **thick yellowish-green discharge**. Four days.', fact: 'discharge' },
      { id: 'q2', q: 'Have you been taking anything for it?', a: 'A friend had **leftover penicillin**. I took it for three days and it did nothing.', fact: 'pen' },
      { id: 'q3', q: 'Have you had any recent sexual contact?', a: 'One new partner. We did not use a condom, about a week ago.', fact: 'sex' },
      { id: 'q4', q: 'Have you felt generally unwell, with a fever or aches?', a: 'No. Just the pain and the discharge. I feel fine otherwise.', fact: 'noflu' },
      { id: 'q5', q: 'Did you finish the tablets?', a: 'No, I stopped when they did nothing. There were only a few left anyway.', fact: 'incomplete' },
      { id: 'q6', q: 'Has your partner been unwell or tested?', a: 'She is fine as far as I know. We have not spoken since.', fact: 'partner' },
      { id: 'q7', q: 'Are you passing more urine than usual or very thirsty?', a: 'No, just the burning.', value: 'useful' },
      { id: 'q8', q: 'Do you have any allergies?', a: 'None.', value: 'useful' },
      { id: 'q9', q: 'What are you studying?', a: 'Economics.', value: 'waste' },
      { id: 'q10', q: 'Which hall do you live in?', a: 'Wentworth.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Swab, grown in the laboratory with different antibiotics', result: 'The bacteria that cause **gonorrhoea** grow even with **penicillin** but are killed by a **different antibiotic**: a **resistant strain**.', fact: 'resist', value: 'key' },
      { id: 't2', name: 'Look at the swab under the microscope', result: 'The sample shows the **bacteria that cause gonorrhoea**.', fact: 'bacteria', value: 'key' },
      { id: 't3', name: 'HIV test', note: 'Offered with any sexual health check', result: 'Negative.', fact: 'nohiv', value: 'useful' },
      { id: 't4', name: 'Urine test for glucose', result: 'Normal.', fact: 'urine', value: 'waste' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. It has no bearing on his symptoms.', value: 'risky' },
      { id: 't6', name: 'Allergy skin test', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'gonorrhoea', name: 'Gonorrhoea', sub: 'A sexually transmitted bacterial disease' },
      { id: 'hiv', name: 'Early HIV infection', sub: 'A flu-like illness caused by a virus' },
      { id: 'uti', name: 'A simple urine infection', sub: 'Bacteria in the urine that penicillin should clear' },
    ],
    truth: 'gonorrhoea', decisive: ['bacteria', 'resist', 'discharge', 'sex', 'pen', 'noflu'],
    treatments: [
      { id: 'x1', label: 'Treat with the antibiotic the laboratory test shows works, treat his partner too, and advise condoms and no sex until both are treated', verdict: 'best', why: 'Gonorrhoea is spread by sexual contact, so **both partners** need treatment, and a **barrier method** such as a condom controls the spread. **Specific bacteria need specific antibiotics**, and this strain is resistant to penicillin.' },
      { id: 'x2', label: 'Prescribe a longer course of penicillin', verdict: 'wrong', why: 'The bacteria are **resistant** to penicillin, so more of it will not work and helps resistance spread.' },
      { id: 'x3', label: 'Tell him it is a simple urine infection and to drink more water', verdict: 'harm', why: 'Untreated gonorrhoea can be passed to partners and cause serious problems. Water will not cure a bacterial infection.' },
      { id: 'x4', label: 'Treat him with the correct antibiotic, but say nothing about his partner', verdict: 'ok', why: 'He will be cured, but his partner may still have the infection and pass it back or on to others.' },
    ],
    outcome: {
      right: 'Ethan took the correct antibiotic and was cured within a week. His partner was contacted, tested and treated, and Ethan now uses condoms. He told his friend not to share leftover antibiotics.',
      wrong: 'Ethan took more penicillin without effect. The infection continued and was passed to his partner and then to others. A swab with antibiotic testing would have shown at once what to use.',
    },
    twist: 'A burning sensation sounds like a **simple urine infection**, and **penicillin** is the first thing anyone would try, but he took it and nothing changed. The bacteria are **resistant**, which is why the laboratory test of **which antibiotic works** matters. Read the **gonorrhoea** and **resistant bacteria** lessons.',
    lessons: ['gonorrhoea', 'resistance', 'antibiotics', 'hiv'],
    spec: { board: 'AQA', code: '8461', refs: ['4.3.1.3 bacterial diseases (gonorrhoea)', '4.6.3.7 resistant bacteria', '4.3.1.8 antibiotics and painkillers'] },
  });

  D.add({
    id: 'g11', track: 'gcse', rank: 4, minutes: 10,
    title: 'The wedding barbecue', tagline: 'Fourteen guests ill, and one dish to blame',
    complaint: 'Vomiting, diarrhoea and fever the day after a wedding',
    patient: { name: 'Chloe Barker', age: 24, job: 'Bridesmaid and dental nurse', setting: 'GP surgery, urgent appointment', image: P + 'g11.jpg',
      look: 'a twenty-four-year-old white woman with her hair still half-styled from a wedding, pale and clammy, wearing a crumpled pink dress under a coat, sitting in a doctor\'s surgery' },
    opening: 'Chloe is grey and shaky. She says she is the third guest from the wedding to see the doctor today.',
    referral: 'Chloe has had **vomiting, watery diarrhoea, stomach cramps and a fever since the early hours**. She was a bridesmaid at a wedding **yesterday with a barbecue for 40 guests**. The surgery has **seen two other guests** with the same symptoms.',
    obs: [['Temperature', '38.6 °C'], ['Pulse', '108 per minute'], ['Hydration', 'Dry mouth, sunken eyes'], ['Abdomen', 'Tender, with cramps']],
    notes: ['Symptoms began about 14 hours after the meal.', 'Two other guests have the same illness; the bride says several more are unwell.', 'Chloe ate chicken, salad and a slice of cake.', 'She is not pregnant. No known allergies.'],
    startFacts: ['symp', 'others'],
    facts: {
      symp: 'Vomiting, diarrhoea, cramps and fever starting about 14 hours after the meal', others: 'Other guests have the same illness',
      chicken: 'Everyone who is ill ate the barbecue chicken', veg: 'Guests who ate only the vegetarian dishes are well', undercooked: 'The chicken was pink in the middle when she ate it',
      kitchen: 'The same board and knife were used for raw chicken and the salad', stool: 'A stool sample grows Salmonella bacteria', noshell: 'She ate no shellfish and has no allergy history',
      hours: 'Symptoms came on many hours after eating, not within minutes', contact: 'Ill guests had no contact with each other apart from the meal',
    },
    questions: [
      { id: 'q1', q: 'What did you eat at the wedding?', a: '**Barbecue chicken**, a green salad, some bread and wedding cake.', fact: 'chicken' },
      { id: 'q2', q: 'How was the chicken?', a: 'Honestly, it was a bit **pink in the middle**. I ate it anyway because I was starving.', fact: 'undercooked' },
      { id: 'q3', q: 'When did you start to feel ill?', a: 'About **fourteen hours** after the meal, at around 4 a.m.', fact: 'hours' },
      { id: 'q4', q: 'Are other people ill too?', a: 'The bride\'s brother, my cousin, and about ten others are ill.', fact: 'others' },
      { id: 'q5', q: 'Did the guests who are ill all eat the same dishes?', a: 'All the ones I know about had the chicken. The vegetarians are all fine.', fact: 'veg' },
      { id: 'q6', q: 'How was the food prepared?', a: 'I helped in the kitchen. We used the same board for the raw chicken and the salad, and a quick wipe in between.', fact: 'kitchen' },
      { id: 'q7', q: 'Did you eat any shellfish or nuts, or have any reaction before?', a: 'No shellfish and no allergies.', fact: 'noshell' },
      { id: 'q8', q: 'Have you been in contact with anyone else who was ill?', a: 'Only the other guests, and only at the wedding.', fact: 'contact' },
      { id: 'q9', q: 'How many guests were at the wedding?', a: 'Forty, plus the staff.', value: 'useful' },
      { id: 'q10', q: 'What colour was the wedding cake?', a: 'White, with raspberries.', value: 'waste' },
      { id: 'q11', q: 'What song did the couple dance to?', a: 'Can we not do this now?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Stool sample grown in the laboratory', result: 'The sample grows **Salmonella** bacteria.', fact: 'stool', value: 'key' },
      { id: 't2', name: 'List what each ill guest ate', note: 'Helps find the source', result: 'Every ill guest ate the **barbecue chicken**. No one who only had vegetarian dishes is ill.', fact: 'chicken', value: 'key' },
      { id: 't3', name: 'Check the caterer\'s kitchen', result: 'The same board and knife were used for **raw chicken and salad**, and the chicken was undercooked.', fact: 'kitchen', value: 'useful' },
      { id: 't4', name: 'Check her hydration', result: 'She is **dehydrated** from fluid loss.', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Normal. No reason for it.', value: 'risky' },
      { id: 't6', name: 'Allergy skin test', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'salmonella', name: 'Salmonella food poisoning', sub: 'A bacterial disease from food' },
      { id: 'virus', name: 'A virus spreading from person to person', sub: 'A viral stomach illness' },
      { id: 'allergy', name: 'An allergic reaction to food', sub: 'An immune reaction within minutes' },
    ],
    truth: 'salmonella', decisive: ['stool', 'chicken', 'veg', 'undercooked', 'hours', 'kitchen', 'contact'],
    treatments: [
      { id: 'x1', label: 'Rehydrate her, keep ill food handlers away from food, report the outbreak so the source can be traced, and advise thorough cooking and separate boards', verdict: 'best', why: 'Salmonella is spread by **bacteria in food or unhygienic preparation**, so controlling it means removing the source and keeping the ill away from handling food. Fluids replace what she has lost.' },
      { id: 'x2', label: 'Give antibiotics to every guest as a precaution and say nothing more', verdict: 'ok', why: 'Antibiotics kill bacteria, but treating well people is wasteful and encourages resistance, and it does nothing to find and stop the source.' },
      { id: 'x3', label: 'Give her an antihistamine and tell her to rest', verdict: 'wrong', why: 'This is not an allergic reaction: it started 14 hours after the meal, with fever, and a stool sample grew bacteria.' },
      { id: 'x4', label: 'Tell her it will pass and the caterer can carry on as normal', verdict: 'harm', why: 'The caterer would carry on preparing food in the same way and more people would be poisoned.' },
    ],
    outcome: {
      right: 'Chloe recovered after three days with fluids. The caterer\'s kitchen was inspected and changed its practices, and the other 14 guests recovered without complication.',
      wrong: 'The caterer carried on, and another wedding party became ill the following weekend. The link had been plain: every ill guest had eaten the chicken.',
    },
    twist: 'Several people with vomiting and diarrhoea could be a **virus** passing between guests, or an **allergy**. But the illness started **many hours** after the meal, **only the chicken-eaters** are ill and the stool sample grew **Salmonella**. Read the **salmonella** lesson.',
    lessons: ['salmonella', 'pathogens', 'allergy', 'antibiotics'],
    spec: { board: 'AQA', code: '8461', refs: ['4.3.1.3 bacterial diseases (Salmonella)', '4.3.1.1 communicable diseases (spread and its prevention)', '4.2.2.5 health issues (allergies)'] },
  });

  D.add({
    id: 'g12', track: 'gcse', rank: 4, minutes: 10,
    title: 'Swollen ankles, short of breath', tagline: 'It looks like the heart. Is it?',
    complaint: 'Swollen ankles, breathlessness and tiredness, with very little urine',
    patient: { name: 'Rosa Fernandes', age: 45, job: 'Hairdresser', setting: 'Medical admissions unit', image: P + 'g12.jpg',
      look: 'a forty-five-year-old Portuguese-British woman with shoulder-length dark hair, puffy ankles visible, pale and tired, sitting up on a hospital bed in a gown, breathing a little heavily' },
    opening: 'Rosa slides her slippers off to show swollen ankles, and says her shoes will not fit.',
    referral: 'Rosa has had **swollen ankles, breathlessness, tiredness and nausea for two weeks**, and has been passing **very little urine**. Her GP suspected **heart failure** because of the swelling and breathlessness.',
    obs: [['Blood pressure', '168 / 102'], ['Pulse', '84 per minute'], ['Weight', '6 kg heavier than a month ago'], ['Ankles', 'Swollen, pitting']],
    notes: ['Long-standing high blood pressure, poorly controlled.', 'No chest pain. Her heart sounds normal.', 'Passes only a small amount of dark urine.', 'Her mother needed dialysis in her sixties.'],
    startFacts: ['ankles', 'bp'],
    facts: {
      ankles: 'Swollen ankles and 6 kg of fluid gained in a month', bp: 'Blood pressure is high at 168 / 102',
      littleurine: 'She passes very little urine, dark in colour', heartok: 'Her heart sounds and heart tracing are normal', urea: 'Her blood urea is very high',
      fam: 'Her mother needed dialysis', tired: 'She is tired and feels sick, with a metallic taste in her mouth', lungs: 'No wheeze or lung disease',
      nochest: 'No chest pain or palpitations', sodiumwater: 'She is retaining water that her body is not removing',
    },
    questions: [
      { id: 'q1', q: 'How much urine are you passing?', a: '**Hardly any**, and it is dark. A tiny amount a few times a day.', fact: 'littleurine' },
      { id: 'q2', q: 'When did the swelling start?', a: 'About two weeks ago, in the ankles, and now my face feels puffy too. I have put on **six kilos** of water.', fact: 'ankles' },
      { id: 'q3', q: 'Do you have chest pain or palpitations?', a: 'No, nothing like that. My heart seems fine.', fact: 'nochest' },
      { id: 'q4', q: 'How is your energy and appetite?', a: 'Terrible. I am **exhausted and feel sick**, and food tastes metallic.', fact: 'tired' },
      { id: 'q5', q: 'Is there kidney disease in your family?', a: 'My mother was on dialysis for years.', fact: 'fam' },
      { id: 'q6', q: 'Have you any breathing problems like wheeze or a cough?', a: 'No wheeze, no cough. I am breathless when I lie flat, and when I walk because of the fluid.', fact: 'lungs' },
      { id: 'q7', q: 'How is your blood pressure usually?', a: 'High for years. I do not always take my tablets.', value: 'useful' },
      { id: 'q8', q: 'Do you drink a lot of water?', a: 'Normal. Maybe a bit less recently because I feel sick.', value: 'useful' },
      { id: 'q9', q: 'Where do you work?', a: 'A salon in town.', value: 'waste' },
      { id: 'q10', q: 'What is your favourite hair colour to do?', a: 'Copper. I love copper.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Blood test for urea', note: 'Urea is normally removed by the kidneys', result: 'Her blood urea is **very high**: her kidneys are not removing it.', fact: 'urea', value: 'key' },
      { id: 't2', name: 'Measure and record the urine she passes', result: 'She passes only **a small amount of dark urine** in 24 hours.', fact: 'littleurine', value: 'key' },
      { id: 't3', name: 'Listen to the heart and record a heart tracing', result: 'Heart sounds and the heart tracing are **normal**: no sign of heart failure.', fact: 'heartok', value: 'useful' },
      { id: 't4', name: 'Check her weight against last month', result: '**6 kg heavier**: fluid is building up.', value: 'useful' },
      { id: 't5', name: 'Chest X-ray', note: 'Uses radiation', result: 'Shows some fluid, but it does not show where the fluid is coming from.', value: 'risky' },
      { id: 't6', name: 'Throat swab', result: 'Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'kidney', name: 'Kidney failure', sub: 'The kidneys are not removing urea or water' },
      { id: 'heart', name: 'Heart failure', sub: 'The heart is not pumping enough blood' },
      { id: 'lung', name: 'A lung problem', sub: 'Breathlessness from damaged lungs' },
    ],
    truth: 'kidney', decisive: ['urea', 'littleurine', 'heartok', 'fam', 'tired', 'lungs'],
    treatments: [
      { id: 'x1', label: 'Start kidney dialysis now to remove urea and excess fluid, and assess her for a kidney transplant', verdict: 'best', why: 'Her kidneys have failed. **Dialysis** removes urea and excess ions and water through a partially permeable membrane, and a **transplant** could restore normal kidney function, though she would need **drugs to stop rejection** and a suitable donor.' },
      { id: 'x2', label: 'Refer her for a heart transplant', verdict: 'harm', why: 'Her heart is normal. A heart transplant would be a major operation with no benefit.' },
      { id: 'x3', label: 'Tell her to drink more water to flush her system out', verdict: 'wrong', why: 'Her kidneys cannot remove water, so extra water would make the swelling and breathlessness worse.' },
      { id: 'x4', label: 'Start dialysis but make no plan for a transplant', verdict: 'ok', why: 'Dialysis is right for now, but it is an ongoing burden of several sessions a week. A transplant may offer a better long-term outcome.' },
    ],
    outcome: {
      right: 'Rosa started dialysis that week and the swelling and sickness eased. She was assessed for a transplant and her sister, a close match, volunteered to donate.',
      wrong: 'Rosa was treated for heart failure for a fortnight and became sicker as waste products built up. When her kidney failure was found she needed emergency dialysis.',
    },
    twist: 'Swollen ankles and breathlessness are the classic signs of **heart failure**, so the heart tests look like the obvious next step. But **her heart is normal**, she passes **very little urine** and her **blood urea is very high**: this is **kidney failure**. Read the **kidney failure and dialysis** lesson.',
    lessons: ['dialysis', 'waterbalance', 'chd'],
    spec: { board: 'AQA', code: '8461', refs: ['4.5.3.3 maintaining water and nitrogen balance (kidney failure, dialysis, transplant)', '4.2.2.4 treating organ failure (heart failure, transplant)', '4.1.3.2 osmosis'] },
  });
})(typeof window !== 'undefined' ? window : globalThis);
