/* Psychology Career: A-level cases (AQA 7182), part two. See cases-psych.js. */
(function (root) {
  var D = root.DOCTOR = root.DOCTOR || {}; D.cases = D.cases || [];
  var P = '/assets/psych/';

  D.add({
    id: 'p06', track: 'psych', rank: 2, minutes: 10,
    title: 'Never off', tagline: 'Headaches, colds and a racing heart in a call centre',
    complaint: 'Constant colds, headaches, chest tightness and exhaustion, mostly on weekdays',
    patient: { name: 'Fiona McAllister', age: 38, job: 'Call centre team leader', setting: 'Occupational health clinic', image: P + 'p06.jpg',
      look: 'a thirty-eight-year-old white woman with a neat auburn bob, wearing a blouse and a company lanyard, looking pale and tired with shadows under her eyes, sitting in an occupational health room with a laptop bag at her feet' },
    opening: 'Fiona checks her phone twice before she begins, then apologises.',
    referral: 'Sent by her employer. Over **the last year** Fiona has had **frequent colds, headaches, a racing heart and tightness in her chest**. She has taken **time off sick** several times. Her GP found nothing wrong with her heart and wondered whether she is **depressed**.',
    obs: [['Appearance', 'Pale, tense'], ['Pulse', '96 per minute, regular'], ['Blood pressure', '150 / 95'], ['Sleep', 'Light, wakes with work on her mind']],
    notes: ['Back-to-back calls, with targets raised twice this year.', 'Two colleagues left and have not been replaced.', 'Frequent colds and a slow-healing cut on her hand.', 'ECG normal. No heart condition found.'],
    startFacts: ['phys', 'ecg'],
    facts: {
      phys: 'She has frequent colds, headaches and a racing heart', ecg: 'Her ECG and heart tests are normal',
      workload: 'Her workload has risen sharply: targets have been raised and two colleagues have not been replaced', control: 'She has little say over her schedule, targets or how she does her job',
      better: 'Her symptoms ease at weekends and on holiday', mood: 'Her mood is good when she is away from work, and she enjoys things then',
      cold: 'She has frequent colds and a cut on her hand that has been slow to heal', typeA: 'She is competitive, always rushing and finds it hard to relax',
      bp: 'Her blood pressure is raised', sleep: 'Her sleep is light and full of work worries', nolow: 'She does not feel worthless or hopeless',
    },
    questions: [
      { id: 'q1', q: 'When are your symptoms worst?', a: 'Sunday night through Friday. On **holiday** last month I felt like a different person.', fact: 'better' },
      { id: 'q2', q: 'What has changed at work?', a: 'Targets went up twice. **Two people left** and they have not been replaced. I cover **three jobs**.', fact: 'workload' },
      { id: 'q3', q: 'How much say do you have over how you work?', a: 'Hardly any. The schedule is set, my calls are timed, every break is monitored.', fact: 'control' },
      { id: 'q4', q: 'How is your mood outside work?', a: 'Fine, honestly. At weekends I am happy. I do not feel hopeless.', fact: 'mood' },
      { id: 'q5', q: 'How often are you ill?', a: 'I have had **five colds** this year, and a cut on my hand that took two months to heal.', fact: 'cold' },
      { id: 'q6', q: 'How would you describe yourself?', a: 'Driven. I hate waiting. I am always doing three things at once. I do not know how to switch off.', fact: 'typeA' },
      { id: 'q7', q: 'How are you sleeping?', a: 'Light. I wake at 3 and go through tomorrow\'s calls.', fact: 'sleep' },
      { id: 'q8', q: 'Do you ever feel worthless?', a: 'No. I feel **overloaded**, not worthless.', fact: 'nolow' },
      { id: 'q9', q: 'Have you told your manager how you feel?', a: 'I said I was struggling. I was told everyone is.', value: 'useful' },
      { id: 'q10', q: 'Do you have any hobbies?', a: 'I used to run. I have not had the energy.', value: 'useful' },
      { id: 'q11', q: 'What was your first job?', a: 'A paper round. Why?', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Ask her to compare symptoms during work and during leave', value: 'key', fact: 'better', result: 'Her symptoms **fade within days** of leave and **return** when she is back at work, which **points to the job** as the cause.' },
      { id: 't2', name: 'Workplace stress assessment (workload and control)', value: 'key', fact: 'control', result: '**High workload**, **low control**: the same combination that **Johansson** and **Marmot** linked to **stress and heart disease**.' },
      { id: 't3', name: 'Depression questionnaire', value: 'useful', fact: 'nolow', result: 'A **low** score. Low mood, worthlessness and hopelessness are **not** present.' },
      { id: 't4', name: 'Check blood pressure, pulse and stress hormones', value: 'useful', fact: 'bp', result: 'Blood pressure and cortisol are **raised**, consistent with **a long period of stress**.' },
      { id: 't5', name: 'Cardiac MRI', note: 'Expensive', result: 'Normal. The ECG had already shown no heart problem.', value: 'waste' },
      { id: 't6', name: 'Test for HIV', result: 'No reason for it. Irrelevant.', value: 'waste' },
    ],
    options: [
      { id: 'stress', name: 'Work-related stress', sub: 'Heavy workload and low control' },
      { id: 'dep', name: 'Depression', sub: 'Persistent low mood and negative thinking' },
      { id: 'heart', name: 'A heart condition', sub: 'Chest tightness and a racing heart' },
    ],
    truth: 'stress', decisive: ['workload', 'control', 'better', 'mood', 'ecg'],
    treatments: [
      { id: 'x1', label: 'Stress inoculation training for her, and a meeting with her employer about workload and control', verdict: 'best', why: '**Stress inoculation training (Meichenbaum)** teaches her to **understand her stress**, **learn and rehearse coping skills**, and **apply** them. Dealing with **workload and control** removes the **source**.' },
      { id: 'x2', label: 'A short course of benzodiazepines while the other changes are made', verdict: 'ok', why: '**Benzodiazepines** (which **enhance GABA**) can **calm** her in the short term, but **do not remove the cause**, and are for **short-term** use only.' },
      { id: 'x3', label: 'Start an antidepressant for depression', verdict: 'wrong', why: 'Her **mood is fine** away from work. This is **stress**, not depression.' },
      { id: 'x4', label: 'A long course of benzodiazepines and carry on as she is', verdict: 'harm', why: 'Long-term use risks **tolerance and dependence**, and the **cause remains**, so the **HPA axis stays active** and her **immune system** stays suppressed.' },
    ],
    outcome: {
      right: 'Fiona learned to catch her thoughts and slow her breathing, and her manager agreed to share the calls and review the targets. After three months her blood pressure was normal and she had not had a cold since the spring.',
      wrong: 'Fiona was treated for depression and carried on as before. Within a year she had been signed off with heart palpitations that no scan could explain.',
    },
    twist: 'Exhaustion, poor sleep and constant illness sound like **depression**, and chest tightness sounds like a **heart problem**. But Fiona\'s **mood is good** away from work, her **heart tests are normal**, and her symptoms **follow the working week**, with a **high workload** and **low control**. This is **stress**, with **cortisol** suppressing her **immune system**.',
    lessons: ['p-stress-body', 'p-stress-sources', 'p-stress-manage', 'p-depression'],
    spec: { board: 'AQA', code: '7182', refs: ['Stress: SAM and HPA, and stress and illness', 'Stress: workplace stress (workload and control)', 'Stress: personality types and hardiness', 'Stress: stress inoculation training and drugs'] },
  });

  D.add({
    id: 'p07', track: 'psych', rank: 3, minutes: 10,
    title: 'Off the tablets', tagline: 'Well for two years, until the side effects got too much',
    complaint: 'The voices have come back, three weeks after he stopped his medication',
    patient: { name: 'Gareth Pryce', age: 36, job: 'Delivery driver', setting: 'Community mental health team', image: P + 'p07.jpg',
      look: 'a thirty-six-year-old white man with a heavy build and short sandy hair, in a casual jacket, looking restless and slightly puffy-faced, sitting on the edge of a chair in a clinic room with his wife beside him' },
    opening: 'Gareth\'s wife speaks first. "He has been fine for two years. I do not know what has gone wrong."',
    referral: 'Referred urgently by his wife. Gareth has **schizophrenia**, diagnosed eight years ago, and has been **well for two years** on an antipsychotic. Three weeks ago he **stopped taking it**. For the last **ten days** he has been **hearing voices again** and thinks his van is being **bugged**. His wife is worried it is her family: **her mother visits often and criticises him**.',
    obs: [['Appearance', 'Restless, a slight tremor'], ['Weight', 'Up 14 kg in two years'], ['Speech', 'Fast, guarded'], ['Medication', 'Stopped three weeks ago']],
    notes: ['Schizophrenia, stable for two years on regular medication.', 'Complained of drowsiness, shaking, weight gain and a lack of feeling.', 'Stopped medication without telling anyone.', 'Voices and suspicion returned about a week later.'],
    startFacts: ['stopped', 'back'],
    facts: {
      stopped: 'He stopped taking his antipsychotic three weeks ago', back: 'The voices and suspicion returned about a week after he stopped',
      side: 'He stopped because of side effects: drowsiness, tremor, weight gain and feeling numb', same: 'The symptoms are the same as in his earlier illness',
      calm: 'His family home is warm and supportive and his wife does not criticise him', mother: 'His mother-in-law visits and sometimes comments, but he describes it as mild',
      stress: 'There has been no new major stress at work or home', mood: 'His mood is not low', drug: 'He has taken no other drugs and drinks little',
      well: 'He was well for two years while on his tablets', dose: 'His dose was unchanged until he stopped',
    },
    questions: [
      { id: 'q1', q: 'When did you stop your tablets?', a: 'Three weeks ago. I **just stopped**. I could not stand the shaking and the weight. I felt like a zombie.', fact: 'stopped' },
      { id: 'q2', q: 'When did the voices come back?', a: 'About a week after. Slowly, then **louder**. They are the same ones as before.', fact: 'back' },
      { id: 'q3', q: 'Why did you stop?', a: 'The **side effects**. Fourteen kilos. My hands shake. I wanted to feel like me.', fact: 'side' },
      { id: 'q4', q: 'Is this like your earlier illness?', a: 'Exactly the same. The voices, the feeling that I am being watched.', fact: 'same' },
      { id: 'q5', q: 'How are things at home?', a: 'Good. My wife is **brilliant**. She does not nag. We are fine.', fact: 'calm' },
      { id: 'q6', q: 'What about your wife\'s mother?', a: 'She calls round on Sundays. She says things, but I do not take it to heart.', fact: 'mother' },
      { id: 'q7', q: 'Has anything stressful happened lately?', a: 'No. Work is quiet. We have no money worries.', fact: 'stress' },
      { id: 'q8', q: 'How is your mood?', a: 'Fine. I am not sad. I just want the voices to stop.', fact: 'mood' },
      { id: 'q9', q: 'Have you taken any other drugs or drunk more than usual?', a: 'No. Not since I was a student.', fact: 'drug' },
      { id: 'q10', q: 'How were you before you stopped?', a: 'Well. For two years I was working full time. I forgot I was ill.', fact: 'well' },
      { id: 'q11', q: 'What do you listen to in the van?', a: 'Talk radio.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Review his medication record and ask when he stopped', value: 'key', fact: 'stopped', result: 'The pharmacy shows **no repeat collected** for three weeks. The **voices began about a week later**, as the drug cleared his system.' },
      { id: 't2', name: 'Assess the family climate (expressed emotion) with his wife', value: 'key', fact: 'calm', result: '**Low expressed emotion**: his wife is **warm, patient and uncritical**. There is **no hostility or over-involvement**.' },
      { id: 't3', name: 'Clinical interview about current symptoms', value: 'useful', fact: 'same', result: '**Hallucinations and delusions**, the same as before, with **no low mood**.' },
      { id: 't4', name: 'Ask about side effects', value: 'useful', fact: 'side', result: 'Tremor, drowsiness and **weight gain** from his drug. These are the reasons he stopped.' },
      { id: 't5', name: 'MRI scan', note: 'Expensive and not needed', result: 'No change from his old scans. It would not alter the plan.', value: 'waste' },
      { id: 't6', name: 'Test for cannabis and other drugs', result: 'Negative.', value: 'useful', fact: 'drug' },
    ],
    options: [
      { id: 'med', name: 'A relapse after stopping his antipsychotic', sub: 'Dopamine activity returns when the drug stops blocking it' },
      { id: 'ee', name: 'A relapse caused by high expressed emotion at home', sub: 'Criticism and hostility from the family' },
      { id: 'dep', name: 'A new episode of depression', sub: 'Low mood and withdrawal' },
    ],
    truth: 'med', decisive: ['stopped', 'back', 'calm', 'same', 'well'],
    treatments: [
      { id: 'x1', label: 'Restart an antipsychotic, switching to one with fewer side effects, with monitoring', verdict: 'best', why: 'Antipsychotics **block dopamine**, which is why symptoms **returned when he stopped**. An **atypical** drug such as clozapine may cause fewer movement side effects but needs **blood tests**. **Side effects** are the real reason to change, since they led to him stopping.' },
      { id: 'x2', label: 'Restart the same drug and add family therapy and CBT', verdict: 'ok', why: 'The drug is right, and CBT and family therapy help, but **the side effects** that caused him to stop are not addressed.' },
      { id: 'x3', label: 'Treat the family with therapy to reduce expressed emotion, and no drug', verdict: 'wrong', why: 'The family climate is **warm**. The **trigger** was stopping the drug. Therapy alone cannot replace the **dopamine blockade**.' },
      { id: 'x4', label: 'Stop all medication permanently because of the side effects', verdict: 'harm', why: 'Without medication the **relapse** will continue, and **repeated relapses** make recovery harder.' },
    ],
    outcome: {
      right: 'Gareth moved to a different antipsychotic with fewer side effects and agreed monthly checks. Within three weeks the voices had settled, and he was back at work within the month.',
      wrong: 'Gareth\'s plan did not tackle the real cause. The voices continued, he was admitted to hospital within a fortnight, and it took a year to rebuild the trust with his team.',
    },
    twist: 'The wife\'s mother is a **red herring**: **high expressed emotion** is linked to **relapse**, so it sounds like the cause. But the **family climate is warm**, the symptoms began **a week after he stopped his drug**, and they are **the same as before**. The **dopamine hypothesis** and the effect of **antipsychotics** explain it.',
    lessons: ['p-schiz-bio', 'p-schiz-psych', 'p-schiz-treat'],
    spec: { board: 'AQA', code: '7182', refs: ['Schizophrenia: the dopamine hypothesis', 'Schizophrenia: family dysfunction and expressed emotion', 'Schizophrenia: antipsychotics, CBT and family therapy'] },
  });

  D.add({
    id: 'p08', track: 'psych', rank: 3, minutes: 10,
    title: 'A perfect daughter', tagline: 'Top of the class, careful with every crumb',
    complaint: 'Eating very little, losing weight and spending hours on food rituals',
    patient: { name: 'Isla Brennan', age: 16, job: 'Sixth-form student', setting: 'Child and adolescent eating disorders service', image: P + 'p08.jpg',
      look: 'a sixteen-year-old white girl with long fair hair in a plain school jumper that is too big for her, looking thin and pale and quietly composed, sitting beside her mother in a calm clinic room' },
    opening: 'Isla answers politely and calmly. Her mother answers first, every time.',
    referral: 'Referred by her school nurse. Isla has **lost 9 kg in four months** and her **periods have stopped**. She cuts her food into very small pieces and **weighs it**. She says she is **"too big"**. Her mother says she is a **perfect daughter** who **never argues**. Her GP asks whether this is **OCD** or **depression**.',
    obs: [['Weight', '41 kg'], ['BMI', '16'], ['Pulse', '48 per minute'], ['Periods', 'Stopped three months ago']],
    notes: ['Restricts food, weighs everything and counts calories.', 'Believes she is overweight, despite being underweight.', 'Very high achiever and a perfectionist.', 'Close, controlling relationship with her mother; her parents rarely argue.'],
    startFacts: ['bmi', 'restrict'],
    facts: {
      bmi: 'Her BMI is 16, which is dangerously low', restrict: 'She restricts her food and weighs everything she eats',
      fear: 'She has an intense fear of gaining weight', image: 'She sees herself as "huge" when she is clearly underweight', periods: 'Her periods have stopped',
      only: 'Her rituals are only about food and weight, not about anything else', family: 'Her family is very close and her mother is controlling and overprotective; conflicts are never discussed',
      perfect: 'She is a perfectionist and a high achiever', media: 'She follows social media accounts that praise being thin and has copied their diets',
      mood: 'Her mood is low at times, but she says it is because she is afraid of getting fat', rigid: 'Her family is rigid about routines, and avoids all open conflict',
    },
    questions: [
      { id: 'q1', q: 'How do you feel about your body?', a: 'I am **huge**. Everyone can see it. I know people say I am thin, but they do not understand.', fact: 'image' },
      { id: 'q2', q: 'What are you most afraid of?', a: 'Putting on weight. I think about it all day. If I eat I will **lose control** and not stop.', fact: 'fear' },
      { id: 'q3', q: 'What do you do with your food?', a: 'I weigh it. I cut it small. I count. I have a **limit** for each day, and I never go over.', fact: 'restrict' },
      { id: 'q4', q: 'Do you have any other habits you cannot stop?', a: 'No. Only with food. I am not like that about anything else.', fact: 'only' },
      { id: 'q5', q: 'Tell me about your family.', a: 'We are very close. Mum organises everything. We **never argue**. Dad and Mum are tense but we do not talk about it.', fact: 'family' },
      { id: 'q6', q: 'How do you cope with school?', a: 'I need to be the best. If I get a B, I cannot sleep. I always have to be perfect.', fact: 'perfect' },
      { id: 'q7', q: 'Where do you get ideas about food and weight?', a: 'Instagram. There are girls who post their meals. They look so **in control**. I follow them.', fact: 'media' },
      { id: 'q8', q: 'How is your mood?', a: 'Sometimes low. But that is because I am scared of getting fat, not the other way round.', fact: 'mood' },
      { id: 'q9', q: 'Are your periods regular?', a: 'They stopped in the summer.', fact: 'periods' },
      { id: 'q10', q: 'How is your sleep?', a: 'Not great. I am often cold and hungry.', value: 'useful' },
      { id: 'q11', q: 'What is your favourite subject?', a: 'Maths.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Weigh her and calculate her BMI', value: 'key', fact: 'bmi', result: 'Weight **41 kg**, BMI **16**: **well below** a healthy range.' },
      { id: 't2', name: 'Interview about body image and fear of weight gain', value: 'key', fact: 'image', result: 'A **distorted body image** and an **intense fear of gaining weight**. The rituals are **only around food and weight**.' },
      { id: 't3', name: 'Family interview', value: 'useful', fact: 'family', result: 'An **enmeshed** and **overprotective** family that **avoids open conflict**, with **tension** between the parents that is never discussed.' },
      { id: 't4', name: 'ECG and blood tests', note: 'To check the effects on her body', value: 'useful', fact: 'periods', result: 'A **slow heart rate** and **hormone levels** consistent with **stopped periods**.' },
      { id: 't5', name: 'Brain MRI scan', result: 'Normal. It would not distinguish between the possibilities.', value: 'waste' },
      { id: 't6', name: 'Test for thyroid disease', result: 'Normal. Her signs have a clear cause.', value: 'waste' },
    ],
    options: [
      { id: 'an', name: 'Anorexia nervosa', sub: 'Restricting food, fear of weight gain, distorted body image' },
      { id: 'ocd', name: 'OCD', sub: 'Obsessions and compulsions about many things' },
      { id: 'dep', name: 'Depression', sub: 'Low mood, loss of appetite' },
    ],
    truth: 'an', decisive: ['bmi', 'fear', 'image', 'only', 'restrict'],
    treatments: [
      { id: 'x1', label: 'Family therapy: work with Isla and her parents on control, boundaries and open conflict', verdict: 'best', why: '**Family systems theory (Minuchin)** sees anorexia as a **symptom of a faulty family system** (**enmeshment, overprotection, rigidity, avoiding conflict**). Treating the **system** removes the need for her illness.' },
      { id: 'x2', label: 'CBT to challenge her distorted body image and all-or-nothing thinking', verdict: 'ok', why: 'The **cognitive** explanation points to **distorted thinking**, and CBT helps with that. But the **family pattern** will go on, so CBT alone is less complete.' },
      { id: 'x3', label: 'An SSRI alone, and reassure her mother', verdict: 'wrong', why: 'Her low mood is a **result** of the **weight loss**. A drug alone does not tackle the **thinking or the family system**.' },
      { id: 'x4', label: 'Tell her to eat more and send her home', verdict: 'harm', why: 'Telling a person with anorexia simply to eat misses the **fear and distorted thinking**, and her **physical state** is dangerous.' },
    ],
    outcome: {
      right: 'Isla and her parents attended family sessions together for six months. Her mother learned to step back, her parents began to talk about their own problems, and Isla\'s weight returned to a healthy range.',
      wrong: 'Isla\'s weight fell further and she was admitted to hospital within two months. The family pattern had not changed.',
    },
    twist: 'Rigid food rituals and perfectionism sound like **OCD**, and low mood sounds like **depression**. But Isla\'s rituals are **only about food and weight**, driven by a **fear of weight gain** and a **distorted body image**, with a **dangerously low BMI**. Her low mood **follows** the weight loss. That is **anorexia nervosa**.',
    lessons: ['p-eating', 'p-ocd', 'p-depression'],
    spec: { board: 'AQA', code: '7182', refs: ['Eating behaviour: anorexia nervosa (genetic and neural explanations)', 'Eating behaviour: family systems, social learning and cognitive explanations', 'Psychopathology: OCD and depression compared'] },
  });

  D.add({
    id: 'p09', track: 'psych', rank: 4, minutes: 10,
    title: 'A voice in the chapel', tagline: 'Hospital notes say schizophrenia. The congregation says otherwise.',
    complaint: 'Hears his late mother speak to him during prayer, and was diagnosed after mentioning it to a doctor',
    patient: { name: 'Winston Clarke', age: 47, job: 'Bus driver and church deacon', setting: 'Community mental health team', image: P + 'p09.jpg',
      look: 'a forty-seven-year-old Black British man of Jamaican heritage, in a smart dark suit and tie with a small church lapel badge, calm, composed and dignified, sitting upright in a clinic consulting room with his hands resting on his knees' },
    opening: 'Winston greets you politely, and says he would like to understand why he has been sent.',
    referral: 'Referred for a **second opinion**. Winston told a locum GP that he **hears the voice of his late mother** when he prays. The GP recorded **"hallucinations: probable schizophrenia"** and referred him. Winston is **puzzled and upset**. He has **worked as a bus driver for 22 years**, is a **deacon**, and has **never had a mental health problem**.',
    obs: [['Appearance', 'Neat, well groomed'], ['Speech', 'Clear, measured and fluent'], ['Mood (his words)', '"Content. Confused about why I am here."'], ['Work', '22 years, no absences']],
    notes: ['Hears his late mother\'s voice during prayer at his church.', 'Others in the congregation describe similar experiences.', 'No other unusual experiences, and no distress.', 'Functions fully at work, at home and in the community.'],
    startFacts: ['voice', 'fine'],
    facts: {
      voice: 'He hears his late mother\'s comforting voice when he prays', fine: 'He works full time, runs his home and leads at church with no difficulty',
      culture: 'The experience is accepted and valued in his church, and others there describe the same', distress: 'It does not distress him; he finds it comforting',
      only: 'It only happens during prayer or worship, never at other times', nodel: 'He has no delusions or fixed false beliefs outside his faith',
      neg: 'He has no negative symptoms: his speech is full and he is motivated', never: 'He has never had any mental health problem in his life',
      ground: 'The diagnosis came from a single short appointment with a doctor who did not ask about his culture', stat: 'People of Afro-Caribbean origin in the UK are diagnosed with schizophrenia far more often than white people',
      insight: 'He understands the difference between his prayer experience and real events',
    },
    questions: [
      { id: 'q1', q: 'Tell me about the voice you hear.', a: 'It is my **mother**. She died in 2011. I hear her when I pray. She says "I am proud of you." It is a **comfort**.', fact: 'voice' },
      { id: 'q2', q: 'Does it distress you?', a: 'Not at all. I would be sad if it stopped. It is a **blessing**.', fact: 'distress' },
      { id: 'q3', q: 'Do other people at your church have the same experience?', a: 'Many. **Sister Hall** hears her husband. It is part of our worship. We call it being **visited**.', fact: 'culture' },
      { id: 'q4', q: 'When does it happen?', a: 'Only in the **chapel** or when I pray at home. Never on the bus. Never at work.', fact: 'only' },
      { id: 'q5', q: 'How do you manage your daily life?', a: 'I have driven the 52 for twenty-two years. I run my home. I lead the Sunday service.', fact: 'fine' },
      { id: 'q6', q: 'Do you hold any beliefs that others find strange?', a: 'My faith, which many people share. Otherwise no. I am the same man I always was.', fact: 'nodel' },
      { id: 'q7', q: 'Have you ever had a mental health problem before?', a: 'Never. Not once. I do not even have a history of low mood.', fact: 'never' },
      { id: 'q8', q: 'How long did the appointment with the first doctor last?', a: 'Five minutes. She did not ask about my church. She wrote "hallucinations".', fact: 'ground' },
      { id: 'q9', q: 'Do you understand the difference between these experiences and real life?', a: 'Of course. I know what is prayer and what is the road.', fact: 'insight' },
      { id: 'q10', q: 'How is your sleep and your appetite?', a: 'Normal. I am a bus driver, I need my sleep.', value: 'useful' },
      { id: 'q11', q: 'What route do you drive?', a: 'The 52, from the station to the hospital.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Culturally informed interview about the experience', note: 'Ask about his faith, his community and what the experience means to him', value: 'key', fact: 'culture', result: 'The experience is **normal within his community**, is **valued**, and **happens only in worship**. It has **no other features** of a psychotic illness.' },
      { id: 't2', name: 'Assess his ability to function and any distress', value: 'key', fact: 'fine', result: 'He is **fully functioning**, with **no distress** and **no impairment** at work, at home or in the community.' },
      { id: 't3', name: 'Screen for other symptoms: delusions, negative symptoms, thought disorder', value: 'key', fact: 'nodel', result: '**No delusions**, **no negative symptoms**, and his speech and thinking are **well organised**.' },
      { id: 't4', name: 'Collateral from his church minister and family', value: 'useful', fact: 'never', result: 'Both describe **no change in behaviour** and no earlier problems. The minister says the experience is **common and understood**.' },
      { id: 't5', name: 'Brain scan to look for schizophrenia', note: 'There is no brain scan that diagnoses it', result: 'Normal. It cannot confirm or exclude the diagnosis.', value: 'waste' },
      { id: 't6', name: 'Compulsory admission for observation', note: 'Detaining a well man', result: 'Unnecessary and harmful: there is nothing to observe.', value: 'risky' },
    ],
    options: [
      { id: 'sch', name: 'Schizophrenia', sub: 'The first diagnosis, from hearing a voice' },
      { id: 'norm', name: 'No disorder: a culturally normal religious experience', sub: 'Hearing a loved one in worship, valued by his community' },
      { id: 'dep', name: 'Depression with hallucinations', sub: 'Low mood with unusual experiences' },
    ],
    truth: 'norm', decisive: ['distress', 'fine', 'culture', 'only', 'nodel'],
    treatments: [
      { id: 'x1', label: 'Do not diagnose or medicate; record the cultural context, correct the notes and offer support if he wants it', verdict: 'best', why: 'By **failure to function adequately** and **deviation from ideal mental health** he shows **no abnormality**. By **social norms** the experience is **normal in his culture**. The earlier diagnosis shows **culture bias**, so the **record should be corrected**.' },
      { id: 'x2', label: 'Make no changes now but offer a review in three months to check', verdict: 'ok', why: 'Careful, but there is **no need to treat**. A review is sensible, as long as it is **offered**, not **imposed**.' },
      { id: 'x3', label: 'Start an antipsychotic drug', verdict: 'wrong', why: 'There are **no symptoms to treat**. The drug has side effects and would **label** a healthy man.' },
      { id: 'x4', label: 'Admit him under a section and start chlorpromazine', verdict: 'harm', why: 'This would **detain a healthy man** because of **cultural misunderstanding**, with side effects and lasting damage to his trust in services.' },
    ],
    outcome: {
      right: 'Winston\'s notes were corrected, with a letter explaining why. He told the team he had expected to be judged, and was relieved to be listened to. He did not return, and he was still driving the 52 two years later.',
      wrong: 'Winston was started on medication he did not need and lost his driving licence for several months. He stopped telling any doctor about his faith, and stopped trusting the NHS.',
    },
    twist: '**Hearing a voice** is a **positive symptom of schizophrenia**, so the first doctor applied the label. But **hallucinations** only suggest schizophrenia when they cause **distress**, come with **other symptoms** and **impair functioning**. Winston\'s experience is **valued in his culture**, he is **fully functioning** and has **no other symptoms**. This is **culture bias** in diagnosis.',
    lessons: ['p-abnormal', 'p-schiz-class', 'p-schiz-bio'],
    spec: { board: 'AQA', code: '7182', refs: ['Psychopathology: definitions of abnormality (social norms, failure to function, ideal mental health)', 'Schizophrenia: reliability and validity of diagnosis (culture bias)', 'Schizophrenia: classification (hallucinations)'] },
  });

  D.add({
    id: 'p10', track: 'psych', rank: 4, minutes: 10,
    title: 'First time, and then not', tagline: 'A student, a bad term, and a diagnosis that depends on what comes next',
    complaint: 'Hearing voices and believing she is being followed, five weeks after she stopped using cannabis',
    patient: { name: 'Ayesha Rahman', age: 21, job: 'University student', setting: 'Early intervention in psychosis service', image: P + 'p10.jpg',
      look: 'a twenty-one-year-old British Bangladeshi young woman with long dark hair in a loose ponytail, in a university hoodie, pale and withdrawn, looking guarded and unsettled, sitting in a plain clinic room with her older sister beside her' },
    opening: 'Ayesha\'s sister does most of the talking. Ayesha watches the door.',
    referral: 'Referred by the student health team. Ayesha **heard voices** and became convinced she was **being followed** after a **bad exam term** in which she was **smoking cannabis heavily**. She **stopped five weeks ago**, but **still hears the voices and still thinks she is followed**. Her tutor thinks it is **just the cannabis**. Her sister says she has been **withdrawn for a year**.',
    obs: [['Appearance', 'Unkempt, withdrawn'], ['Speech', 'Few words, flat'], ['Beliefs', 'Thinks she is being followed'], ['Last cannabis use', 'Five weeks ago']],
    notes: ['Voices and a belief she is followed, for several weeks.', 'Heavy cannabis use over the last term, now stopped for five weeks.', 'Withdrawn, with falling motivation, for about a year.', 'An aunt has been treated for schizophrenia.'],
    startFacts: ['voices', 'stopped'],
    facts: {
      voices: 'She hears voices and believes she is being followed', stopped: 'She stopped cannabis five weeks ago but the symptoms continue',
      aunt: 'Her aunt has schizophrenia', year: 'She had been withdrawn and unmotivated for about a year, before the cannabis',
      exam: 'The symptoms followed a very stressful exam term', screen: 'Her drug test is now negative', noinsight: 'She does not accept that anything is wrong',
      long: 'The symptoms have lasted for longer than a month', neg: 'She has avolition and speaks very little', nomood: 'Her mood is not low: she is frightened', trauma: 'She has been bullied online for months',
    },
    questions: [
      { id: 'q1', q: 'Tell me about the voices.', a: 'There are **three**. They talk about me. They say I am a **fraud**. I think they are **real**.', fact: 'voices' },
      { id: 'q2', q: 'When did you last use cannabis?', a: 'About **five weeks** ago. I stopped completely when I was scared.', fact: 'stopped' },
      { id: 'q3', q: 'Has anyone in the family been unwell?', a: 'My **aunt** in Dhaka. She was ill for years. We do not talk about it.', fact: 'aunt' },
      { id: 'q4', q: 'How were you before the exams?', a: 'I had **already pulled away** for about a year. I could not be bothered to see people.', fact: 'year' },
      { id: 'q5', q: 'What was the exam term like?', a: 'Awful. I had three exams in a week. I stopped sleeping.', fact: 'exam' },
      { id: 'q6', q: 'Do you think anything is wrong?', a: 'No. They really are following me. I have seen the same man four times.', fact: 'noinsight' },
      { id: 'q7', q: 'Do the voices and fears come and go?', a: 'They are there **all the time** now. Longer than a month.', fact: 'long' },
      { id: 'q8', q: 'How is your motivation and speech?', a: 'I do not do much. I do not see the point of talking.', fact: 'neg' },
      { id: 'q9', q: 'How is your mood?', a: 'Scared. I am not sad.', fact: 'nomood' },
      { id: 'q10', q: 'Has anything else upset you lately?', a: 'I was bullied online by a group. It has been months.', fact: 'trauma' },
      { id: 'q11', q: 'What are you studying?', a: 'Pharmacy.', value: 'waste' },
    ],
    tests: [
      { id: 't1', name: 'Urine drug screen', note: 'Is there any cannabis or other drug in her system now?', value: 'key', fact: 'screen', result: '**Negative**: no cannabis or other drugs. The symptoms **continue without the drug**.' },
      { id: 't2', name: 'Clinical interview: symptoms, timeline and insight', value: 'key', fact: 'long', result: '**Hallucinations and persecutory delusions** lasting **more than a month**, with **negative symptoms** (avolition, little speech) and **no insight**.' },
      { id: 't3', name: 'Family history', value: 'useful', fact: 'aunt', result: 'Her **aunt** has **schizophrenia**: a family history, so a **genetic vulnerability**.' },
      { id: 't4', name: 'Collateral history from her sister and tutor', value: 'useful', fact: 'year', result: 'Her sister describes **a year of withdrawal and falling motivation** before the cannabis. Her tutor remembers the **exam stress**.' },
      { id: 't5', name: 'Brain MRI scan', result: 'Normal. There is no scan to diagnose schizophrenia.', value: 'waste' },
      { id: 't6', name: 'Whole-body CT scan', note: 'Uses radiation', result: 'Normal. No reason for it.', value: 'risky' },
    ],
    options: [
      { id: 'sch', name: 'Schizophrenia, in a person with a vulnerability and several stressors', sub: 'Diathesis-stress' },
      { id: 'can', name: 'A cannabis-induced episode that is passing', sub: 'Symptoms caused by the drug alone' },
      { id: 'stress', name: 'A stress reaction to exams and bullying', sub: 'Stress alone, without a mental illness' },
    ],
    truth: 'sch', decisive: ['stopped', 'screen', 'aunt', 'year', 'long'],
    treatments: [
      { id: 'x1', label: 'An antipsychotic drug, CBT for the voices, family involvement and advice to avoid cannabis', verdict: 'best', why: 'The **diathesis-stress** model says her **vulnerability** (family history, an earlier decline) met **stressors** (exams, cannabis, bullying). **Drugs** block **dopamine**, **CBT** helps with the voices, **family** support reduces stress, and **avoiding cannabis** removes a trigger.' },
      { id: 'x2', label: 'Advise her to stay off cannabis and review in a week, with no medication', verdict: 'ok', why: 'Avoiding cannabis is right. But symptoms have **already lasted over a month without the drug**, so **waiting** delays treatment.' },
      { id: 'x3', label: 'Treat it as stress with relaxation classes', verdict: 'wrong', why: 'Stress played a part, but the **symptoms are those of psychosis**, and relaxation does not treat **hallucinations and delusions**.' },
      { id: 'x4', label: 'Decide it was the cannabis, and discharge her with no follow-up', verdict: 'harm', why: 'Her **drug test is negative** and symptoms continue. Untreated, a **first episode** of psychosis is likely to **get worse**.' },
    ],
    outcome: {
      right: 'Ayesha started an antipsychotic and weekly CBT, and her sister joined the family sessions. After four months the voices had quietened and she returned to her course, with a plan to stay clear of cannabis.',
      wrong: 'Ayesha was sent away on the assumption that it was the drug. The voices continued, and she was admitted to hospital three months later after a crisis.',
    },
    twist: 'Cannabis can produce **psychotic symptoms**, and exam stress is real, so it is easy to blame them. But if it were the drug alone, the symptoms would **fade after it was stopped**. Ayesha is **five weeks clean**, her **screen is negative**, her symptoms have lasted **over a month**, there is a **family history** and she had been **withdrawn for a year**. Several factors combined in a vulnerable person: **diathesis-stress**.',
    lessons: ['p-schiz-psych', 'p-schiz-bio', 'p-schiz-treat', 'p-schiz-class'],
    spec: { board: 'AQA', code: '7182', refs: ['Schizophrenia: the interactionist approach (diathesis-stress)', 'Schizophrenia: genetic basis and the dopamine hypothesis', 'Schizophrenia: antipsychotics, CBT and family therapy'] },
  });

})(typeof window !== 'undefined' ? window : globalThis);
