// Case 18 (Senior Junior, defence): assaulting a constable, where the arrest itself may have been unlawful.
LAW_CAREER.add({
  id: 'c18', rank: 2, special: false, minutes: 15, role: 'defence',
  title: 'R v Sato', tagline: 'An arrest that came with no reasons',
  charge: 'Assaulting a constable in the execution of his duty, contrary to section 89(1) of the Police Act 1996: on 15 September, outside the Regent Cinema, he assaulted PC Hollis while PC Hollis was acting in the execution of his duty.',
  briefing: 'Kenji Sato pulled his arm away and caught PC Hollis in the mouth during an arrest outside a cinema. He was arrested for being drunk and says he was sober and was never told why. You defend him. If the arrest was unlawful, the officer was not acting in the execution of his duty.',
  concepts: [
    { label: 'Assault on a police constable in the execution of duty', subtopic: 'Public order and policing', arises: 'When the barrister asks what the officer said when he arrested the client.', stage: 'interview', char: 'sat' },
    { label: 'Lawful arrest', subtopic: 'Police powers', arises: 'When the bodycam is shown to the officer.', stage: 'witness', char: 'hol' },
    { label: 'Burden and standard of proof', subtopic: 'Trial procedure', arises: 'In the closing speech.', stage: 'closing' },
  ],
  meta: { interviewCharacterId: 'sat', defendantId: 'sat' },
  facts: [
    ['f1', 'At about 22:10 on 15 September Kenji Sato pulled his arm away from PC Hollis during an arrest and his elbow struck PC Hollis\'s mouth.', 'p', 3],
    ['f2', 'PC Hollis had a swollen and cut lip.', 'p', 2],
    ['f3', 'PC Hollis was in uniform and said "I am arresting you".', 'p', 2],
    ['f4', 'PC Hollis did not tell Sato the reason for the arrest when he made it.', 'd', 4],
    ['f5', 'The bodycam shows the arrest announced with no grounds, and Sato asking "what for?" twice.', 'd', 4],
    ['f6', 'Sato\'s breath test an hour later showed zero alcohol.', 'd', 3],
    ['f7', 'Sato was filming PC Hollis dealing with another man on his phone, and the officer did not like it.', 'd', 3],
    ['f8', 'Sato refused to put his phone down when told.', 'p', 2],
    ['f9', 'Sato apologised at the scene and said he never meant to hit him.', 'd', 2],
    ['f10', 'Sato is a chef who was walking home from work.', 'n', 1],
  ],
  characters: [
    { id: 'sat', name: 'Kenji Sato', role: 'Defendant', side: 'd', look: 'a man of 38, chef\'s jacket under a coat, spectacles, calm demeanour', demeanour: 'Polite, bewildered, a little indignant', speech: 'Careful English, precise and courteous',
      knows: 'f1 f3 f4 f5 f6 f7 f8 f9 f10', believes: ['He did nothing wrong by filming, and the officer arrested him for it.'], remembers: ['He was filming the officer and another man.', 'The officer grabbed him and said "you\'re under arrest" with no reason.', 'He asked "what for?" twice and pulled away.', 'His elbow caught the officer\'s mouth by accident.'], gaps: ['He did not hear any reason given.'],
      rel: 'high', honesty: 'truthful', candour: 'full', by: 'd', order: 1,
      cross: [['You refused to put your phone down?', 'I did, yes. I thought I had the right to film.', 'f8'], ['And your elbow hit the officer\'s mouth?', 'Yes, I am very sorry. I was pulling away.', 'f1']] },
    { id: 'hol', name: 'PC Liam Hollis', role: 'Arresting officer', side: 'p', look: 'a man of 29, short fair hair, cut lip, police uniform', demeanour: 'Defensive about the arrest, annoyed about the filming', speech: 'Clipped and formal',
      knows: 'f1 f2 f3 f4 f5 f7 f8', believes: ['He was entitled to arrest anyone who refused his instructions.'], remembers: ['Sato was filming him and refused to stop.', 'He said "I am arresting you" and took hold of his arm.', 'He did not say why.', 'Sato pulled away and caught his lip.'], gaps: ['He cannot say what offence he had in mind when he arrested him.'],
      rel: 'medium', honesty: 'mistaken', by: 'p', order: 1, intro: 'e1',
      chief: [['What happened outside the cinema?', 'I was dealing with a drunk man. Mr Sato was filming and would not stop. I said "I am arresting you". He pulled away and his elbow caught my lip.', 'f1 f3 f8'], ['Were you hurt?', 'I had a cut and swollen lip.', 'f2']] },
  ],
  evidence: [
    { id: 'e1', kind: 'cctv', title: 'Bodycam footage, 22:09 to 22:11', caption: 'Worn by PC Hollis', content: { location: 'Outside the Regent Cinema', timestamp: '22:09:30', description: 'PC Hollis says "Put the phone down." Sato says "I\'m allowed to film." PC Hollis says "I am arresting you" and grabs Sato\'s arm. Sato says "What for?" twice and pulls away. No reason for the arrest is given.' }, facts: 'f3 f4 f5 f8', favours: 'neutral', by: 'hol' },
    { id: 'e2', kind: 'document', title: 'Breath test record', caption: 'Custody suite, 23:15', content: { title: 'Roadside/evidential breath test', paragraphs: ['Subject: Kenji Sato. Alcohol reading: 0 microgrammes in 100 ml of breath.'] }, facts: 'f6', favours: 'd' },
    { id: 'e3', kind: 'medical', title: 'Police medical note', caption: 'PC Hollis', content: { patient: 'PC Liam Hollis', author: 'Police surgeon', date: '15 September', sections: [{ heading: 'Injury', text: 'Swollen and cut lower lip, about 1 cm.' }] }, facts: 'f2', favours: 'p' },
    { id: 'e4', kind: 'statement', title: 'Statement of Kenji Sato', caption: 'Written on release', content: { witness: 'Kenji Sato', date: '16 September', paragraphs: ['I was filming because the officer was being rough with another man. He arrested me and gave no reason. I pulled away and my elbow hit him. I am sorry.'] }, facts: 'f9 f7', favours: 'd' },
  ],
  caseFile: {
    summary: 'PC Hollis arrested Mr Sato outside a cinema for refusing to stop filming. Mr Sato pulled away and caught the officer\'s lip. The officer gave no reason for the arrest. Mr Sato\'s breath test was zero.',
    agreed: ['Mr Sato\'s elbow struck PC Hollis\'s lip.', 'PC Hollis said "I am arresting you".', 'Mr Sato was sober.'],
    chargeSheet: 'Assaulting a constable in the execution of his duty, contrary to section 89(1) of the Police Act 1996.',
  },
  scripts: {
    arraignment: ['Kenji Sato, you are charged with assaulting a police constable in the execution of his duty. How do you plead?', 'Not guilty.'],
    pOpen: ['Members of the jury, the defendant refused to stop filming, refused an officer\'s instruction and then struck him in the mouth while being arrested.'],
    dOpen: ['Members of the jury, the officer arrested Mr Sato with no reason and no power. An officer making an unlawful arrest is not acting in the execution of his duty.'],
    pClose: ['Members of the jury, he was told to stop and would not, and he struck the officer. The Crown says the officer was acting in the execution of his duty.'],
    dClose: ['Members of the jury, an arrest without being told the reason is unlawful. If it was unlawful, the officer was not acting in the execution of his duty, and this charge cannot succeed.'],
    summing: ['Members of the jury, the defendant is presumed innocent and the prosecution must make you sure of guilt.', 'The Crown must prove that the defendant assaulted the officer and that the officer was acting in the execution of his duty at the time. An officer who unlawfully arrests someone is not acting in the execution of his duty.', 'A person must be told at the time of arrest, or as soon as is practicable, that they are under arrest and the grounds for it.'],
  },
  verdict: {
    threshold: 'auto',
    elements: [['He assaulted the officer', 'f1 f2'], ['The officer was acting in the execution of his duty', 'f3 f4 f5 f6 f7 f8']],
    sentences: [[0, 'The judge imposes a 12-month community order with a fine.'], [4, 'The judge imposes a 6-month custodial sentence suspended for 12 months.']],
    notGuilty: 'Members of the jury, thank you. Mr Sato, you are found not guilty and are free to go.',
  },
});
