// Case 13 (Senior Junior, prosecution): fraud by abuse of position, and a "bonus" email with a very recent timestamp.
LAW_CAREER.add({
  id: 'c13', rank: 2, special: false, minutes: 15, role: 'prosecution', officerId: 'ko',
  title: 'R v Reid', tagline: 'The bookkeeper and the false invoices',
  charge: 'Fraud by abuse of position, contrary to sections 1 and 4 of the Fraud Act 2006: between January and August she, occupying a position in which she was expected to safeguard the financial interests of Linden Dental Practice, dishonestly abused it, intending to make a gain of £31,400.',
  briefing: 'Tabitha Reid, the practice bookkeeper, paid £31,400 to a company she controlled through false invoices. She says the owner authorised the payments as bonuses. You prosecute, and the authorisation email may not be what it seems.',
  concepts: [
    { label: 'Fraud by abuse of position', subtopic: 'Fraud Act 2006', arises: 'When the prosecution shows she held a position of trust.', stage: 'opening' },
    { label: 'Dishonesty', subtopic: 'Theft and fraud', arises: 'When the defendant explains the bonus emails.', stage: 'witness', char: 'rei' },
    { label: 'Burden and standard of proof', subtopic: 'Trial procedure', arises: 'In the closing speech.', stage: 'closing' },
  ],
  meta: { interviewCharacterId: 'ko', defendantId: 'rei' },
  facts: [
    ['f1', 'Between January and August Tabitha Reid, the practice bookkeeper, paid £31,400 from Linden Dental Practice to Reid Admin Services.', 'p', 3],
    ['f2', 'Reid Admin Services was a company she had set up and controlled; the invoices were for work never done.', 'p', 3],
    ['f3', 'Reid was responsible for the practice\'s payments and was trusted to safeguard its money.', 'p', 2],
    ['f4', 'The "bonus authorisation" email from the owner was created on a laptop on the weekend before the police interview, according to metadata.', 'p', 4],
    ['f5', 'The owner, Dr Kapoor, never agreed any bonus above her normal £500 Christmas payment.', 'p', 3],
    ['f6', 'Reid had worked for the practice for eleven years and had never taken money before.', 'd', 2],
    ['f7', 'The practice had no second signatory or audit and had made informal cash gifts to staff before.', 'd', 3],
    ['f8', 'Reid says Dr Kapoor told her in the corridor that she could pay herself a "retention bonus".', 'd', 3],
    ['f9', 'Reid\'s husband lost his job in January and she was under financial pressure.', 'p', 1],
    ['f10', 'Reid repaid £6,000 after the fraud was discovered.', 'd', 2],
  ],
  characters: [
    { id: 'ko', name: 'DC Ifeoma Nwosu', role: 'Officer in the case', side: 'p', look: 'a woman of 36, smart black suit, braided hair, laptop bag', demeanour: 'Calm, exact', speech: 'Precise, forensic vocabulary',
      knows: 'f1 f2 f3 f4 f5 f7 f9 f10', believes: ['The email was created after the investigation began.'], remembers: ['The invoices, the bank transfers and the company registration in Reid\'s name.', 'The metadata on the "authorisation" email.', 'Dr Kapoor denies any bonus.', 'Reid repaid £6,000.'], gaps: [],
      rel: 'high', honesty: 'truthful', candour: 'full', by: 'n', order: 1 },
    { id: 'kap', name: 'Dr Anjali Kapoor', role: 'Practice owner', side: 'p', look: 'a woman of 52, white coat, neat bob, tired eyes', demeanour: 'Hurt and angry, but honest about the loose management', speech: 'Measured, a little tight-lipped',
      knows: 'f1 f3 f5 f6 f7', believes: ['Reid betrayed her trust.'], remembers: ['She only agreed a £500 Christmas bonus.', 'She never saw the invoices from Reid Admin Services.', 'She never had a second signatory and sometimes gave staff cash gifts.', 'She trusted Reid for eleven years.'], gaps: ['She did not check the accounts.'],
      rel: 'high', honesty: 'truthful', by: 'p', order: 1, intro: 'e1',
      cross: [['You never audited the accounts?', 'No. I trusted her completely.', 'f7']],
      chief: [['Did you agree any bonus for Ms Reid?', 'Only the £500 Christmas bonus. Nothing like £31,000.', 'f5'], ['What was her role?', 'She handled all payments. I relied on her to protect the practice\'s money.', 'f3']] },
    { id: 'rei', name: 'Tabitha Reid', role: 'Defendant', side: 'd', look: 'a woman of 44, neat grey suit, pinched face, clutching a tissue', demeanour: 'Defensive then tearful when confronted with the metadata', speech: 'Prim, quick to explain',
      knows: 'f1 f2 f3 f4 f6 f7 f8 f9 f10', believes: ['She is a good person who panicked.'], remembers: ['She set up the company in January.', 'Dr Kapoor never gave her a bonus; she wrote the email herself later.', 'Her husband lost his job.', 'She paid back £6,000 when she was caught.'], gaps: [],
      rel: 'low', honesty: 'lying', hide: 'f2 f4 f9', lie: 'She says Dr Kapoor told her in the corridor to pay herself a retention bonus and that the email confirmed it. In truth she made the email herself after being questioned and Reid Admin Services invoiced for no work.', candour: 'guarded', by: 'd', order: 1,
      chief: [['Why did you pay Reid Admin Services?', 'Dr Kapoor told me I could give myself a retention bonus. I just wanted it recorded properly.', 'f8'], ['Is that how you have behaved for eleven years?', 'I have never taken a penny before.', 'f6']] },
  ],
  evidence: [
    { id: 'e1', kind: 'document', title: 'Reid Admin Services invoices and bank transfers', caption: 'Fourteen payments', content: { title: 'Invoices and transfers', paragraphs: ['Fourteen invoices from Reid Admin Services for "administration support" between January and August, total £31,400. Company registered 4 January; director and sole shareholder: Tabitha Reid.'] }, facts: 'f1 f2', favours: 'p', by: 'kap' },
    { id: 'e2', kind: 'messages', title: '"Bonus authorisation" email', caption: 'Said to be from Dr Kapoor', content: { participants: ['Dr Kapoor', 'Tabitha'], messages: [{ from: 'Dr Kapoor', time: '14 March', text: 'Tabitha, as discussed, please pay yourself the retention bonus through your company. A.' }] }, facts: 'f8', favours: 'd' },
    { id: 'e3', kind: 'document', title: 'Email metadata analysis', caption: 'Digital forensics', content: { title: 'Forensic report', paragraphs: ['The file was created on a laptop belonging to Ms Reid on 22 November, two days before her police interview. The displayed date of 14 March was typed in the header, not set by the mail server.'] }, facts: 'f4', favours: 'p' },
    { id: 'e4', kind: 'document', title: 'Repayment record', caption: 'Bank statement', content: { title: 'Statement extract', paragraphs: ['Transfer of £6,000 from Ms Reid to the practice account on 10 October, reference "returning money".'] }, facts: 'f10', favours: 'd' },
  ],
  caseFile: {
    summary: 'Ms Reid paid £31,400 from the dental practice to a company she controlled, using invoices for work not done. She says the owner authorised the payments as a retention bonus and produced an email to prove it. The Crown says the email was made after she was caught.',
    agreed: ['Fourteen payments were made to Reid Admin Services.', 'Ms Reid controlled that company.', 'Ms Reid repaid £6,000.'],
    chargeSheet: 'Fraud by abuse of position, contrary to section 4 of the Fraud Act 2006.',
  },
  scripts: {
    arraignment: ['Tabitha Reid, you are charged with fraud by abuse of position. How do you plead?', 'Not guilty.'],
    pOpen: ['Members of the jury, the defendant was trusted with a practice\'s money and paid £31,400 of it to her own company for work that never happened.'],
    dOpen: ['Members of the jury, Dr Kapoor agreed the bonus in a corridor conversation and an email. This is a dispute about authority, not fraud.'],
    pClose: ['Members of the jury, the email was written two days before her interview. The company, the invoices and the lie tell you what she knew. The Crown asks you to be sure she was dishonest.'],
    dClose: ['Members of the jury, a practice with no audit, cash gifts and a trusted bookkeeper of eleven years. The Crown has not made you sure she was dishonest.'],
    summing: ['Members of the jury, the defendant is presumed innocent and the prosecution must make you sure of guilt.', 'The Crown must prove that she held a position in which she was expected to safeguard the practice\'s financial interests, that she abused it, that she was dishonest, and that she intended to make a gain.', 'If she believed she was authorised, you must consider whether that belief was genuine, and what the evidence of the email tells you about it.'],
  },
  verdict: {
    threshold: 'auto',
    elements: [['She held a position of trust', 'f3 f6 f7'], ['She abused it', 'f1 f2 f4 f5'], ['She acted dishonestly', 'f4 f8 f9 f10']],
    sentences: [[0, 'The judge sentences Tabitha Reid to 18 months\' imprisonment, suspended for two years, with a compensation order.'], [4, 'The judge sentences Tabitha Reid to 3 years\' imprisonment, noting the abuse of long-standing trust.']],
    notGuilty: 'Members of the jury, thank you. Ms Reid, you are found not guilty and are free to go.',
  },
});
