// Plays, once, everything a new game starts with, so that every game starts the same and nothing has to be played at the start:
//   FM.PRESEASON    the pre-season friendlies of the shared league
//   FM.LAST_SEASON  a whole previous season of the same league: its final table and every match of the club the player manages
// The matches of the managed club keep a (slimmed) log, so the statistics pages, Elena's lessons and the opposition reports have real data to
// work on before the first league game. Run again (node create/football/tools/gen_preseason.js) after any change to the match engine or the
// clubs, then commit preseason.js.
global.window = global;
const path = require('path'), fs = require('fs');
const dir = path.resolve(__dirname, '..') + '/';
['formations', 'roles', 'ratings', 'names', 'engine', 'rules', 'instructions', 'fitness', 'match', 'league', 'stats_math', 'stats', 'stats_top', 'news'].forEach((f) => { try { require(dir + f + '.js'); } catch (e) { console.log('skipped', f, e.message); } });

// Only what the statistics read: passes, tackles and shots. Dribbles, the heat map and clips are left out to keep the file small.
const slim = (log) => (log ? {
  teams: log.teams, duration: log.duration, dribbles: [],
  passes: log.passes.map((p) => [p[0], p[1], p[2], p[3], p[4], Math.round(p[5]), 0, p[7], p[8], p[9]]),
  tackles: log.tackles.map((t) => [t[0], t[1], t[2], t[3], t[4], Math.round(t[5]), 0]),
  other: (log.other || []).filter((e) => e.type === 'shot').map((e) => ({ t: e.t, type: 'shot', team: e.team, player: e.player, xg: e.xg, outcome: e.outcome })),
} : null);

// ---- the pre-season friendlies ----
const league = FM.createLeague({ userIndex: 0 });
const me = league.userId;                      // the club a player manages: its matches are the ones that keep a log
league.friendlies.forEach((f) => FM.simulateFixture(league, f, 0.25));
const friendlies = league.friendlies.map((f) => { const o = JSON.parse(JSON.stringify(f)); o.log = slim(f.log); delete o.clips; return o; });

// ---- last season: the same league and squads, every fixture played with its own seeds ----
const past = FM.createLeague({ userIndex: 0 });
past.fixtures.forEach((f) => { f.seed = (f.seed || 1) + 99991; });
past.fixtures.forEach((f) => FM.simulateFixture(past, f, 0.25));
const rows = {};
past.teams.forEach((t) => { rows[t.id] = { id: t.id, name: t.name, P: 0, W: 0, D: 0, L: 0, GF: 0, GA: 0, Pts: 0 }; });
past.fixtures.forEach((f) => {
  if (!f.played) return;
  const h = rows[f.homeId], a = rows[f.awayId];
  h.P++; a.P++; h.GF += f.hg; h.GA += f.ag; a.GF += f.ag; a.GA += f.hg;
  if (f.hg > f.ag) { h.W++; a.L++; h.Pts += 3; } else if (f.hg < f.ag) { a.W++; h.L++; a.Pts += 3; } else { h.D++; a.D++; h.Pts++; a.Pts++; }
});
const table = Object.values(rows).sort((a, b) => b.Pts - a.Pts || (b.GF - b.GA) - (a.GF - a.GA) || b.GF - a.GF || a.name.localeCompare(b.name));
table.forEach((r, i) => { r.pos = i + 1; r.GD = r.GF - r.GA; });
const mine = past.fixtures.filter((f) => f.played && (f.homeId === me || f.awayId === me)).map((f) => ({
  id: 'ls' + f.id, round: f.round, homeId: f.homeId, awayId: f.awayId, played: true, hg: f.hg, ag: f.ag, history: true, log: slim(f.log),
}));
const lastSeason = { me, table, matches: mine };

const head = '// Generated by tools/gen_preseason.js: the pre-season friendlies and last season of the shared league, played in advance.\n';
fs.writeFileSync(dir + 'preseason.js', head + '(function () { const FM = (window.FM = window.FM || {}); FM.PRESEASON = ' + JSON.stringify(friendlies) + '; FM.LAST_SEASON = ' + JSON.stringify(lastSeason) + '; })();\n');
console.log('wrote', friendlies.length, 'friendlies and', mine.length, 'matches of last season,', Math.round(fs.statSync(dir + 'preseason.js').size / 1024), 'kB');
table.forEach((r) => console.log(String(r.pos).padStart(2), r.name.padEnd(22), r.P, r.W, r.D, r.L, r.GF + '-' + r.GA, r.Pts + ' pts', r.id === me ? '<- the managed club' : ''));
console.log('friendlies with a log:', friendlies.filter((f) => f.log).length);
