// Plays the pre-season friendlies for the shared league once and writes preseason.js, so no game has to play them at the start.
// Run again (node create/football/tools/gen_preseason.js) after any change to the match engine or the clubs, then commit preseason.js.
global.window = global;
const path = require('path'), fs = require('fs');
const dir = path.resolve(__dirname, '..') + '/';
['formations', 'roles', 'ratings', 'names', 'engine', 'instructions', 'fitness', 'match', 'league', 'stats_math', 'stats', 'stats_top', 'news'].forEach((f) => { try { require(dir + f + '.js'); } catch (e) { if (!/document|localStorage/.test(e.message)) throw e; } });
const league = FM.createLeague({ userIndex: 0 });
league.userId = null; // every club is computer-run in these friendlies, whichever club a player later chooses
league.friendlies.forEach((f) => FM.simulateFixture(league, f, 0.25));
const out = league.friendlies.map((f) => JSON.parse(JSON.stringify(f)));
fs.writeFileSync(dir + 'preseason.js', '// Generated by tools/gen_preseason.js: the pre-season friendlies of the shared league, played in advance.\n(function () { const FM = (window.FM = window.FM || {}); FM.PRESEASON = ' + JSON.stringify(out) + '; })();\n');
console.log('wrote', out.length, 'friendlies,', Math.round(fs.statSync(dir + 'preseason.js').size / 1024), 'kB');
out.forEach((f) => console.log(f.homeId, f.hg + '-' + f.ag, f.awayId));
